### ISSUE TITLE
You can "shake" orbiting ghosts by hiding in a locker

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#15689] opened 2016-02-22 18:55 UTC
If you've got orbiting ghosts walk into a closet, the ghost orbit will physically enter the closet with you, and when you open the closet the ghosts will no longer be orbiting and won't automatically track you anymore (unless they manually start a new orbit)

It used to be that orbits stayed on the turf while a target was inside something, but it seems that this behavior changed recently.

**Comment by phil235** [comment] 2016-02-22 19:14
Dupe of #15612

**Closed by phil235** 2016-02-22 19:14 UTC

**Comment by Incoming5643** [comment] 2016-02-22 19:17
:warning: whoops :warning:

**Comment by duncathan** [comment] 2016-02-22 19:58
I'm glad that people are ignoring the issue template even with it right in the body
