### ISSUE TITLE
Unbuckling mobs from meatspikes is either broken or inconsistant

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#17852] opened 2016-05-22 15:08 UTC
Normal structures that allow you to 'buckle in' mobs allow you to unbuckle them by clicking the structure's sprite, but for meatspikes nothing seems to happen.

**Comment by phil235** [comment] 2016-05-22 19:14
it's broken, I think this is a duplicate

**Comment by optimumtact** [comment] 2016-05-23 07:45
Duplicate of #16186

**Closed by optimumtact** 2016-05-23 07:45 UTC
