### ISSUE TITLE
THE RETURN OF THE ZOMBIE IAN: Dead corgis and meat spikes

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12115] opened 2015-10-02 19:35 UTC
Putting a dead corgi on a meatspike results in the regular corgi sprite being on the spike, right side up, and you are able to attack it for a few hits before it bursts into hide and meat. 2SPOOKY.

@KorPhaeron

**Comment by Niknakflak** [comment] 2015-10-03 07:23
GOD DAMNIT. WHY WOULD YOU REUSE THE NAME OF THE ISSUE I CAUSED

**Comment by KorPhaeron** [comment] 2015-10-04 19:52
It takes the Xs of their eyes?

**Comment by KorPhaeron** [comment] 2015-12-21 15:04
@tkdrg 

The corgi death sprite is just a corgi flipped 180 degrees with Xs on its eyes, and the meatspike flips it 180 when it dies (though it still has X eyes)

Short of a new dead corgi sprite this is unresolvable/not a bug/not something I'm going to fix (because it'd require an istype for corgis or something)

**Comment by tkdrg** [comment] 2015-12-21 15:24
I don't even understand this report. I'll test it later I guess, not even sure if this is a bug or a feature request.

**Comment by bgobandit** [comment] 2016-01-07 13:29
the point is, if you place a dead corgi on a meatspike the mob meatspike code kicks in, resulting in an alive-looking corgi sprite that you can attack and butcher

**Comment by phil235** [comment] 2016-02-24 20:11
It doesn't really look alive when its eyes are x's. But yeah, it doesn't exactly look pretty.

**Comment by phil235** [comment] 2016-03-03 11:51
@KorPhaeron

**Comment by optimumtact** [comment] 2016-05-23 07:44
Duplicate of #15585 and that is more general than this one

**Closed by optimumtact** 2016-05-23 07:44 UTC
Labels: Bug
