### ISSUE TITLE
Solid Plasma Not Yielding Liquid

### ISSUE THREAD

**Issue by Skorvold** [tgstation/-tg-station#17862] opened 2016-05-22 22:04 UTC
1. Insert Solid Plasma into a reagent grinder/blender whatever.
2. Grind
3. Receive nothing

**Comment by Boredone** [comment] 2016-05-22 22:07
Likely fixed if reproduced on Sybil, server is just not updated with the fix. Can't tell on Basil if that's updated or not though.

**Comment by bgobandit** [comment] 2016-05-22 22:27
specifically, likely due to https://github.com/tgstation/-tg-station/issues/17813

**Comment by ChangelingRain** [comment] 2016-05-22 22:34
This is basically a dupe of that issue, so.

**Closed by ChangelingRain** 2016-05-22 22:34 UTC
