### ISSUE TITLE
Strange Reagent does not work

### ISSUE THREAD

**Issue by S0ldi3rKr4s0** [tgstation/-tg-station#7201] opened 2015-01-19 18:43 UTC
Steps to reproduce:
1. Have someone die
2. Heal them up
3. Feed them a strange reagent pill
4. Watch as your fellow co-worker does not come back from death and shed a single patriotic tear

![2015-01-19_17-15-35](https://cloud.githubusercontent.com/assets/3855300/5803479/13e3a72c-9fff-11e4-9060-7bbc36e9a7f3.png)
![2015-01-19_17-15-45](https://cloud.githubusercontent.com/assets/3855300/5803482/18e42382-9fff-11e4-8767-c1ebb320b71b.png)

**Comment by Deantwo** [comment] 2015-01-19 22:49
Kinda a duplicate of https://github.com/tgstation/-tg-station/issues/7154.

**Comment by tkdrg** [comment] 2015-01-21 21:09
Closing this as a dupe.

**Closed by tkdrg** 2015-01-21 21:09 UTC
