### ISSUE TITLE
Airlock electronics are broken.

### ISSUE THREAD

**Issue by TheNightingale** [tgstation/-tg-station#8875] opened 2015-04-10 16:00 UTC
Problem Description: Airlock electronics can't be used airlock assemblies.
What did you expect to happen: I expected the airlock electronics to go into the assembly like they usually do.
What happened instead: Instead, they appeared on top like I'd moved during the construction.
Why is this bad/What are the consequences: It means drones can't fix airlocks.
Steps to reproduce the problem: Make an airlock assembly, wire it, and try and put airlock electronics in.
Server: Basil, ~16:00 GMT
Revision: 7e5f6aba3cdc569ae580c40d06f204ce217aa4ad
Possibly related stuff: N/A

**Comment by phil235** [comment] 2015-04-10 16:48
duplicate of #8869

**Closed by phil235** 2015-04-10 16:48 UTC
