### ISSUE TITLE
Doors: Fast Close Doesn't work

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10326] opened 2015-07-02 02:57 UTC
Currently, if you override a door's timings and open it, it won't close nearly immediately; it behaves exactly as a normal door--as a matter of fact, doors that have their timing overridden will actually *never* close, once opened.

**Comment by Supermichael777** [comment] 2015-07-02 03:53
door code is a mess, a readable mess but still so bloated that I can't even find where the timing toggle is.

**Comment by phil235** [comment] 2015-07-02 10:21
duplicate of #7039

**Closed by phil235** 2015-07-02 10:21 UTC
