### ISSUE TITLE
Golems take damage from stepping in glass

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#6951] opened 2015-01-10 21:22 UTC
Why hasn't this been fixed yet?

**Comment by WJohn** [comment] 2015-01-10 21:37
As do people with augmented legs.

**Comment by MMMiracles** [comment] 2015-01-10 21:55
Augmented people can wear shoes, golems can't.

**Comment by WJohn** [comment] 2015-01-10 22:29
Even then, having metal robot feet should be protected from glass. Also nice when you're showing YOUR ROBO FORM.

**Comment by Tenebrosity** [comment] 2015-01-11 03:29
Yeah, like, if you ever had a friend with no legs in high school, you should be sure to know that he can walk on white hot cement and/or sharp objects without repercussion.

**Comment by WJohn** [comment] 2015-01-11 03:51
If he has robo legs? Yeah he's not exactly going to feel any of that.

**Comment by AnonymousNow** [comment] 2015-01-11 04:17
To be fair, one is a set of reinforced metal feet, and the other is a set of solid, magical metal feet. Neither should even notice stepping on glass.

**Comment by tkdrg** [comment] 2015-01-11 05:57
Dupe of #6477

**Closed by tkdrg** 2015-01-11 05:57 UTC
