### ISSUE TITLE
Guns charge overlays are missing when you pick them up

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#17253] opened 2016-04-29 20:45 UTC
1. Pick taser up.

2. Taser overlays are now missing.

**Comment by phil235** [comment] 2016-04-29 21:12
Caused by #17086

**Comment by MrPerson** [comment] 2016-04-30 00:24
phil on the money as usual

**Comment by phil235** [comment] 2016-04-30 10:04
I'll close this one and keep #17242 which is more general.

**Closed by phil235** 2016-04-30 10:04 UTC
Labels: Bug
