### ISSUE TITLE
some late joins are spawning in the lobby screen

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#9874] opened 2015-06-10 04:06 UTC
They late join, and get spawned with everything they should have, but never leave the lobby screen area, and are a human mob in the middle of it.

It seems to be robottist that does it, but who knows.

@Incoming5643

**Comment by Incoming5643** [comment] 2015-06-10 04:37
If they're getting job clothes assigned properly I haven't changed anything recently that would cause this, at least not that I can think off the top of my head.

You're saying this is happening only to roboticists ? Is there something unique to the roboticists starting loadout that's had a path change recently? There is probably an associated run time for this.

**Comment by Jordie0608** [comment] 2015-06-10 05:35
Likely caused by my changes in #9721, although I don't see what's broken there.

**Comment by Incoming5643** [comment] 2015-06-10 05:39
Singulo eating the arrivals shuttle?

**Comment by MrStonedOne** [comment] 2015-06-10 06:08
nope. a few were shortly (~10 minutes) after round start.

**Comment by freerealestate** [comment] 2015-06-10 13:35
I have always wanted to run around on the title screen.

**Comment by francinum** [comment] 2015-06-11 21:17
@freerealestate It's all walls. except for 1 tile in the center which is floor.

**Comment by Ikarrus** [comment] 2015-06-18 02:24
Can we get this escalated it's occurring every round to a roboticist.

**Comment by Incoming5643** [comment] 2015-06-18 02:33
All I can tell you is it's not replicatable on a one person test server. I spawned in as robotocist no less than 20 times and it never happened.

I even tried closing all other job slots, nothing.

**Comment by Miauw62** [comment] 2015-06-18 09:31
I suspect it is the SECOND roboticist slot that is causing the issue.

**Comment by Incoming5643** [comment] 2015-06-18 15:44
Can confirm, if both slots are filled at round start only the first is placed.

No associated runtime 

:question:

**Comment by Incoming5643** [comment] 2015-06-18 15:58
There's only one map spawn location for roboticists on box instead of two. I'm testing to see if this is what the problem is now.

**Comment by Incoming5643** [comment] 2015-06-18 16:19
That's what it is. Someone just needs to plop down a second start landmark in robotics for the missing slot. I was going to do this myself but I accidentally made the edit on an outdated map and now I gotta jet for a while before I can fix this.

If no one gets to it before me I'll take care of it in a few hours.

**Comment by freerealestate** [comment] 2015-06-19 00:41
I wonder what made this an issue

For like a year roboticists would just spawn on top of each other in
robotics

**Closed** 2015-06-20 05:39 UTC
Labels: Bug, Priority: High
