### ISSUE TITLE
Bluespace artillery button on the centcom message doesn't work

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11453] opened 2015-08-29 02:04 UTC
Steps to reproduce:
1. Be an admin
2. Send a direct message to centcom.
3. See this message and see the various buttons including respond to, and BSA
4. Clicking the BSA button does not shoot artillery at them, it does nothing
5. Right click version of BSA still works.
6. Have to right click the person instead of hitting the easy to use link in the centcom message
7. cry over 3 extra seconds of work

**Comment by Jordie0608** [comment] 2015-08-29 06:37
Dupe of #10764

**Closed by Jordie0608** 2015-08-29 06:37 UTC
Labels: Administration, Bug
