### ISSUE TITLE
Strange workaround for changeling ability regenerative stasis

### ISSUE THREAD

**Issue by Falamazeer** [tgstation/-tg-station#9589] opened 2015-05-21 20:48 UTC
Problem Description: What is the problem? 
Changeling regenerative stasis it bugged.

What did you expect to happen: Why do you think this is a bug? 
You are supposed to be able to regenerate even after death.

What happened instead: How is what happened different from what you expected?
You gain a pulse for a second, then die again

Why is this bad/What are the consequences: Why do you think this is an important issue?
It's a signature ability of the changeling

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.

Server: Which server were you playing on? sybil

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us

 It is known that regen stasis is bugged, you use it, and try to move and you die again. I was experimenting with it on sybyl to see if I could trick it into working by changing my mob type into monkey. it worked, the trick for replicating this is to press regenerate after you have waited out the stasis And while your Pulse marker is still red, quickly press lesser form, and you will successfully survive the process, the same is true in reverse, A dead monkey can become a live human, though it is harder due to the prompt for which human you chose to be.

I hope this helps, if nothing else, you could make regenerate also change your form as part of the expected process and it might fix it, I also tried it with fleshmend and it was a failure, something about changing mob types allows this to work.

**Comment by Falamazeer** [comment] 2015-05-21 20:57
Further note, this can also be used in the short time of being not dead to activate the move last resort, and become a headslug

**Comment by Miauw62** [comment] 2015-05-25 10:24
this is a dupe of #9456

**Closed by Miauw62** 2015-05-25 10:24 UTC
