### ISSUE TITLE
The Janitor Job is broken

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#6814] opened 2015-01-05 10:44 UTC
Its design at the core is just fully broken and not able to stand up to the current needs of our playerbase.

@GunHog (bot ideas)
@paprka
and anyone else what ideas do you have which could improve this?

**Comment by Jalleo** [comment] 2015-01-05 10:52
The dirt change only proved that this was a issue automation of this job is not something everyone wants.

**Comment by dezzmont** [comment] 2015-01-05 10:59
The Janitor job isn't broken.

It was meeting the needs of the playerbase just fine. You didn't see many complaints about the job, it was even held up as an ideal for RP jobs in a few ideas threads.

The problem is the new dirt code fundementally doesn't do what it wanted to do. It was intended to be a way for the station to naturally get dirty over time but the problem is that:

A: It gets dirty so fast that you have the Red Queen problem where a bad janitor can in fact made the station more dirty by walking about and is endlessly playing catch up. In a station with 50 people assuming that the average job walks 5 tiles every 10 seconds in order to account for things like chemists, you are getting 1.2 dirt clods a second.

This is a relatively low round pop. When looking at 80 players a dirt clod would be generated every .75 seconds. If we are realistic and assume that the round has a lot of moving jobs like engineers, assistants, sec, ect, and bump it up to 10 per 10, you are looking at 3 clods a second.

3 new dirt tiles a second.

That means in a minute of play on a busy round 180 dirt clods will form.

and the other problem

B: The way the dirt comes about doesn't feel natural at all. It feels highly unnatural because people know dirt magically apearing from nowhere doesn't make any real sense. It is ugly and invasive.

While I like the idea of the janitor getting automation effects, pretending that the janitor is broken is self deception. Dirt just didn't work.

**Comment by Jalleo** [comment] 2015-01-05 11:05
I dont object to the dirt change the dirt change is awful but before then how many times did the janitor get overwhelmed due to too many people getting killed and whatever etc etc.
To be honest after you had at least 5 or 6 people dead and dragged to medical how long does it take to clean?
For quite a while people were saying get closets and drag people just to prevent the blood going everywhere.
The playerbase made their own bandaid fix with that.

**Comment by dezzmont** [comment] 2015-01-05 11:12
But the thing is that blood trails are generally a very localized and temporary problem. You will only find them encompasing the station in two situations.

1: An Artist goes a bit crazy and coats everything. Yes, pain. Takes forever, many janitors clean up. But it honestly takes a lot of effort to do this.

2: More than one corpse is being created for each corpse trail the janitor cleans. In this situation the janitor's job should be impossible not just by design but because more than one person is getting killed rapidly. At this point the station should look like a horror show because in the average round this would mean that there is about 5% of the crew dying each minute.

**Comment by Jalleo** [comment] 2015-01-05 11:14
Trails can be very long especially if it comes from crew quaters or anything in that type of distance.

**Comment by dezzmont** [comment] 2015-01-05 11:21
Long is fine as long as it is still a contained phenomina.

Blood trails are contained. They have a lot of qualities about them that are actually positive, they create the illusion of a larger task than actually exists and have a defined source and scope of the problem based on the distance the corpse was dragged. A janitor can be sure that after he cleans the trail it will not magically re-appear unless someone else dies, meaning that cleaning the blood trail actually acomplishes a goal.

Dirt clods have none of these qualities, which is why players are complaining now, not about blood trails.

**Comment by Jalleo** [comment] 2015-01-05 11:26
Yeah but normally when there is one there is more

**Comment by dezzmont** [comment] 2015-01-05 11:35
Not unless the station i falling apart.

Erro used to have really good stat tracking functionality in his server. We actually had pretty good data on when people died, and generally deaths were rather scattered and isolated early on, and exploded in density as the round goes on.

This is not a bug or undesired, this is a logical sequence of play. An early body leaves a grisly trail for the janitor to clean up. Cool.

As the game progresses and things start to spiral out of control the station naturally becomes dirty faster than the janitor can clean up to refect how horrific it is to have 10% of the station die within 5 minutes of each other. The janitor is not supposed to be able to realistically clean up endlessly, eventually the mess out paces them, the station is deliberately an entity of gradual entropy that starts an exponential dive in quality as the round goes on.

**Comment by Jalleo** [comment] 2015-01-05 11:45
Yeah and due to how Erro acted we lost it and I liked that feature and yes its a logical sequence of play but for the janitor mechanic its bad.
By how you suggest it the better way for dirt is to increase the rate dirt is made over the course of a round and not making it tick up for every single tile which would make sense but still the Janitor mechanic is just boring and repetitive but its got to be.

**Comment by Steelpoint** [comment] 2015-01-05 11:51
Why not have the janitor have to regularly maintain scatted "dust collectors" around the station akin to a air conditioner?

You get a PDA menu/notification system of the status of the collectors, if they start to fail you just need to go to it and reset it, maybe empty the bag. If it fails the area will collect dirt.

**Comment by Jalleo** [comment] 2015-01-05 11:52
Thats the sort of ideas that I was hoping for.

**Comment by GunHog** [comment] 2015-01-05 12:50
Cleanbots are easy to make, I feel their only problem as of the dirt update is that are too slow. Also, they can detect the dirt before it is visible, so they are near constantly cleaning up in high traffic areas.

The most obvious solution is to make them clean faster (by lowering cleaning cooldown). It may also be an option to switch their emag foam to an actual cleaning type so they could whip up large areas at once, but that is probably OP.

We really should tone down the rate, though. Find a sweet spot so that Janitors are appreciated, but not so high that they cannot keep the station clean.

**Comment by Dorsisdwarf** [comment] 2015-01-05 17:44
Pap's PR should make this better. Instead of 1 obvious dirt in 30 easy steps, it's now 100 steps for very pale dirt which gets dirtier the more people step in it. Still band-aid-y compared to tracking dirt from maint / dust collectors or whatever, but should make janitors less overwhelmed.

**Comment by Czarcastic** [comment] 2015-01-06 00:50
He just needs some heavy buffs to be actually useful for once. Even before the dirt update cleaning up messes took a ridiculous amount of time.

**Comment by paprka** [comment] 2015-01-06 02:28
I'll work on the janitor's gear a bit later.

**Comment by paprka** [comment] 2015-01-06 05:46
My main solution to this is replacing the 'advanced mop' in research with a floor buffer that can also be ordered through cargo for enough points. It would essentially work like the janiborg, equip and clean tiles you're standing on.

(or we could bring back the pussy wagon and add a 'floor buffer' upgrade to it so you can smite the dirt with style)

**Comment by Jalleo** [comment] 2015-01-06 09:41
really we need to look at the janitor job from the ground up again because its really been a oversight of development we just left it as a side project if people wanted to do something with it.

Should the cleaning grenades leave grenade casings for the janitor to get refills to make cleaning large areas more easy?

**Comment by Cheridan** [comment] 2015-01-30 21:10
Fixed by #7087 :monkey_face:

**Closed by Cheridan** 2015-01-30 21:10 UTC
Labels: Not a bug
