### ISSUE TITLE
Hey, how to fix the white ship?

### ISSUE THREAD

**Issue by nopm** [tgstation/-tg-station#7168] opened 2015-01-18 14:32 UTC
I saw somewhere in one of the wikis that the white abandoned ship can be fixed, but i need the right circuit board. also, sorry for posting this in issues.

**Comment by WJohn** [comment] 2015-01-18 14:50
Dupe of #7153
White ship currently can't be built, this is a bug.

**Closed** 2015-01-18 16:06 UTC
