### ISSUE TITLE
Canisters and gas tanks won't transfer gas between them.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#13746] opened 2015-12-17 23:38 UTC
![untitled](https://cloud.githubusercontent.com/assets/4951579/11885197/85231422-a517-11e5-8d86-db2ce1fd3859.png)

**Comment by as334** [comment] 2015-12-18 03:26
This is a dupe of #13671

**Comment by duncathan** [comment] 2015-12-18 23:39
This one is a dupe yeah, I forgot to close it when xxalpha and I started talking about a related issue that turned out to not be a bug

**Closed by duncathan** 2015-12-18 23:39 UTC
Labels: Atmos, Bug
