### ISSUE TITLE
Cheating Orion Trail (Enter spam edition)

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11401] opened 2015-08-26 06:05 UTC
watched a player do this and reproduced it a few times.  You can spam enter using some tab stuff at the end screen of the orion trail to have it spit out anywhere from 3-9 toys.

Steps to reproduce:
1. Beat the orion trail until you are on the screen where it says "Welcome to Orion" or whatever and you just need to press continue once more to have it spit out a toy
2. Press tab until you see the little outline over the continue button
3. Spam the fuck outta enter 
4. Watch it congratulate you like 8 times and spit out 8 toys too!
5. Repeat for INFINITE TOY GOODNESS OH LA LA

**Comment by Iamgoofball** [comment] 2015-08-26 06:09
brb aquiring maximum nukes

**Comment by Core0verload** [comment] 2015-08-26 07:13
Not a bug. Do not fix. Stop removing my fun.

**Comment by Jalleo** [comment] 2015-08-26 09:46
@remierichards

**Comment by Dorsisdwarf** [comment] 2015-08-26 21:01
May be a dupe 

Now I have to search the backlog :(

**Comment by Jalleo** [comment] 2015-08-26 21:02
technically it is because it should of been fixed

**Comment by Dorsisdwarf** [comment] 2015-08-26 21:08
Allegedly fixed in #10898 , but clearly @RemieRichards fix didn't work

**Comment by Jalleo** [comment] 2015-08-26 22:19
It fixed most of it but not all of it

**Closed** 2015-09-06 03:26 UTC
Labels: Bug, In Game Exploit
