### ISSUE TITLE
Cargo jumpsuits broken

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7274] opened 2015-01-22 01:13 UTC
Yeah not sure whath happened yo
![borked](https://cloud.githubusercontent.com/assets/10235107/5848744/fbeb4eca-a1a9-11e4-8daa-02adfebe65c3.png)

**Comment by dannno** [comment] 2015-01-22 01:19
already reported

**Comment by PKPenguin321** [comment] 2015-01-22 01:53
Duplicate of https://github.com/tgstation/-tg-station/issues/7205

**Closed** 2015-01-22 02:05 UTC
