### ISSUE TITLE
Ling's Augmented Eyesight persists through readaption

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#9361] opened 2015-05-05 22:51 UTC
Yes it does.

**Comment by xxalpha** [comment] 2015-05-05 23:23
I have a feeling this is a duplicate.

**Comment by WJohn** [comment] 2015-05-05 23:38
Yeah, duplicate of #8602

I swear this got fixed, though?

**Comment by Dorsisdwarf** [comment] 2015-05-06 07:08
If it had been fixed, #8602 would have been closed when the fix was merged

**Closed** 2015-05-06 10:07 UTC
