### ISSUE TITLE
Centcom can be inflitrated

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#10290] opened 2015-06-30 11:04 UTC
Build an autocloner and autolathe on the cargo shuttle, autoclone yourself and voila. You are there. Nothing fancy to steal, except the centcom shuttle, sadly.

**Comment by freerealestate** [comment] 2015-06-30 11:07
Centcom being off-limits is needless anyway. Provided players can't get
into the space surrounding Centcom, it doesn't matter.

**Comment by phil235** [comment] 2015-06-30 11:13
duplicate of #7690 actually

**Closed by phil235** 2015-06-30 11:13 UTC
Labels: Bug
