### ISSUE TITLE
When placing a poster from a diagonal (?) causes it to appear on the wall above it

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/-tg-station#14670] opened 2016-01-16 19:19 UTC
![tgstation bagil english procreatory monitor five 2016-01-16 141654](https://cloud.githubusercontent.com/assets/7079721/12374003/06f428fa-bc5c-11e5-9a99-02744d22c18f.png)
The poster is supposed to be placed on the circled tile, my current position is where I tried to place it.

**Comment by WJohn** [comment] 2016-01-16 19:21
Dupe of #13430

**Closed by WJohn** 2016-01-16 19:21 UTC
