### ISSUE TITLE
Perma deaf constructs

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#6964] opened 2015-01-11 09:05 UTC
It appears that using flashbangs can render a construct permanently deaf.

As a note, I was an artificer

**Comment by Steelpoint** [comment] 2015-01-11 12:31
I think this has to do with simple mobs, for example Drones also suffer from this.

**Comment by tkdrg** [comment] 2015-01-11 18:21
Dupe of #6442

**Closed by tkdrg** 2015-01-11 18:21 UTC
