### ISSUE TITLE
Cannot become flammable on Ministation

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#12990] opened 2015-11-12 18:16 UTC
halp computer

1) Throw welding fuel/ethanol/napalm ALL OVER YOUR BODY
2) No "covered in flammable liquid" indicator on inspection
3) Applying flame to said body does not light person on fire.

**Comment by Shadowlight213** [comment] 2015-11-12 19:22
This is extremely vague, I don't understand what the bug is. Please use the issue report format found at https://tgstation13.org/wiki/Reporting_Issues

**Comment by phil235** [comment] 2015-11-12 19:31
Related to https://github.com/tgstation/-tg-station/issues/12952 ?

**Comment by Robustin** [comment] 2015-11-12 23:42
Fire code is just fucked right now, I clarified my first post but I just saw a shuttle with a mostly burnt out plasma fire completely and fully ignite on launch, but people passing through the flame were not being lit on fire (though they were dying to the heat created).

**Comment by phil235** [comment] 2015-11-13 00:10
Can't reproduce on box.

**Comment by tkdrg** [comment] 2015-11-13 00:15
yeah i broke fire some time ago
should be fixed on next update

**Comment by Aranclanos** [comment] 2015-11-17 09:02
so does this ever happened or it can happen currently or what

**Comment by KorPhaeron** [comment] 2015-12-31 23:07
@tkdrg 

Think you fixed this

**Closed** 2015-12-31 23:32 UTC
Labels: Bug
