### ISSUE TITLE
Changeling monkification

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#11855] opened 2015-09-18 09:20 UTC
When you monkey yourself while wearing things it completely deletes it and does not drop it on the floor
Also, if you have an implant that gives you an action button, it deletes that too but doesn't update your icons or whatever so you have a nonfunctional action button

**Comment by Dorsisdwarf** [comment] 2015-09-18 09:26
Dupe of #11037

**Comment by Dorsisdwarf** [comment] 2015-09-18 09:27
Actually, this one mentions an additional part of the bug.

**Comment by PKPenguin321** [comment] 2015-09-18 22:22
can we get like a medium or high priority tag on this, it's been in the game for weeks and it sucks donkey balls

**Comment by phil235** [comment] 2015-09-18 23:05
@PKPenguin321 Don't worry I'm working on a fix atm.

**Comment by PKPenguin321** [comment] 2015-09-19 02:36
ty based phil

**Closed** 2015-09-22 15:43 UTC
Labels: Bug, Priority: High, Runtime
