### ISSUE TITLE
Foam can last forever

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#9034] opened 2015-04-18 05:15 UTC
Not sure how have seen it more then once

**Comment by Iamgoofball** [comment] 2015-04-18 09:14
This is an incredibly shitty issue report.

We have no idea if it was true.
We don't know what server it was on.
We don't have a revision number.
We don't have a timestamp.
We don't have any reproduction details.
We don't have a descriptive description.

**Comment by phil235** [comment] 2015-04-18 11:10
I remember seeing a single tile who still had the foam sprite on it in a hallway recently (from a cleaner grenade I think), the tile wasn't slippery though so it may be an icon or overlay update issue.

**Comment by Miauw62** [comment] 2015-04-18 14:14
![2015-04-18 16_12_04-sybil_ slant-ways hazard lima](https://cloud.githubusercontent.com/assets/3975713/7215782/ba969760-e5e5-11e4-8b01-22246cbccae3.png)

this does happen. the tiles were still slippery, though.

**Comment by Iamgoofball** [comment] 2015-04-18 18:09
@Cheridan then

**Comment by Tokiko1** [comment] 2015-04-19 10:22
![basil east frontier gamma 2015-04-11 032342](https://cloud.githubusercontent.com/assets/7812993/7219021/a447c842-e68c-11e4-86f1-d1df296d4c63.png)
This plasma/facid foam tile kept producing infinite amounts of plasma, flooding the entire station. So these tiles certainly seems to be doing something.

I'm not sure how to reproduce it either.

This was a signaller+igniter grenade. I detonated it inside a red emergency toolbox. 
Grenade contents:
Beaker 1: 5u Plasma, 10u FAcid, 35u Fluorosurfactant
Beaker 2: 5u Plasma, 10u FAcid, 35u Water

**Comment by WJohn** [comment] 2015-05-21 21:39
Still happening today.

![](http://i.imgur.com/7VxVXja.png)

@Iamgoofball

**Comment by Iamgoofball** [comment] 2015-05-22 00:20
Still can't reproduce it. Once again @cheridan

**Comment by Aranclanos** [comment] 2015-07-08 01:26
was this fixed?

**Comment by Anonus** [comment] 2015-07-08 01:29
No.

**Comment by Aranclanos** [comment] 2015-07-08 01:39
(´・ω・｀)

**Comment by Iamgoofball** [comment] 2015-07-08 02:15
@cheridan @cheridan @cheridan

**Comment by freerealestate** [comment] 2015-07-09 21:49
Encountered this today.

**Comment by phil235** [comment] 2015-07-09 22:27
@freerealestate  what color was the foam? Did an admin check the variables of it?

**Comment by freerealestate** [comment] 2015-07-09 23:01
It was green. I've seen that green foam lingering in probably 5 or 6
different rounds in the past few months. I did adminhelp to ask an admin to
delete it, and @Ausops responded and delete a couple of the tiles. I'm not
sure if the admins checked the variables or not.

**Comment by Anonus** [comment] 2015-07-09 23:22
If it's green, it's highly likely to be space cleaner foam from the janitor's space cleaner grenades.

**Comment by phil235** [comment] 2015-07-10 00:00
I think this is due to PoolorNew() not calling the foam's New() when it uses a foam in the pool., which means the foam is never processed.

**Comment by phil235** [comment] 2016-04-28 22:19
This hasn't happened for a long time...so I'm closing.

**Closed by phil235** 2016-04-28 22:19 UTC
Labels: Bug, Cannot Reproduce
