### ISSUE TITLE
Climbing a table diagonally dumps you on the floor in front of it

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#5620] opened 2014-11-02 16:59 UTC
see title

**Comment by xxalpha** [comment] 2016-01-17 22:28
I can't reproduce this at all, none of the information here helps.

**Comment by Jalleo** [comment] 2016-01-17 22:33
X is wall T is table P is player
XT
P

I presume this is the issue due to us not allowing proper diagonal movement.

**Comment by xxalpha** [comment] 2016-01-17 22:41
I can do that climb onto the table with no problems, though.

**Comment by Dorsisdwarf** [comment] 2016-01-21 13:11
P
X T X

is the precise setup this was reproduced with originally.

**Comment by tkdrg** [comment] 2016-01-24 16:21
xxalpha says he still can't reproduce this, so closing until somebody makes it happen again

**Closed by tkdrg** 2016-01-24 16:21 UTC
Labels: Bug
