### ISSUE TITLE
I can't stop growing dicks

### ISSUE THREAD

**Issue by Yakk** [tgstation/-tg-station#7510] opened 2015-02-02 06:45 UTC
Server: Sybil

Revision: 920bca9147526b7601c9fdf237b5f3d3d40aa1e5 

Problem Description: I start the round as a female character and then as I'm walking through the station I notice a flesh colored pixel poking out of my groin area. Upon examination I am shown as an "It" and if I am ever naked while this bug is happening I have the male nude sprite rather than the female one.

What did you expect to happen: Expected to be qt stutterwhore unless !!FUN!! were to happen.

What happened instead: I grew a dick.

Why is this bad/What are the consequences: I am significantly less cute and maybe unics would be more easily recognizable amongst the more attentive crew. I dunno.

Steps to reproduce the problem: No idea. It seems to always happen when I'm playing as a security officer though.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): :mystery: Have a supplementary image though.
![dickseverywhere](https://cloud.githubusercontent.com/assets/4669135/5996722/1985a058-aa7d-11e4-9410-6cdafe0608e6.png)

**Comment by Miauw62** [comment] 2015-02-02 06:59
Ayy lmao
Op 2-feb.-2015 07:45 schreef "Yakk" <notifications@github.com>:

**Comment by Razharas** [comment] 2015-02-02 08:42
Fucking male privelege

**Comment by An0n3** [comment] 2015-02-02 08:42
I noticed the reverse problem while playing as a female medical doctor.  When unbuttoning my coat I noticed a really large slice of transparency going up my mob when facing south.

**Comment by Kraseo** [comment] 2015-02-02 13:49
>What happened instead: I grew a dick.

![2015-02-02_14-48-51](https://cloud.githubusercontent.com/assets/3855300/6001484/b277832c-aaea-11e4-8c19-c0caf377c52d.png)

**Comment by GunHog** [comment] 2015-02-02 14:29
BUG OF THE YEAR 2015 :+1:

**Comment by d3athrow** [comment] 2015-02-02 15:12
:+1:

**Comment by Incoming5643** [comment] 2015-02-02 17:55
I've seen this happen with other jobs as well, confusingly sometimes it seems to resolve itself in some cases if you strip out of your clothing, but not always. I wasn't aware it was actually changing the mob sprite though.

Now everyone isn't going to be able to ignore the dick pixels until someone fixes this though

**Comment by Incoming5643** [comment] 2015-02-02 18:10
@Yakk (or anyone really): When you had the visible dick pixel (DP), did taking off and putting your undershirt back on hide it? What I'm asking is if the uniforms "swapped" to the male version upon rewearing.

I ask because the code to use the female version of clothing includes a H.gender == FEMALE check, so if it's still showing the DP that means that the mobs are still considered female, despite having fucked up pronouns and the wrong mob icon.

Other things to check: if H.dna.species.sexes is toggled off somewhere or if something's fucked up the gender DNA block

**Comment by hugelosernapkin420** [comment] 2015-02-02 19:37
remove penis

**Comment by dannno** [comment] 2015-02-02 19:45
this is incredible

**Comment by Yakk** [comment] 2015-02-02 20:26
>When you had the visible dick pixel (DP), did taking off and putting your undershirt back on hide it? What I'm asking is if the uniforms "swapped" to the male version upon rewearing.

Taking the uniform off and putting it back on covers the dixel, yes.

**Comment by Incoming5643** [comment] 2015-02-02 21:39
For the record, the women, and only the women, are becoming gender "Plural"

**Comment by WJohn** [comment] 2015-02-02 23:59
Likely related to #4833

**Comment by bgobandit** [comment] 2015-02-03 00:53
did you miss your annual johnson inspection

**Comment by An0n3** [comment] 2015-02-03 03:59
Learn my pronouns.

**Comment by Stickymayhem** [comment] 2015-02-03 04:31
Just roleplay harder

**Comment by TZK13** [comment] 2015-02-03 17:56
Or roleplay hard ;^)

**Comment by Yakk** [comment] 2015-02-04 01:04
Happened again. You can't select a beard style as an It and if you get gender change surgery it makes you back into a woman.

**Comment by Incoming5643** [comment] 2015-02-04 01:15
yeah I've seen the dixel reappear mere moments after gender surgery, and I've see it not come back after a full hour as well. This shit is so weird.

**Comment by Yakk** [comment] 2015-02-04 01:22
"The Wild Dixel" by Yakk

I want to take the dixel off
But I can't
I use medbay and when I use medbay I never go back to my original gender
It's my curse
My eternal curse
I WANT TO TAKE THE DIXEL OFF BUT I CAN'T
IT'S MY CURSE
IT'S MY FUCKING CURSE
I WANT TO TAKE THE DIXEL OFF
PLEEEEEEEEASE
TAKE IT OFF
PLEEEEEEEEEEEEAAAAAAAAASEEEE

**Comment by dannno** [comment] 2015-02-04 01:39
this is the bug of the century

**Comment by paprka** [comment] 2015-02-04 02:56
This has been happening on a lot of cases, more than it ever did before. Mostly on security and medbay from what I've seen. Someone really needs to delve into these pronoun procs and help them check their privilege.

**Comment by Miauw62** [comment] 2015-02-04 11:45
I Have No Dixel And I Must ERP.
Op 4-feb.-2015 03:56 schreef "paprka" <notifications@github.com>:

**Comment by Kraseo** [comment] 2015-02-07 16:58
IT'S THE RETURN OF THAT ONE OBSCURE BUG AGAIN AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by hornygranny** [comment] 2015-02-19 23:31
Thanks to Skyglazer's report and Menshin's investigation, we've discovered that this is caused by luminosity higher than 7, as it's stored in 3 bits. Gender is the next variable in memory, so it overflows there as there's no sanity.

**Comment by dannno** [comment] 2015-02-19 23:34
;-;7 god bless these united states of america

**Comment by RemieRichards** [comment] 2015-02-19 23:36
it's simple, we kill the luminosity.

**Comment by Incoming5643** [comment] 2015-02-19 23:46
breaking news as stuttering nurses retreat to darkened maintenance halls in search of purity

**Comment by Miauw62** [comment] 2015-02-20 18:21
( ͡° ͜ʖ ͡°)

**Comment by dannno** [comment] 2015-02-20 18:33
DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES DICKGIRL VAMPIRES

**Comment by RemieRichards** [comment] 2015-02-20 18:34
@dannno gmail wants to translate that from Sudanese...

**Comment by Yakk** [comment] 2015-02-21 23:15
I do always carry flashlights on me so I can see in maint and stuff. Seems legit.

**Comment by SkowronX** [comment] 2015-03-12 04:09
Die cis scum

**Comment by MrPerson** [comment] 2015-03-13 16:52
Supposedly fixed in the current byond version.

@Yakk "dixel" made Tom laugh, pat yourself on the back. Ideally with your dick.

**Comment by Incoming5643** [comment] 2015-04-12 16:47
sidestep fixed by #8581 apparently

**Closed** 2015-04-13 19:12 UTC
Labels: Bug, BYOND Issue, FUCK

**Comment by interestingusernam3** [comment] 2021-07-07 00:26
Penis

**Comment by d3athrow** [comment] 2021-07-07 00:27
based
