### ISSUE TITLE
Spacewind doesn't work for negative pressure differences

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/-tg-station#14703] opened 2016-01-17 21:25 UTC
Your waifu is shit.
Whenever air is shared between two tiles and the tile in question pulls air instead of pushing air, spacewind is not applied.
All of this happens in code/LINDA/LINDA_turf_tile.dm
share_air() calls T.consider_pressure_difference(src, difference) on negative difference when it should be calling T.consider_pressure_difference(src, -difference) as consider_pressure_difference() expects a positive pressure difference.
The result is spacewind only being applied very sparsely when an area decompresses.

**Comment by Jalleo** [comment] 2016-01-17 22:27
@duncathan @as334

**Comment by WJohn** [comment] 2016-01-17 22:56
Dupe of #14700 but this seems to be more accurate so I'll close that one instead.

**Comment by DaedalusGame** [comment] 2016-01-17 22:59
Not a dupe. If you had two eyes and the cognitive ability to read, you'd see that he said the O2 level remained the same over a long time. This merely concerns movement due to pressure differences.

**Comment by xxalpha** [comment] 2016-01-18 00:02
Calm down, partner.

**Comment by DaedalusGame** [comment] 2016-01-18 16:55
Another one in process_cell for adjacent unsimulated turfs. Maybe just make consider_pressure_difference do the sanitization.

**Closed** 2016-01-19 04:13 UTC
Labels: Atmos, Bug
