### ISSUE TITLE
Sentience potion mob invisible

### ISSUE THREAD

**Issue by ThatSlyFox** [tgstation/-tg-station#8669] opened 2015-03-31 23:19 UTC
When using a sentience potion on a mob it has a chance to turn it into the "animal", a invisible mob.

**Comment by WJohn** [comment] 2015-03-31 23:49
Dupe of #8667 come on man literally right next to you.

**Comment by phil235** [comment] 2015-04-01 00:03
You sure it's a duplicate? Sentience potions and slime cores aren't the same thing.

**Comment by ThatSlyFox** [comment] 2015-04-01 00:13
I am most likely mistaken. This can be deleted.

**Closed** 2015-04-10 19:44 UTC
