### ISSUE TITLE
No black overlay during crit, sometimes

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8445] opened 2015-03-20 18:32 UTC
Shocked myself to crit on a door -> No black overlay obfuscating my sight
![unbenannt](https://cloud.githubusercontent.com/assets/11201491/6758453/8ebc86d6-cf38-11e4-8d08-9a6300ab9562.PNG)

Getting dragged to medbay a bit later and defibrilated -> Black overlay again

**Comment by francinum** [comment] 2015-03-20 19:15
dupe of #8386. Already fixed by #8394, Server likely out of date.

**Closed** 2015-03-21 00:09 UTC
