### ISSUE TITLE
Toxins chamber is completely fucked!

### ISSUE THREAD

**Issue by SkipsPro** [tgstation/-tg-station#10060] opened 2015-06-20 22:20 UTC
Problem Description:

You cant heat anything in the toxins lab, it only reaches like 4499 kpa and like 630 K.

What did you expect to happen: 

The chamber would get the mixture to heat to 97000 kpa and some ridiculous temp so you could put it on a bomb.

What happened instead:
 
I set the pumps to max, put my 33% o2 and 66% plasma tank on the intake, pumped it in, and ignited. It burned for a little while then stopped. It was only 4499 kpa and like 630 K. I tried putting in more of the mix, but it just stayed at 4499 kpa and around 630 K.

Why is this bad/What are the consequences:

 toxins is completely useless, you can't make bombs, the mixture cannot reach the sufficient temperature and pressure needed.

Steps to reproduce the problem: 

1) mix 2 plasma and 1 o2 canister. 
2)wrench one of the canisters that has 66% plasma and 33% o2 into the intake, set both pumps to max
3) pump the mixture into the burn chamber
4)ignite the mixture
5)mixture catches fire for like 20 seconds and dies out, the temp and pressure are way too low to make a bomb with.

Server: Which server were you playing on? 

Server 2

Revision: What revision was the server running? 
Server revision compiled on: 2015-06-20
f1239081160115e770d91022ee67fb518785d49e 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): please fix this, it's been like this for a while, and it seems like almost no one has noticed, except for like razharas, and he told me it was just bad luck and that it's just a flaw inherent with the atmos system, however that cant be true because it has happened every time I've tried doing toxins.

**Comment by Niknakflak** [comment] 2015-06-20 23:03
I have had this happen to me and also not happen to me.  This seems to only happen, some of the time.

**Comment by phil235** [comment] 2015-06-20 23:41
Duplicate of #9711 I think. It seems the issue is that the burn mix can't go past 4500kPa.

**Comment by Marflowerose** [comment] 2015-06-21 08:34
This may happen normally if you have pump from chamber set to max before the gas in chamber is ignited, causing the pipe to get full of unburned mix, which naturally wouldn't increase in pressure or temperature as it isn't burning. If the pipe is full and then the chamber is ignited, the gas inside the pipe will not ignite seeing as it's already "full". Although it's possible this is part of fastmos mystique with gases we've been seeing lately.

**Comment by WJohn** [comment] 2015-06-21 10:30
Yeah, this is a dupe.

**Closed by WJohn** 2015-06-21 10:30 UTC

**Comment by Dorsisdwarf** [comment] 2015-06-22 13:58
Oh, and you don't need 90,000 *C for a bomb. 700 degrees is plenty for a detonation
