### ISSUE TITLE
Radiation pulses clutter up admin logs without any useful information

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12613] opened 2015-10-23 19:24 UTC
Gives no hint as to the source (and which player may have caused it), no chat links, etc.

Would be nice if it either

A) Warned admins what was causing the radiation

or

B) Didn't appear in asay at all

**Comment by WJohn** [comment] 2015-10-23 19:42
Literally two issues down from here, man, come on. Dupe of #12609

**Closed by WJohn** 2015-10-23 19:42 UTC
