### ISSUE TITLE
Bio Bags: Rapid Pick up

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#13127] opened 2015-11-20 01:02 UTC
The rapid pick up feature does not work on the following items for the bio-hazard bags:

- Slime Extract
- Syringes
- blood bags

**Comment by Anonus** [comment] 2015-11-20 01:06
What do all of these have in common gee I wonder.
They're all reagent containers.

**Comment by Fox-McCloud** [comment] 2015-11-20 01:07
Actually, slime extracts aren't reagent containers, per se.

**Comment by tkdrg** [comment] 2015-11-20 03:04
dupe of #13116 etc

**Closed** 2015-11-20 11:52 UTC
