### ISSUE TITLE
Mech ballistics do not fire properly.

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#7766] opened 2015-02-16 16:16 UTC
While testing a mech shotgun (Scattershot) and LMG (Ultra) with a Durand the following issue has been discovered:

Projectiles are spawned on the mech's square and do not move. They can be picked up, and throwing them does deal damage.

**Comment by SconesC** [comment] 2015-02-16 17:13
this has been around for ages, not sure if it's mech-specific or just gun-specific but shit still happens on Gygax/Phazon

**Comment by Dorsisdwarf** [comment] 2015-02-16 17:19
Due to budget cuts, the gunpowder in NT standard bullets has been removed, requiring employees to use combat mechs as throwing weapon dispensers.

**Comment by phil235** [comment] 2015-02-16 18:09
Pretty sure this is a duplicate.

**Comment by WJohn** [comment] 2015-02-16 23:17
4th time dupe of #6179. Might be the most times we've seen an issue duped, actually.

**Closed** 2015-02-16 23:27 UTC
