### ISSUE TITLE
X-ray vision mutation is lost shortly after gaining.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#8250] opened 2015-03-09 06:44 UTC
Get x-ray vision.
AW YES I CAN SEE THROUGH WA-
![xrayisdead](https://cloud.githubusercontent.com/assets/6583225/6551560/a01ffdee-c5f7-11e4-80c0-cae140425608.gif)

Aww, now it's gone.

**Comment by Razharas** [comment] 2015-03-09 09:50
Someone refactored life again

**Comment by phil235** [comment] 2015-03-09 10:32
duplicate of #8196 but this one has an explanatory image so we'll keep this one.

**Comment by Chocobro** [comment] 2015-03-09 16:47
you could at least grab that body
jeez

**Comment by RandomMarine** [comment] 2015-03-09 18:47
Nah don't worry the other geneticist is on it.

**Comment by Razharas** [comment] 2015-03-09 19:45
Is this troll image?
Theres geneticist ling absorbing engineer in genetics maint, mime with flash and esword killing secborg in robotics and sec officer with baton near the downed clown below genetics, all of this appear for a few moments and then vanish in the darkness again
5/5 must be staged

**Comment by RandomMarine** [comment] 2015-03-09 19:50
Missed the syndibomb/10

**Comment by Miauw62** [comment] 2015-03-09 19:51
lol

**Closed** 2015-03-14 03:56 UTC
Labels: Bug, Mob
