### ISSUE TITLE
AI holograms are affected by lack of gravity

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#11858] opened 2015-09-18 18:13 UTC
Repro:
- Turn off gravity
- Activate a holopad in a gravity-less area
- Move around
- Float due to lack of gravity, as if you weren't a projection

**Comment by WJohn** [comment] 2015-09-18 18:49
Dupe of #6109.

**Closed by WJohn** 2015-09-18 18:49 UTC
