### ISSUE TITLE
Juice cartons break like bottles when thrown

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11097] opened 2015-08-08 06:32 UTC
Exactly what the title says. Take a carton and throw it and it will break. Broken cartons can be used to violently slash people doing no damage at all.

**Comment by phil235** [comment] 2015-08-08 08:34
That's because the juice cartons are /obj/item/weapon/reagent_containers/food/drinks/bottle just like vodka bottles, lol.

**Comment by Miauw62** [comment] 2015-08-08 13:11
f e a t u r e

**Comment by Core0verload** [comment] 2015-08-08 22:58
@phil235, not a bug, intended behaivour according to code. Close it.

**Comment by Jalleo** [comment] 2015-08-08 23:29
No this is a bug reopen it.
Cartons arent glass.

**Comment by phil235** [comment] 2015-08-08 23:32
I doubt whoever coded juice carton intended for them to be broken and used as sharp weapon.

**Comment by Core0verload** [comment] 2015-08-09 07:28
if(isGlass)
		if(prob(33))
			new/obj/item/weapon/shard(new_location)
		playsound(src, "shatter", 70, 1)
	else
		B.name = "broken carton"
		B.force = 0
		B.throwforce = 0
		B.desc = "A carton with the bottom half burst open. Might give you a papercut."

**Comment by phil235** [comment] 2015-08-09 09:47
You're right, it appears to be intended, but it's not exactly realistic, plus the code is ugly.

**Comment by Ergovisavi** [comment] 2015-08-14 16:01
This was intended. Mostly because it's silly, but also to ensure that you can't reuse them for molotovs. They're completely ineffective as weapons.

**Comment by phil235** [comment] 2015-08-14 16:03
@Ergovisavi  I think the bigger problem is the fact that you could make molotovs with juice cartons.

**Comment by Ergovisavi** [comment] 2015-08-14 16:04
@phil235 
Crafting is goofy and can't distinguish children and parents, also, making molotovs with juice cartons is an option, but an incredibly stupid one. You can do it, but you have a very short time to throw it before it just splashes its reagents all over whoever is holding it.

**Comment by Dorsisdwarf** [comment] 2015-09-14 12:17
Issue closed for XXINTENDED FEATUREXX

**Closed by Dorsisdwarf** 2015-09-14 12:17 UTC
Labels: Consistency Issue, Not a bug
