### ISSUE TITLE
Dreamstation: All camera consoles list zero cameras.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12467] opened 2015-10-18 00:14 UTC
![](http://puu.sh/kO2ef/cbc73b8b06.png)

**Comment by Shapsy** [comment] 2015-10-18 04:27
All maps do this, sorta critical

**Comment by Xhuis** [comment] 2015-10-18 04:31
\>this managed to happen

sign me the FUCK up good shit go౦ԁ sHit thats ✔ some goodshit rightth ere right✔there ✔✔if i do ƽaү so my selｆ :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: Н

**Comment by Jordie0608** [comment] 2015-10-18 06:30
Dupe of #12435

**Closed by Jordie0608** 2015-10-18 06:30 UTC
