### ISSUE TITLE
spraypaint is INSANE

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#8934] opened 2015-04-13 04:01 UTC
Last I checked, you can still stunlock someone from a screen away behind windows and tables, with a can of spray paint. 
Also, someone said in radio it works on borgs..?

**Comment by Jordie0608** [comment] 2015-04-13 05:38
This should've been fixed by #8887, are you sure the server was updated?

**Comment by Jordie0608** [comment] 2015-04-13 11:25
Just tried, unable to reproduce. This was fixed.

**Closed by Jordie0608** 2015-04-13 11:25 UTC
Labels: Bug
