### ISSUE TITLE
Defib fails to revive healed corpses.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8617] opened 2015-03-29 18:03 UTC
When someone has taken 180~ burn/brute, you are supposed to be unable to revive them using defib unless you heal their body using styptic/silver/synthflesh.

The issue:
Even after healing the body below 180~ damage, defib fails to revive them. The message changes from
>The defibrillator buzzes: Resuscitation failed - Severe tissue damage detected.

to

>The defibrillator buzzes: Resuscitation failed.

and nuffin happens.

I am sure the other person was inside their body, as it was my second key, and the body was fresh enough to defib.

Steps to reproduce:
-Beat someone to 180~ brute/burn.
-Use patches on them and heal their body to 0 damage.
-Defib them
-Fail terribly.

**Comment by Xhuis** [comment] 2015-03-29 18:54
The resuscitation failure message is displayed when the person in question is not in their body. Generally this means they're either braindead or don't want to be revived.

**Comment by SeikoTheSeal** [comment] 2015-03-29 19:53
Thing is, the other person was not braindead, was in the body, and really wanted to be revived, and i am 100% sure of it, as it was me using second ckey, on my own server.

**Comment by Xhuis** [comment] 2015-03-29 19:53
Oh. Duh. Guess it is an issue, then.

**Comment by phil235** [comment] 2015-03-29 20:45
It looks like this has been like this for a long time. The defib's checks include:
`H.health <= config.health_threshold_dead && total_burn <= 180 && total_brute <= 180`
So the problem is that if you have too much burn or brute damage you can't be resuscitated, and if your body is healed and your health gets above -100 then you can't be resuscitated either!

**Comment by stapler2025** [comment] 2015-03-29 20:52
>The underlying issue is that you can heal corpses with styptic patches I think.

Not a bug, let people use patches to defib people, quit taking away our fun.

Battle doctors are fun to play.

**Comment by SeikoTheSeal** [comment] 2015-03-29 21:03
^ I concur.

**Comment by Iamgoofball** [comment] 2015-03-30 02:32
@phil235 styptic patches healing brute on dead bodies is intentional

**Comment by phil235** [comment] 2015-04-06 17:59
All I'm saying is no other reagent or medicine has ever been intended to work on corpses, thus styptic patches breaks the defibrilator's balance.

**Comment by Iamgoofball** [comment] 2015-04-06 18:26
I can make chems metabolize inside corpses.

**Comment by phil235** [comment] 2015-04-11 13:33
Fixed by #8802

**Closed by phil235** 2015-04-11 13:33 UTC
Labels: Bug
