### ISSUE TITLE
Guy was able to rejoin the round after being gibbed from a bomb

### ISSUE THREAD

**Issue by elyina** [tgstation/-tg-station#5170] opened 2014-10-10 13:20 UTC
HELP: Allen Westry/(Allen Westry) (?) (PP) (VV) (SM) (JMP) (CA) : Hey admins, I got booted from my body and into the start screen. Am I allowed to rejoin? 
Admin PM to-Allen Westry/(Allen Westry): how did that happen?
Reply PM from-Allen Westry/(Allen Westry): I got bombed, the connection got closed and now I'm back at new player options after reopening the game.
Admin PM to-Allen Westry/(Allen Westry): Are you sure it hasn't been a new round since then?
Reply PM from-Allen Westry/(Allen Westry): Nope, just happened. I was the geneticist.
Reply PM from-Allen Westry/(Allen Westry): Telescience teleported a bomb over to genetics.

I checked the logs at the time of this, everything he said was true.  His character existed and was in the round, got bombed, he got disconnected and was able to rejoin as a new character under the same name, in the same round.  I was not able to reproduce this by bombing myself, so I'm not sure on the exact details, but this seems bad.

**Comment by Shadowlight213** [comment] 2015-09-21 20:54
Pretty sure this happens when the mob containing the player's ckey and client is destroyed before an observer can be created for them.
Easy way to reproduce is to edit a mob's ckey from one player to another. The previous player will be booted from the game and rejoin as a new player.

**Comment by Fox-McCloud** [comment] 2015-10-10 09:44
I'm going to guess this has been resolved as this was before Destroy() would return ..()

all mob/living things are no hard deleted, so I doubt this is even possible anymore.

**Comment by MrStonedOne** [comment] 2015-12-23 12:25
lets just close this until it happens again, it's been a while since i've seen an admin relating to this.

**Closed** 2015-12-23 17:36 UTC
Labels: Bug, Needs Reproducing/Testing, qdel() problem
