### ISSUE TITLE
Issue with new genetic voice changing powers

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#7262] opened 2015-01-21 20:01 UTC
![image](https://cloud.githubusercontent.com/assets/6778786/5843963/6c7a1c92-a17e-11e4-83b2-62dbf0d8444f.png)

**Comment by drynwyn** [comment] 2015-01-21 20:08
Duplicate of #7259 
I beat you to it.

**Closed** 2015-01-21 20:09 UTC
