### ISSUE TITLE
All sounds being cut midway very often

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#10077] opened 2015-06-21 15:40 UTC
It wasnt like this before, something changed
f1239081160115e770d91022ee67fb518785d49e this is the last server update

**Comment by Ikarrus** [comment] 2015-06-21 17:06
If it helps I sometimes find that some sounds would cancel out all others, such as violins. 

Perhaps it has something to do with the way the sounds are being played.

**Comment by RemieRichards** [comment] 2015-06-21 19:02
It's a Byond issue.
It didn't happen in versions prior to 507, it no longer occurs in the latest 508 betas.

**Comment by WJohn** [comment] 2015-06-21 22:40
Also this is a dupe of #9042

It's been around for months.

**Comment by RemieRichards** [comment] 2015-06-22 02:00
Closed the other one, this one is more informative since I've explained what it is.

**Comment by SconesC** [comment] 2015-07-11 05:35
I think I found the culprit of the sound bug

Steps to reproduce (Have tried multiple times)
1) go to brig armory
2) equip riot helmet
3) use action button to flip visor of riot helmet up
4) all sounds are broken for you and anyone around you
5) flip visor back down, sounds are fine

>while(up)
playsound(src.loc, "[activation_sound]", 100, 0, 4)
sleep(15)

https://github.com/tgstation/-tg-station/blob/256f0adeb672edeace2aff90ae4e8f1ce02d8cbe/code/modules/clothing/head/helmet.dm#L70

**Comment by phil235** [comment] 2015-07-11 08:57
And it's due o the addition of the stupid justice helmet, I'm not surprised.

**Comment by Iamgoofball** [comment] 2015-07-11 19:53
WEEWOOWEEWOO

**Closed** 2015-07-17 23:03 UTC
Labels: BYOND Issue, Sound
