### ISSUE TITLE
Lings can't use stings in space

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7560] opened 2015-02-05 02:20 UTC
Problem Description: Lings cannot use stings while in space.

What did you expect to happen: I expected to sting someone in space

What happened instead: No matter how much I alt clicked, the sting did not work until we re-entered the station

Why is this bad/What are the consequences: I want to sting people in space but I can't which doesn't really make a lot of sense

Steps to reproduce the problem: 
-be ling
-go into space with fellow human (both have CR)
-try to transform sting after yelling "DIE"
-awkwardly play it off as a joke after nothing happens 

Server: Badger

Revision: b1a3cde873bc26a33f009130d4cc5dfbae9420c1 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): The two people I tried it on both had a couple of superpowers each (both had CR) and a basic supervirus.

**Comment by Xhuis** [comment] 2015-02-06 12:26
This might be due to targeting - I think it aims for the turf the target is on. I'm not sure how this could be remedied.

**Comment by Incoming5643** [comment] 2015-02-06 17:38
I don't think this was always the case, I remember fun times cryostinging space travelers and watching them freeze to death thanks to the insulating effects of their suits.

**Comment by GunHog** [comment] 2015-02-06 22:42
Ling stings use Astar for connecting to targets, yes? Altering the parameters of the proc to include space tiles would fix it, if that is true.

**Comment by Razharas** [comment] 2015-02-06 23:58
I never managed to make astar work nicely in ling stings, it is going crazy from time to time

**Comment by Dorsisdwarf** [comment] 2015-03-02 10:58
Is this reproducable?

I've not seen anyone else mention it.

**Comment by dannno** [comment] 2015-03-02 16:41
make a dummy in space and try to sting it

**Comment by Shadowlight213** [comment] 2015-10-10 00:09
This was fixed needs closing

**Closed** 2015-10-10 08:55 UTC
Labels: Bug
