### ISSUE TITLE
SecHuD's are not showing some jobs

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#10607] opened 2015-07-14 01:13 UTC
Saw the detective, he had his ID on, however it didnt appear on the secHuD glasses, leaving an empty loyalty sprite box

![](http://puu.sh/iYdO7/68c642f0a7.png)

**Comment by tedward1337** [comment] 2015-07-15 01:36
Found out why
ID's that arent registered names get this grey box

![](http://puu.sh/iZxZM/5c55f78649.png)
Heres an updated one

**Comment by tedward1337** [comment] 2015-07-15 01:36
Registered jobs*

**Comment by Shadowlight213** [comment] 2015-07-15 21:13
Grey boxes for custom jobs on the sechud is intended.  Not a bug.

**Comment by xxalpha** [comment] 2015-07-18 07:35
@phil235 you could have closed this, it's not even an issue. It's intended behavior.

**Closed** 2015-07-18 09:46 UTC
Labels: Not a bug
