### ISSUE TITLE
Borked recorder playback.

### ISSUE THREAD

**Issue by BlittzOff** [tgstation/-tg-station#10296] opened 2015-06-30 15:16 UTC
Audio recorder displaying THIS.

![](http://puu.sh/iIjae/347772c6cb.png)

**Comment by PKPenguin321** [comment] 2015-06-30 15:22
pretty sure this is a dupe of https://github.com/tgstation/-tg-station/issues/10169

**Comment by phil235** [comment] 2015-06-30 16:26
yep, dupe.

**Closed by phil235** 2015-06-30 16:26 UTC
