### ISSUE TITLE
Can't switch camera networks as AI

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15004] opened 2016-01-28 10:24 UTC
Using Jump To Network results in a message in your chatbox, and nothing else

Switched to /list camera network.

**Comment by CPTANT** [comment] 2016-01-28 11:34
it seems all camera networks are once again broken, you can't select any camera's on security cam consoles either.

**Comment by Dorsisdwarf** [comment] 2016-01-28 13:12
Dupe of #14985

**Closed by Dorsisdwarf** 2016-01-28 13:12 UTC
