### ISSUE TITLE
Mining with pick in off-hand?

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/-tg-station#14049] opened 2015-12-25 21:33 UTC
Don't know when it changed, or if it's even intentional, but it seems like the way that mining is done has been fundamentally changed within the past couple of days.

Normal behavior: Mining with a pick in your offhand means you can just push up against a direction and start automatically mining, rather than having to click the asteroid to mine

Current behavior: Mining with a pick in your offhand will show the progress bar for about a half second and then abort out with no message.

**Comment by AnturK** [comment] 2015-12-25 22:09
@MrStonedOne changed something about do_mob/after recently iirc

**Comment by phil235** [comment] 2015-12-26 13:34
Yeah, it's a bug. MSO's changes to do_after make last_move null and then check if it's still null. The problem is that bump-mining happens during Move(), and inside Move(), last_move is set to 0 (https://github.com/tgstation/-tg-station/blob/02fe4ec5a8635c2d5a6a27f558901d46a2eb8876/code/game/atoms_movable.dm#L51). Do_after runs and see last_move != null and cancels the action.
See https://github.com/tgstation/-tg-station/pull/13959/files#diff-2aec593799a15c879d8f95f7276b689aR691

This can probably be fixed by changing do_after to set last_move to 0 and check for last_move != 0.

**Comment by MrStonedOne** [comment] 2015-12-26 14:27
What we need is to change the last_move var to be the deciseconds of their last ***successful*** move, and move last_move to last_move_dir

**Comment by octareenroon91** [comment] 2015-12-26 23:16
>MSO's changes to do_after make last_move null and then check if it's still null.
So, what?
change 
```
(user.last_move != null)
```
to
```
(!user.last_move)
```
in
https://github.com/tgstation/-tg-station/blob/master/code/__HELPERS/unsorted.dm#L749
?

**Comment by MrStonedOne** [comment] 2015-12-27 02:19
I'm removing the need for that by forcing do_after to have a 1ds resolution rather then delay/5 resolution.

This will be fixed by the time i go to bed, mark my words.

**Closed** 2015-12-28 17:35 UTC
Labels: Bug
