### ISSUE TITLE
Crusher loves/hates windows and grilles

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10551] opened 2015-07-11 16:32 UTC
1. Move crusher from disposals
2. Place crusher so left side has a window and grille then wrench
3. Bump the crusher
4. Window and grille moves to the crusher tile even though they are anchored and arent meant to go into a crusher.
5. Break window and grille to be able to move the crusher

Why is this bad?
Using two crusher in a row can be used to make a quick entrance without needing to break anything.

**Comment by Iamgoofball** [comment] 2015-07-11 19:09
H u h

**Comment by xxalpha** [comment] 2015-07-11 20:00
The real bug is the crusher remaining operable while unanchored.

**Comment by Jalleo** [comment] 2015-07-11 21:04
I believe it was anchored but i cant confirm gonna test it sometime next week.

**Comment by Dorsisdwarf** [comment] 2015-07-15 17:51
[bug]

**Comment by phil235** [comment] 2015-07-15 18:21
duplicate of #10507 
THe real issue is the crusher being active while unanchored

**Closed by phil235** 2015-07-15 18:21 UTC
Labels: Bug
