### ISSUE TITLE
Character appearances don't apply on roundstart

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8383] opened 2015-03-16 22:59 UTC
Everyone spawns as the same albino bald guy, names are ok as is hair color if you grow some later but most of the settings just don't work period even if you set and save them again.

Reassigning gender helps restore a lot of the missing settings (just updating icon in general probably is enough) they are still THERE, they just aren't expressed on round start

**Comment by Incoming5643** [comment] 2015-03-16 23:00
!!Test your shit!!

**Comment by Man-Shroom** [comment] 2015-03-16 23:27
apperences

**Comment by Incoming5643** [comment] 2015-03-16 23:33
Spell how you feel, not how you know!

**Comment by RemieRichards** [comment] 2015-03-16 23:50
Calling update_icons() does indeed solve it, as I've been doing this on every human via SQDL2 for about 2 days.

**Comment by Incoming5643** [comment] 2015-03-17 00:03
savefiles as a whole seem not to apply, Every bit of the ghost sight/ears/PDA whatever only works if you set it from preferences after roundstart.

Antag at least, is ok.

**Comment by optimumtact** [comment] 2015-03-17 00:41
@Miauw62 any thoughts?

**Comment by optimumtact** [comment] 2015-03-17 00:45
was this fixed by #8377

**Comment by Incoming5643** [comment] 2015-03-17 01:08
No it's not, sybil is 100% up to date with master right now

**Comment by RemieRichards** [comment] 2015-03-17 01:09
are you sure? that wasn't merged very long ago.

**Comment by Boredone** [comment] 2015-03-17 01:14
Yeah, just double checked myself. Sybil is updated to #8379

**Comment by Incoming5643** [comment] 2015-03-17 01:15
Revert it all and try again from scratch? :ghost:

**Comment by optimumtact** [comment] 2015-03-17 01:29
https://github.com/tgstation/-tg-station/commit/2830325e4e19dd0c186634044d12acf87f2c71eb something here?

**Comment by Incoming5643** [comment] 2015-03-17 17:06
I hope someone gets on this soon, it's kind of a hilariously critical bug.

**Comment by Miauw62** [comment] 2015-03-17 18:13
i dont even know what causes this.
the fucked preferences i can understand, but i didnt touch appearances at all.

**Comment by RemieRichards** [comment] 2015-03-17 18:20
Well since a simple icon update (update_icon() or regenerate_icons()) solves it, the preference files themselves must be fine, since the character information has to be there for the icon procs to use.

**Comment by Incoming5643** [comment] 2015-03-17 18:22
The saves are intact, they just aren't being read at roundstart.
Except for the misc preferences (not antags), which seem to be defaulting every round and have to be manually set afterwards every time.

**Comment by RemieRichards** [comment] 2015-03-17 18:23
Well I can tell you wherever character age is saved (I assume with the appearance data) that IS loaded at round start, since when I spawned without my hair and such the first time I checked my variables and my character age and stuff were correct.

**Comment by AnturK** [comment] 2015-03-17 19:18
My guess : #8334 removed deffered update_icons which defaults to on aka removed roundstart update icon.

**Comment by optimumtact** [comment] 2015-03-17 20:04
I'd say that is the root cause, good catch

**Comment by optimumtact** [comment] 2015-03-17 20:04
@MrPerson

**Closed** 2015-03-20 04:36 UTC
