### ISSUE TITLE
Humanized monkeys have null blood type in their DNA

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11770] opened 2015-09-13 21:20 UTC
Been looking through genetics issues and noticed this

**Comment by Razharas** [comment] 2015-09-13 21:28
DNA is magic

**Comment by phil235** [comment] 2015-09-13 22:41
duplicate of #7803

**Closed by phil235** 2015-09-13 22:41 UTC
Labels: Bug

**Comment by Shadowlight213** [comment] 2015-09-14 07:42
Jesus. from February and still not fixed?
