### ISSUE TITLE
Time stop stuns forever

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#17146] opened 2016-04-26 20:33 UTC
Be atmos tech
Attack wizard with a punch
He timestops
Get stunned by timestop
Timestop ends
Still stunned
Rest
Get up to clear stun

**Comment by Iamgoofball** [comment] 2016-04-26 21:11
>Rest
>Get up to clear stun

this shouldnt work

**Comment by Iamgoofball** [comment] 2016-04-26 21:11
this also shouldnt be a permastun wtf

**Comment by phil235** [comment] 2016-04-26 21:19
duplicate of #15978

**Closed by phil235** 2016-04-26 21:19 UTC
