### ISSUE TITLE
AI medical overlay does not work

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7707] opened 2015-02-13 19:20 UTC
Yeah the medical HUD for the AI doesn't seem to work. Frowny face.

**Comment by Chocobro** [comment] 2015-02-13 19:36
for posterity, the borg one works fine.

**Comment by GunHog** [comment] 2015-02-13 20:10
The Medical HUD is functioning properly. In order to get it merged, I was required to have the AI's HUD to only show medical data of people with vitals enabled on their suit sensors. As such, this is not a bug, *unless* you are talking about people you have confirmed to have full suit sensors.

**Comment by phil235** [comment] 2015-04-19 13:45
So is this confirmed a bug or did the AI simply got unlucky and only saw people without suit sensors?

**Comment by GunHog** [comment] 2015-04-19 16:26
I usually default to the Medical HUD when I am playing AI, and keeping this bug in mind, I cross-referenced against the suit sensor console, as well as bugged the people I tracked to turn on their suit sensors. This feature is functioning properly. I would *prefer* not to depend on suit sensor settings to get someone's health, but this is the way it has to be.

For any other AI experiencing a problem, check the person you are tracking against his suit sensor settings. If you cannot see his health on sensors, you will not see anything on your MedicalHUD.

**Comment by phil235** [comment] 2015-04-19 17:31
Closing then

**Closed by phil235** 2015-04-19 17:31 UTC
Labels: Not a bug
