### ISSUE TITLE
The roundstart emergency shuttle has no air

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#17582] opened 2016-05-11 22:10 UTC
The default one, looks like, from roundstart. There is a strip of space turfs by the entry airlocks. Probably related to @coiax's shuttle changes EDIT: maybe not.

Fix: Delete the shuttle and re-import emergency shuttle (box)

**Comment by PKPenguin321** [comment] 2016-05-11 22:32
most recent shuttle changes i can find: https://github.com/tgstation/-tg-station/pull/17555 @coiax 
https://github.com/tgstation/-tg-station/pull/17518 @ChangelingRain 
high priority

**Comment by xxalpha** [comment] 2016-05-12 08:37
>Also apparently pieces fall off it

Working as intended?

**Comment by coiax** [comment] 2016-05-12 08:59
Wasn't me, my changes don't touch the default shuttle at all.

**Comment by coiax** [comment] 2016-05-13 10:43
Fixed by #17607 and #17614

**Closed** 2016-05-13 11:45 UTC
Labels: Bug, Priority: High
