### ISSUE TITLE
Mining Artifact Rooms can intersect with things they shouldn't

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12960] opened 2015-11-11 07:29 UTC
![inter](https://cloud.githubusercontent.com/assets/13275673/11086150/e148620c-8802-11e5-9a82-63c8923adf92.png)

**Comment by tkdrg** [comment] 2015-11-11 15:17
Duplicate of #6297

**Closed** 2015-11-11 15:19 UTC
Labels: Bug, Map Issue
