### ISSUE TITLE
Lighting oddities 

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#8986] opened 2015-04-15 12:15 UTC
![sybil aegis lab six 2015-04-15 051137](https://cloud.githubusercontent.com/assets/7069733/7158374/459cc3d0-e32e-11e4-8dcd-33d77cac7828.png)

Not sure what happened here. but the odd change from full on light to no light was just odd.

oddly enough, the air chambers all had the right amount of light from space/starlight.

@MrPerson

**Comment by WJohn** [comment] 2015-04-15 14:13
Seems to be a dupe of #8939.

**Comment by WJohn** [comment] 2015-08-09 10:37
This is also starlight, and starlight has been closed.

**Closed by WJohn** 2015-08-09 10:37 UTC
Labels: Bug
