### ISSUE TITLE
Typing while a confirmation prompt comes up will give a yes result.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#12229] opened 2015-10-08 01:12 UTC
This is very aggravating when you're trying to talk in dead chat and you're suddenly given control a of something you had no intention of agreeing too.

**Comment by PKPenguin321** [comment] 2015-10-08 03:12
99% sure this is a dupe

**Comment by WJohn** [comment] 2015-10-08 03:49
Basically a dupe of #12134

**Closed by WJohn** 2015-10-08 03:49 UTC
