### ISSUE TITLE
Chameleon mutation is not kicking in

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#9876] opened 2015-06-10 05:12 UTC
Chameleon mutation is not kicking in
@Iamgoofball

**Comment by Iamgoofball** [comment] 2015-06-10 05:16
We found out this is because apparently everyone shares a mutation's datum 

You were MIA at the time

I don't know how to fix it

**Comment by phil235** [comment] 2015-06-13 21:43
duplicate of #8404

**Closed by phil235** 2015-06-13 21:43 UTC
