### ISSUE TITLE
Turning into a monkey removes xenomorph foetuses

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7678] opened 2015-02-12 08:59 UTC
As reported on singulo, being turned into a monkey removes xenomorph embryos from a human. This gives people a much faster and easier way to prevent chestbursting than surgery.

**Comment by scoopscoop** [comment] 2015-02-12 18:59
Didn't anatomic panacea remove the embryo too anyway?

**Comment by WJohn** [comment] 2015-02-12 19:10
Does this happen with other diseases or are they kept?

**Comment by Razharas** [comment] 2015-02-12 23:59
I thought thats intended

**Comment by WJohn** [comment] 2015-02-13 00:10
This doesn't make too much sense, but we have all sorts of mechanics for actually removing xenos, and if they're completely beaten totally and fully by turning them into a monkey and back then what's the point of using the intended method?

**Comment by Dorsisdwarf** [comment] 2015-02-13 21:34
Anatomic panacea doesn't fix xenoes.

**Comment by phil235** [comment] 2015-02-13 22:56
Other diseases are kept.

**Comment by xxalpha** [comment] 2015-09-07 23:12
Can't reproduce, this might have been fixed by a recent refactor.
@phil235

**Closed** 2015-09-08 15:29 UTC
Labels: Bug, In Game Exploit
