### ISSUE TITLE
Apparently fire makes mankees horny and speeds up pregnancy.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8837] opened 2015-04-08 22:34 UTC
![zp04ikq](https://cloud.githubusercontent.com/assets/10717398/7056850/c803147a-de4f-11e4-9cd7-d8efdefb15b9.png)

I honestly have no idea what causes this.

Inject gold cores with plasma
Hostile mobs spawn
Throw monkeys inside
They are set on fire by magicarp
500~ monkeys after 5 or so minutes almost killing the server and more were comming

**Comment by phil235** [comment] 2015-04-08 22:44
What other types of hostile mobs were spawned? I can't reproduce this with just monkey+magicarp

**Comment by SeikoTheSeal** [comment] 2015-04-08 22:45
Xeno queen, headslug, crate, magicarp with fireballs, chaos carp.

**Comment by SeikoTheSeal** [comment] 2015-04-08 22:51
Throwing ideas, maybe it has something to do with transfering fire stacks?

**Comment by RemieRichards** [comment] 2015-04-08 22:53
Fire stacks would (at worst, although I made sure this wouldn't happen) duplicate the fire effect.
It wouldn't make more monkeys.

**Comment by phil235** [comment] 2015-04-08 23:00
My guess is headslugs doind something bad.

**Comment by RemieRichards** [comment] 2015-04-08 23:03
Oh yeah headslugs can infinitely create monkeys.

One round I edited my ghost mind into a headslug spawned from slimes for "le epic events" (seriously why the fuck is it a mind datum and not a ckey?) And every second or so a new monkey would spawn after the egg had popped, and I'd be moved and put in control of the next monkey, and so on and so on.

I forgot to report it.

**Comment by phil235** [comment] 2015-04-08 23:08
headcrab.dm:

obj/item/body_egg/changeling_egg/proc/Pop()
	var/mob/living/carbon/monkey/M = new(affected_mob.loc)
	owner.transfer_to(M)
	owner.changeling.purchasedpowers += new /obj/effect/proc_holder/changeling/humanform(null)
	M.key = owner.key
	affected_mob.gib()
	qdel(src)

The egg is qdel'd but isn't deleted until much later by gc. And since each time the egg is processed it calls Pop(), it spawns a new monkey at the affected mob's location. QED.

**Comment by RemieRichards** [comment] 2015-04-08 23:09
here's the thing @phil235 it NEVER got cleaned up by the garbage collector in that round.

**Comment by phil235** [comment] 2015-04-08 23:10
This needs some sanity checks.

**Comment by Incoming5643** [comment] 2015-04-08 23:28
Also if I'm reading it correctly the head slug itself can just keep implanting more eggs while the first eggs incubate and even after the ling transfers to a monkey the now AI controlled slug will keep going for corpses and making apes.

The slug should either die after planting eggs or die after transferring consciousness,

**Comment by PKPenguin321** [comment] 2015-04-09 00:24
i was pretty sure it did die after planting the eggs

**Comment by AnturK** [comment] 2015-04-09 10:44
Whoops. I'll add add some checks in there and fix that internal organs thing.

**Closed** 2015-04-10 18:50 UTC
Labels: Bug, Priority: CRITICAL
