### ISSUE TITLE
Using bluespace capsules in a shuttle makes it leave a big part of the shuttle behind

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14783] opened 2016-01-22 18:23 UTC
[Like happened here](http://puu.sh/mFy0O/dcfb5b3608.png)

Shuttle was without those 2 parts(at this screenshot shuttle had left already)

**Comment by xxalpha** [comment] 2016-01-22 18:56
reminder that you can upload images to github

**Comment by WJohn** [comment] 2016-01-22 20:29
Dupe of #13842

**Closed by WJohn** 2016-01-22 20:29 UTC
