### ISSUE TITLE
If you space yourself in a coffin, and open the coffin, you stand still in space

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#9563] opened 2015-05-19 15:02 UTC
You completely lose all velocity if you open a coffin while travelling in space. Makes spacing people a bit less robust than it should be, as they can instantly travel back to the station without fighting the coffin-v.

**Comment by ike709** [comment] 2015-05-19 21:06
Feature, should have welded the coffin shut.

**Comment by spasticVerbalizer** [comment] 2015-05-20 17:33
Duplicate of #6569

**Closed** 2015-05-20 18:22 UTC
