### ISSUE TITLE
Space tile shenanigans [immersion]

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#10229] opened 2015-06-28 15:11 UTC
if a space tile is shown before the shuttle leaves, it will not be a moving-space tile.
![spaceweird](https://cloud.githubusercontent.com/assets/5677255/8396860/4a2f426c-1db0-11e5-99fa-3a03084f63a0.jpg)

**Comment by phil235** [comment] 2015-06-28 15:21
Duplicate of #9952

**Closed by phil235** 2015-06-28 15:21 UTC

**Comment by Chocobro** [comment] 2015-06-29 12:04
posting the screenshot in there since it's relevant to it.
