### ISSUE TITLE
disposal pipe white ship wonkiness

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#11171] opened 2015-08-12 21:05 UTC
this might be a dupe but i'm not sure and can't be bothered to look through 2000+ old issues
1. get white ship and RPD
2. go to derelict
3. make piping system with a chute on both ends leading from the white ship to the derelict
4. fly to the station
5. enter chute on the white ship
6. come out at the derelict
7. you now have a disportal pipe

this might actually work with the emergency shuttle too meaning you could potentially get people onto the shuttle after it's launched by connecting it to escape through pipes

**Comment by WJohn** [comment] 2015-08-12 22:31
I swear this is a dupe.

**Comment by Marflowerose** [comment] 2015-08-13 06:06
Essentially dupe of https://github.com/tgstation/-tg-station/issues/9903

**Comment by Dorsisdwarf** [comment] 2015-08-13 11:31
Now a dupe of master issue #11183

**Closed by Dorsisdwarf** 2015-08-13 11:31 UTC
Labels: Bug, In Game Exploit

**Comment by Supermichael777** [comment] 2015-08-15 14:45
does not work with emergency shuttel
