### ISSUE TITLE
An unscrewed APC that is accessed at range by silicons will stop opening the control window after the first time.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#8195] opened 2015-03-07 02:33 UTC
If the AI clicks on an APC with it's wires exposed, it will at first get the normal interface. Upon closing the window and clicking again, it will see the wires. 
After this, it will only see the wires, and never the controls. if the APC wires are unexposed, clicking on the APC will not open up any interface.

**Comment by palpatine213** [comment] 2015-04-04 21:50
Bump.
This also happens with cyborgs. It appears to caused by attempting to access the APC from range when the wires are exposed, both the control panel window and the wire window open.

**Comment by MrStonedOne** [comment] 2015-12-23 07:30
@neersighted is this still an issue?

**Comment by neersighted** [comment] 2015-12-24 15:10
Nope, should be fixed. The code was rewritten and I can't reproduce it.

**Comment by MrStonedOne** [comment] 2015-12-24 17:52
@duncathan @tkdrg @Jordie0608

**Closed** 2015-12-24 18:05 UTC
Labels: Bug
