### ISSUE TITLE
People on other Z-levels are knocked down forever after a nuke

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#7778] opened 2015-02-17 01:16 UTC
Probably doesn't matter too much, but this happened to me on the mining station a few days back and just happened to me as an operative in the Syndicate outpost. You're alive, you can speak, but nothing will get you back up.

**Comment by ike709** [comment] 2015-02-17 02:26
It's radiation poisoning!

**Comment by AnonymousNow** [comment] 2015-02-17 02:38
They should be well clear of the blastzone, considering the speed they travel on their shuttles.

**Comment by Steelpoint** [comment] 2015-02-17 12:45
Its a bit of a edge case since in most scenarios when the Nuke is detonated the round will end. The only scenarios I can think of where this is a problem is if a admin spawned nuke detonates (thus not ending the round) while the emergency shuttle is in transit to Centcom.

In that scenario, which I've been a apart of before, everyone is knocked on the floor for a considerable amount of time (1 to 2 minutes). However they will get back up.

However, blobs are not affected by this, which the crew unfortunately discovered as I was able to spread my blob all over the crew, but I digress.

**Comment by AnonymousNow** [comment] 2015-02-18 14:14
Aye, I acknowledge that it's not hugely important. I'm just not sure why it's there.

**Comment by Dorsisdwarf** [comment] 2015-02-19 11:49
Nukes on the station should always end the round. If they aren't something's gone wrong.

**Comment by Dorsisdwarf** [comment] 2015-02-23 11:13
This is a dupe of #7424

**Closed** 2015-02-23 13:42 UTC
Labels: Consistency Issue, Not a bug
