### ISSUE TITLE
Away mission blood red hardsuit

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14186] opened 2015-12-31 02:37 UTC
Far left. Space battle away mission, helmet sticks to hand/head, cannot be removed.

Mapping error, flat out remove the helmets to solve issue.

**Comment by KorPhaeron** [comment] 2015-12-31 02:40
Duplicate issue

**Comment by tkdrg** [comment] 2015-12-31 04:24
dupe of  #13548

**Closed by tkdrg** 2015-12-31 04:24 UTC
