### ISSUE TITLE
Improvised Shotguns have no onsprite

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8557] opened 2015-03-26 18:46 UTC
>The improvised shotguns from R&D (Single shot, made from modular receivers) have no on-sprite when worn on your back. Not sure if this was an oversight or if a unique onsprite simply does not exist.

>Additionally, they DO have one if you add a wire bandolier to them - But that does literally nothing as far as I can tell besides blow the cover of your weird invisible shotgun. Feels like an unfinished feature similar to the 'modular' receiver as a whole.

Reopened/dupe of #7709 which was closed because Pap said he had other shit to do

Pap is dead. Someone else should fix this.

**Comment by Dorsisdwarf** [comment] 2015-03-26 21:55
I think this maaay have been a hacky fix to someone moaning that you couldn't wear them without a strap that then backfired.

Don't quote me.

**Comment by Lumipharon** [comment] 2015-03-26 22:22
Wat, you're not supposed to be able to wear an improv shotgun without the wire strap - and last time I checked (a month ago?) that was still the case.

**Comment by phil235** [comment] 2015-03-29 12:22
Can't reproduce, the improvised shotgun can't be worn on your back unless it has a sling.

**Comment by phil235** [comment] 2015-03-29 12:25
Actually paprka did fix it in #7713. He forgot to mention the issue to close it.

**Closed by phil235** 2015-03-29 12:25 UTC
