### ISSUE TITLE
AI can see lights in the static

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#9414] opened 2015-05-09 01:44 UTC
1. Be an AI
2. Look at all the static/no vision in maint
3. Watch people run around in it because you can see their lights through the static

**Comment by WJohn** [comment] 2015-05-09 02:10
Does this mean the static is not illuminated? Or are you talking about walls that you do have cameras on being illuminated? Because this happens with absolutely everyone.

**Comment by KorPhaeron** [comment] 2015-05-09 02:24
I mean the static itself is illuminated, nevermind the walls as well.

**Comment by SconesC** [comment] 2015-05-09 02:58
Ghetto AI tracking finally gets an issue report

**Comment by WJohn** [comment] 2015-05-09 11:19
That's strange, static used to be full brightness in the past. Perhaps @mrperson changed something in his light overhaul.

**Comment by Cheridan** [comment] 2015-05-11 14:25
Have you heard my new band, Lights In The Static?

**Comment by MrPerson** [comment] 2015-06-22 08:39
This issue was fixed by #9911 and is a duplicate of #9884

**Closed** 2015-06-22 10:22 UTC
