### ISSUE TITLE
Doors created by wands of door creation are left behind when the escape shuttle leaves.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#6885] opened 2015-01-08 07:59 UTC
Doors created by wands of door creation are left behind when the escape shuttle leaves, stepping in the holes fires you into space.

**Edit:**
One way to fix it would be if the door staff shoots a shuttle wall, make the floor spawned under the door a shuttle turf.

**Comment by Tenebrosity** [comment] 2015-01-08 08:44
I like the idea of the shuttle not being impervious to damage by anything other than the singularity, but perhaps for consistency's sake and to fix this bug the wand of door creation should be unable to work on shuttle turfs?

**Comment by Incoming5643** [comment] 2015-01-08 09:09
worth noting that this didn't used to happen, a shuttle could very happily take off composed almost entirely of rickety wooden doors

**Comment by Boggart** [comment] 2015-01-08 10:02
It's due to the shuttle change, only shuttle turfs are brought along.

**Comment by Jalleo** [comment] 2015-01-08 10:28
are the chairs and tables affected at all on the shuttles?

**Comment by Miauw62** [comment] 2015-01-08 15:06
Wand of door creation probably turns the shuttle wall into an ordinary
simulated turf. I wish we had objwalls.
Op 8-jan.-2015 11:28 schreef "Jalleo" <notifications@github.com>:

**Comment by Jalleo** [comment] 2015-01-08 16:38
well there was a refactor that got turned down recently which made them objects....

**Comment by Miauw62** [comment] 2015-01-08 17:05
the refactor was closed by the dude who made it iirc

**Comment by tkdrg** [comment] 2015-01-08 18:10
I closed the refactor because it looked like the sort of thing that solved few problems and created many more. But that's off-topic. On the shuttle thing, the issue is that only /turf/simulated/shuttle turfs are moved by the new shuttle controller. Making the door creation plating on the shuttle /turf/simulated/shuttle/plating would solve the issue.

**Comment by Carn** [comment] 2015-01-10 22:14
I don't know why maintainers keep accepting wizard content
All of it is hacky
and the entire gamemode sucks

**Comment by Iamgoofball** [comment] 2015-01-10 22:55
take it to the feedback forums @Carn 

we should make door creation make a shuttle as an emergency measure if its used on the shuttle

**Comment by Carn** [comment] 2015-01-10 23:37
I'd rather you didn't. Just make them not work on shuttles.

**Comment by Iamgoofball** [comment] 2015-01-11 00:13
that works too

**Comment by Miauw62** [comment] 2015-01-11 09:15
There's nothing hacky about the wand of door creation
Op 11-jan.-2015 01:13 schreef "Iamgoofball" <notifications@github.com>:

**Closed** 2015-02-01 11:46 UTC
Labels: Bug, In Game Exploit
