### ISSUE TITLE
Drones can not take backpack water-tanks off, nor can they use them.

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/-tg-station#10550] opened 2015-07-11 16:08 UTC
When attempting to use the water tank, it states this when in your internal storage slot: 

The watertank needs to be on your back to use!

Dragging them to your hand-slots does nothing.

**Comment by Dorsisdwarf** [comment] 2015-07-15 17:52
[feature request]

**Comment by Shadowlight213** [comment] 2015-10-09 22:34
Dupe of #6597

**Closed** 2015-10-09 22:58 UTC
Labels: Bug
