### ISSUE TITLE
Incinerator Air Alarm bug

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9570] opened 2015-05-20 03:47 UTC
Incinerator room (new) has all-access air alarm that anyone can lock/unlock. I was unable to interact with the Air Alarm in regular fashion (setting vent to vent etc). I asked admin to verify but he could use it just fine. After that, I was able to use it aswell. Air alarm was unlocked when I tried interacting with it.

**Comment by francinum** [comment] 2015-05-20 20:51
Unable to Reproduce.

**Comment by Marflowerose** [comment] 2015-05-21 00:11
Okay, it didn't reproduce for me either now, must've been some buggs higgson byond thing or something.

**Comment by duncathan** [comment] 2016-01-20 05:32
fixed by tgui

**Closed by duncathan** 2016-01-20 05:32 UTC
Labels: Bug, Cannot Reproduce
