### ISSUE TITLE
Self-Respiration (Viro symptom) doesn't actually allow you to breathe without oxygen.

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#13660] opened 2015-12-15 06:33 UTC
The salbutamol it leaves in your system will slow down the rate of oxygen damage but it still does the damage to you, whereas before it completely eliminated the damage from the oxygen so I could cruise through space entirely naked and surprise pAIs.

I feel like something that's called self-respiration should probably allow you to, you know, self-respire.

As it is now it's not actually a very useful symptom to attach to diseases.

**Comment by octareenroon91** [comment] 2015-12-16 16:39
The healing is slower than the cure?

**Comment by newfren** [comment] 2015-12-17 04:12
The healing is slower than the damage, yes.

**Comment by octareenroon91** [comment] 2015-12-17 04:16
Oh wow, I made no sense earlier. I wouldn't be surprised if only one of salbutamol or suffocation damage changed, without the other.

**Comment by tkdrg** [comment] 2015-12-17 18:20
Closing as cannot reproduce according to J_Madison on #coderbus
```
15:14 < J_Madison> virology bug - can't breath in space is busted. go close the issue/bug report if you'd like
15:14 < J_Madison> you can indeed breath in space. however co2 is a different story
15:14 < J_Madison> co2 actually kills you. space doesn't.
```

**Closed by tkdrg** 2015-12-17 18:20 UTC
Labels: Bug
