### ISSUE TITLE
New Holoparasite text causes eye damage

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#16748] opened 2016-04-08 17:36 UTC
![ew](https://cloud.githubusercontent.com/assets/5169683/14392331/acc8c4f2-fd75-11e5-8727-7c9ae45a6da9.png)

Design practice and safety concerns for individuals' eye health is a serious matter.

**Comment by ChangelingRain** [comment] 2016-04-08 18:03
You are free to suggest a yellow that is more visible on a white background while still being yellow.

**Comment by ChangelingRain** [comment] 2016-04-08 18:04
also jeez this is basically a dupe of #16738

**Closed by ChangelingRain** 2016-04-08 18:04 UTC
Labels: Not a bug

**Comment by Niknakflak** [comment] 2016-04-08 19:52
I think your problem here is that you feel the need to have yellow on white. 
Also, it was a dupe? I had no idea.
