### ISSUE TITLE
D100 name and desc are bad.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8589] opened 2015-03-28 08:56 UTC
That's a d00.
A die with ten sides. Works better for d100 rolls than a golfball.

d00?

Ten sides?

**Comment by Jordie0608** [comment] 2015-03-28 11:52
It's correct; a d00 is a d10 with notations in tens instead of ones.

**Comment by RemieRichards** [comment] 2015-03-28 11:54
In code the d00 also actually only has 10 on the side var.
the result it gives you is simply the side it landed on multiplied by 10
```
	if(initial(icon_state) == "d00")
		result = (result - 1)*10
```
It's not a bug.

**Closed by RemieRichards** 2015-03-28 11:54 UTC
Labels: Easy Fix, Grammar and Formating

**Comment by WJohn** [comment] 2015-03-28 19:27
Oh, my bad then. I thought it was a 100 sided die.
