### ISSUE TITLE
using view variables on a changeling egg disconnects client

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#14691] opened 2016-01-17 11:35 UTC

**Comment by tkdrg** [comment] 2016-01-17 14:01
possible dupe of #10881

**Comment by Miauw62** [comment] 2016-01-17 15:16
yeah this happens unreproducably on a wide variety of things

**Comment by tkdrg** [comment] 2016-01-17 17:53
and the things change with each update

**Comment by PKPenguin321** [comment] 2016-01-17 19:09
I bet this will turn out to be some really stupid and bizarre byond bug

**Comment by hornygranny** [comment] 2016-01-17 22:15
this is reproducible between rounds but i have no idea why it happens

**Comment by Jalleo** [comment] 2016-01-17 22:18
Report it on byond maybe lummox can work it out.

**Comment by octareenroon91** [comment] 2016-01-20 15:56
Unsanitized \improper in a binary stream, anyone?

**Comment by tkdrg** [comment] 2016-01-23 14:38
dupe

**Closed by tkdrg** 2016-01-23 14:38 UTC
Labels: Administration, Bug
