### ISSUE TITLE
Itemes slow you down inhand

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#13695] opened 2015-12-16 06:57 UTC
no longer can you hold your hardsuit to walk faster.
this includes galoshes and bear traps

**Comment by Cebasiz** [comment] 2015-12-16 07:05
wasn't this intentional

i'm pretty sure it was?

**Comment by tkdrg** [comment] 2015-12-16 07:26
@KorPhaeron made this intentionally yep (see #13524), thus i'm closing this as not a bug

**Closed by tkdrg** 2015-12-16 07:26 UTC
