### ISSUE TITLE
AI loses ability to track through chat after some time 

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#10059] opened 2015-06-20 21:20 UTC
as title, sometimes when the AI tries to track through chat it will receive a message that that player is not near cameras when indeed they actually are; can be worked around by going to the track.. list (at the bottom of the AI HUD) finding them in the list. do note that this bug effects all players, when it occurs, not specific ones. once the bug has happened no one will be trackable through chat at all, and you will only be able to use the AI HUD track. caused me much confusion until i figured out what was going on. have seen it reoccur for other AIs as well.

i'll play some AI today and see if it happens again. i don't think it occurs all the time, just some of the time.

**Comment by WJohn** [comment] 2015-06-20 21:38
Dupe of #10032

**Closed by WJohn** 2015-06-20 21:38 UTC
