### ISSUE TITLE
transformation sting is broken

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11330] opened 2015-08-23 01:12 UTC
As it says in the title since middle mouse clicking people does noffin.

Also on a side note it has a choice to "Drop Flesh Disguise" in the transformation sting menu

**Comment by WJohn** [comment] 2015-08-23 03:37
Dupe of #11235 
Almost identical title, too!

**Closed by WJohn** 2015-08-23 03:37 UTC
