### ISSUE TITLE
Things are getting laggy

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9031] opened 2015-04-18 02:57 UTC
Might be a server thing
Might be a code thing

But it seems to be becoming a constant enough thing that it should probably get looked into either way.

**Comment by Aranclanos** [comment] 2015-04-18 03:56
do you need a hero?

**Comment by phil235** [comment] 2015-04-18 11:16
Could it be linked to the recent upgrade to atmos speed?

**Comment by Incoming5643** [comment] 2015-04-18 15:48
could be that, could be the new lighting system, could be some unintended side effect of a known somewhat laggy system with a new system (looking at you, starlight)

**Comment by Alek2ander** [comment] 2015-04-18 21:31
![](https://i.imgur.com/1j2Pcx9.png)
Related?

**Comment by xxalpha** [comment] 2015-04-18 22:35
Confirmed, feels much laggier than usual.

**Comment by Dorsisdwarf** [comment] 2015-04-19 08:47
I blame spinning and singulo throwing for the devastating lag that happens when singuloth breaks loose. All that hard work down the drain so goonball could have *flip

**Comment by xxalpha** [comment] 2015-04-19 13:16
It's not just when singulo is loose. It's laggy all the time, the game feels slower than usual.

**Comment by Aranclanos** [comment] 2015-04-19 14:44
do you need a heroo?~

**Comment by optimumtact** [comment] 2015-04-20 01:09
Spinning, spinning spinning all our cpu down the drain

**Comment by Iamgoofball** [comment] 2015-04-20 02:08
@Dorsisdwarf 
![zcdfndm](https://cloud.githubusercontent.com/assets/4081722/7222623/38633716-e6c7-11e4-877c-744d180936b3.jpg)

Please fuck off you autistic neckbeard jackass. This has been fixed, and is fixed on the latest build, but since you're retarded as fuck you think "HURR LET'S TALK ABOUT ALREADY FIXED BUGS LIKE THEY STILL EXIST JUST TO SHIT ON SOMEONE!". If you argue "b-b-but I didn't know it was fixed!!!" then maybe you should of done your fucking research first before making stupid statements that make you look like a retarded kindergarden drop-out faggot.

When you assholes can fucking stop calling me "goonball" to insult me, pull the dragon dildo out of your collective assholes, and then find something better to do then shit on me, I'll consider not being a douchebag back when shit like this is posted.

Although, I bet you retards will start acting entitled and screech about how I'm being the bad guy here and insulting the pure maiden players that did nothing wrong when you guys spit out more toxic bile and acidic insults then a fucking 8 year old playing CoD. If you guys can be total asswipes, why do I get shat on when I respond in kind?

**Comment by phil235** [comment] 2015-04-20 11:27
As xxalpha said, it's laggy all the time, so spinning isn't to blame for the overall lag.

**Closed** 2015-05-02 13:58 UTC
Labels: Performance
