### ISSUE TITLE
"Jug of Caustic Soda" spawns without a sprite

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#8330] opened 2015-03-13 16:32 UTC
In maintenance, one can find a number of "Jugs of Caustic Soda" by right-clicking the various places where things can randomly spawn. However, these jugs lack an icon sprite (though they do have an inhand), and are invisible when laid down.

**Comment by francinum** [comment] 2015-03-13 16:37
Duplicate of #8246

**Closed** 2015-03-13 16:37 UTC
