### ISSUE TITLE
Clicking on old posibrain links

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#12644] opened 2015-10-25 06:44 UTC
Clicking on old posibrain links WHILE THE POSIBRAIN HAS BEEN BORGED can lead to you getting inserted in the brain, in the borg
This leads to severe split personality disorder (or whatever it's called) in androids

Remember: ITS NOT A BUG, ITS A FEATURE.

**Comment by GunHog** [comment] 2015-10-25 06:45
I will get around to fixing it if phil does not beat me to it.

**Comment by kevinz000** [comment] 2015-10-25 06:49
@GunHog 
You should fix it so if the borg falls asleep or logs out or similar the extra personality takes over :^)

**Comment by PKPenguin321** [comment] 2015-10-25 07:08
this is probably a dupe, i feel like i've seen this before

**Comment by phil235** [comment] 2015-10-25 11:10
duplicate of #11331

**Closed by phil235** 2015-10-25 11:10 UTC
