### ISSUE TITLE
Asteroid sand doesn't work as floor

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9445] opened 2015-05-10 18:19 UTC
It used to be possible to place cable on the Asteroid sandy floor but doesn't work anymore.

**Comment by EchoFade** [comment] 2015-05-10 18:50
:+1:  yes this is a huge issue for my solar powered mining-sat

**Comment by WJohn** [comment] 2015-05-10 20:15
Dupe of #8702

**Closed** 2015-05-10 22:59 UTC
