### ISSUE TITLE
Window damage overlays do not update correctly

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#10533] opened 2015-07-11 01:33 UTC
Repaired a window but the damage overlay stayed on
http://pastebin.com/P5rxyWeG - vars at the time (can see it has 50 health)
http://puu.sh/iUJwt/e554a6357c.png

Screenshot

**Comment by WJohn** [comment] 2015-07-11 03:00
Yeah I noticed it seemingly trying to put the overlay on twice before correcting itself.

**Comment by Jordie0608** [comment] 2015-07-11 04:34
Dupe of #10523, which was fixed.

**Closed by Jordie0608** 2015-07-11 04:34 UTC
