### ISSUE TITLE
prompts auto hitting yes

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14038] opened 2015-12-25 06:46 UTC
I swear there was an issue for this before, but I'll report it again
constantly when typing in deadchat and a prompt shows up you automatically hit yes and half the time you become some shit you don't want
just make it like pAIs 
please fix dear god its so fucking annoying

**Comment by Tetsukiba** [comment] 2015-12-25 07:03
You automatically hit yet because you're typing, it doesn't just answer for you. What do you want extra verification, half the time the competitor has already spammed enter on the yes button.

**Comment by Zilenan91** [comment] 2015-12-25 07:03
The other issue got closed because there's no other way to do this.

**Comment by Bawhoppen** [comment] 2015-12-25 07:08
@Tetsukiba what are you even saying

**Comment by Bawhoppen** [comment] 2015-12-25 07:12
oh ok I see what you mean
I made this issue considering most people already know what I meant, I know that its because you're typing. I was just saying make it like pAI where it doesn't hit yes when typing and you get put into something you don't actually want to be put into.

**Comment by Tetsukiba** [comment] 2015-12-25 07:15
That's Why I said, add Extra verification, Or you could stop typing! I think that's just a general issue with computers. If I'm typing to a bot on facebook with really nice tits and I get a pop-up that sends me to gay porn, It's not my fault that I was typing, but the computer is going to do whatever it wants.

**Comment by Bawhoppen** [comment] 2015-12-25 07:16
pAI prompts already work in a way thats just fine, just make it follow that

**Comment by Tetsukiba** [comment] 2015-12-25 07:18
Oh you mean the rest of the prompts, for other things, gotcha.

**Comment by Incoming5643** [comment] 2015-12-25 09:24
You don't have to rush to accept the roll, the list of applicants in the first 10 seconds is picked for randomly

**Comment by duncathan** [comment] 2015-12-25 10:05
>stop typing!

Yeah sure I'll just use my inhuman reaction times and stop as soon as I see it

**Comment by MrStonedOne** [comment] 2015-12-25 12:19
there is a better way actually.

make a custom window for them.

Then we can close them when the time is up!

**Comment by KorPhaeron** [comment] 2015-12-25 13:55
>Then we can also close them when the time is up!

That'd be fantastic. Coming back from getting a snack to see the game taunting me with all the antag rolls I missed is heart breaking

**Comment by WJohn** [comment] 2015-12-25 16:21
Dupe of #12134

**Closed by WJohn** 2015-12-25 16:21 UTC

**Comment by Bawhoppen** [comment] 2015-12-25 16:24
see I told you it still existed
