### ISSUE TITLE
Client verbs cant take arguments if arguments names are special

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#11856] opened 2015-09-18 13:03 UTC
Client verbs cant take arguments if arguments names are special

Namely anything which name starts with "\improper *any non-character non-space symbol*" is unaccessable to verbs such as delete or view variables in any way

Only client verbs show this behaviour, shit like examine is in mobs and thus works fine

Only arguments are unaccessable, client procs that dont take arg can access these things later in their body just fine

Thats because byond tried to access the object in "name.ref" fashion, and improper and other text macros do something unusual and make byond derp if the special symbol in the name is the first one

Just any name that starts with special symbol is ok

Thanks byond

**Comment by MrStonedOne** [comment] 2015-09-20 09:20
I can't reproduce this,

Could you elaborate more?

**Comment by Razharas** [comment] 2015-09-20 22:21
Spawn reset AI module/.357 revolver/.38 revolver/uzi
Try to varedit them
You will get message with error
>Sorry, the following is not valid: \.38-Mars-Special.0x201f549
>usage: View-Variables mob|obj|turf|area in world

Like this one
Same if you try to delete it through rightclick menu

**Comment by Razharas** [comment] 2015-09-20 22:22
It is also possible that only non-hosts get this, but i didnt test

**Comment by MrStonedOne** [comment] 2015-09-21 10:18
Correction, This also seems to apply to mob verbs.

**Comment by MrStonedOne** [comment] 2015-09-21 10:26
Also, Can you please rename proc to verb in this issue report and in your pr.

That is confusing as fuck. The proc will take the arguments, its the verb functionality to provide an interface to the proc that is broke.

**Comment by MrStonedOne** [comment] 2015-09-21 10:27
Related Byond report filed: http://www.byond.com/forum/?post=1946035

**Comment by Razharas** [comment] 2015-09-21 14:57
Thats strang because there are a lot of AI law modules that start with ' symbol without \improper and they work fine, yet uzi that has \improper 'type 3' name do show this behaviour

**Comment by Razharas** [comment] 2015-09-21 15:09
No i just tested and my pr does make the objects accessable, since i only removed \improper thats the only option

**Comment by Razharas** [comment] 2015-09-21 15:10
@MrStonedOne

**Comment by MrStonedOne** [comment] 2015-09-23 12:09
I was using the verb with no arguments, and not right click. So that might be it. My test project doesn't have a map so i couldn't test right click.

**Comment by optimumtact** [comment] 2015-10-16 03:33
Resolved (509.1301)

**Comment by tkdrg** [comment] 2015-12-16 15:20
fixed in 509

**Closed by tkdrg** 2015-12-16 15:20 UTC
Labels: Bug, BYOND Issue, Grammar and Formating
