### ISSUE TITLE
Self-Respiration doesn't work (also maybe toxin filter)

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10698] opened 2015-07-19 08:27 UTC
Got 2 viruses with Self-Respiration, 5/5 both, got steady GROWTH of suffocation damage in space, verified by Shadowlight213. This is different from the usual 1 suffocation damage that goes away.

Edit. Also found out geneticist had toxin damage that the regenerative viruses never cured, despite having 3 toxin filters

Edit 2. The geneticist had all 3 viruses but possibly dying during the round and being defibbed may have fucked over the viruses

**Comment by WJohn** [comment] 2015-07-19 08:34
Might be related in that breathing from an air tank is somewhat broken right now.

**Comment by newfren** [comment] 2015-07-19 09:02
Can confirm, was the geneticist. I definitely had 22 tox damage in my system and checked several times to make sure all 3 viruses were 5/5.

**Comment by phil235** [comment] 2015-07-19 11:38
Can't reproduce the bug with toxic filter.

**Comment by Marflowerose** [comment] 2015-07-19 11:54
I don't know what caused the toxin damage on @newfren but as I recall, he died, got defibbed, still had the viruses 5/5 and some time after that I got note about the toxin damage that didn't heal.

**Comment by newfren** [comment] 2015-07-19 12:14
It was actually also present before I got defibbed. The 22 tox damage was there before I was defibbed, and it looks like the diseases just weren't doing anything after I was defibbed.

**Comment by bustygoku** [comment] 2015-07-19 21:01
Pretty sure self respiration heals oxy damage fast so this is probably a bug with goofchem

**Comment by phil235** [comment] 2015-07-19 21:36
The problem isn't the salbutamol reagent (that self respration symptom is supposed to inject), it works fine if you inject yourself manually and them go in space. You take oxy damage but very slowly, unlike when I tested the selfRespiration virus so It's definitely an issue with the virus not being active.

**Comment by phil235** [comment] 2015-07-19 22:06
@Marflowerose How fast was the oxy damage rate? a slow increase is intended by the code it seems.

**Comment by Marflowerose** [comment] 2015-07-20 02:03
It seemed to be approximately 1 damage every 1-2 seconds and I didn't notice it going down at any point, like how brute/burn/toxin fluctuates normally with viruses when spacewalking nude.

**Comment by AlexanderUlanH** [comment] 2015-07-20 05:45
It's possible to change your metabolism rate ingame.  Maybe that had something to do with it.

**Comment by phil235** [comment] 2015-07-20 10:27
@Marflowerose the viruses only pumps you with salbutamol when you don't have any in you, so having one self-respiration virus or three has the same effect. I think it is working as intended. The only potential issue is how much oxy damage you take per life cycle in an airless environment (I changed that value a couple months ago during my life refactor I think) so it's an easy fix.

**Comment by Marflowerose** [comment] 2015-07-20 10:31
Yeah I know Self-Respiration, Ocular Repair and Stimulant don't stack but I tend to keep Self-Respiration on all viruses since there's no telling which one gets carrier mode on and never goes above 1/5.

**Comment by tkdrg** [comment] 2015-12-20 22:26
@LanCartwright recently reported being unable to reproduce this. Closing unless someone else manages to reproduce it.

**Closed by tkdrg** 2015-12-20 22:26 UTC
Labels: Bug, Cannot Reproduce, Tested / Reproduced
