### ISSUE TITLE
foam is fucked up the ass #1: foam is slow as shit

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#7862] opened 2015-02-21 10:44 UTC
@Cheridan 

Problem Description: foam is so slow I could outrun it at flashing red health while walking

What did you expect to happen: i expected foam to fill the room in a few seconds

What happened instead: the foam very very slowly advanced across the floor at iceberg speeds

Why is this bad/What are the consequences: well foam is kinda worthless right now because of this

Steps to reproduce the problem: 
step 1. get a cleaner foam grenade
step 2. throw a foam grenade
step 3. observe slow as fuck foam spread

Server: local testing

Revision: latest build as of 2/21/2015

Possibly related stuff: testing shit locally for goonchem part 4,  haven't touched foam code yet

**Comment by phil235** [comment] 2015-02-21 11:07
The slowdown was listed in the PR.

**Comment by paprka** [comment] 2015-02-21 11:10
Not a bug, intentional. Foam slip grief was kinda shit.

**Comment by Iamgoofball** [comment] 2015-02-21 20:22
Foam is now literally useless to use now then compared to smoke

the prebuilt slipping just needed removed

**Comment by Fox-McCloud** [comment] 2015-02-22 04:55
@Iamgoofball 

Keep in mind that slipping on Goon is very different from here (as are all stuns and weakens).

When you're slipped/stunned/weakened, you don't immediately fall down; there's a good 1-1.5 second delay before they finally kick in....so...with foam, yes, you slip on it and can't really avoid that because of how fast it spreads, but it's still quite easy to make your way out of the foam before finally falling down.

**Comment by phil235** [comment] 2015-06-22 11:15
This was intended. Foam can still be useful offensively if your target is cornered, if they move they slip and get foamed, if they don't move, the foam reach them and they get foamed. Closing this.

**Closed by phil235** 2015-06-22 11:15 UTC
Labels: Bug
