### ISSUE TITLE
Holy shit goonchems are barely implemented and you deleted the normal chems which have no replacements

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#7133] opened 2015-01-17 16:26 UTC
-Viruses cannot be cured
-Cryo mixes cannot be made
-The genetically damaged stay that way forever unless you use that limited supply of roundstart cryo
-The retarded are permanently retarded.
-Heaters don't work at any of the listed values or above them

How about instead of making chem even more dangerous with OD and shit, you actually fix what's there. We know your main goal is to replace the word "Tricord" with "Styptic powder", but come on - peopel have to play the game while you twiddle your thumbs and think of ways to make TG Goon But Not Coded Badly.

**Comment by AlexCrimson** [comment] 2015-01-17 16:44
Im all for goonchem, but removing the old system seems premature.

**Comment by vista-** [comment] 2015-01-17 16:46
>-The retarded are permanently retarded.

lifelike medical conditions ;_;

**Comment by Iamgoofball** [comment] 2015-01-17 16:55
>retardedness is permanant

Mix some Mannitol.

**Comment by Iamgoofball** [comment] 2015-01-17 16:56
>genetic damage is permanent 

Mix some Mutadone

**Comment by Iamgoofball** [comment] 2015-01-17 16:57
>viruses cannot be cured

What was the cure marked as? I'll take a look.

**Comment by Iamgoofball** [comment] 2015-01-17 16:58
Also, what version was this?

**Comment by tkdrg** [comment] 2015-01-17 17:33
All of the complaints in this issue don't exist. You're wrong on all accounts.

> -Viruses cannot be cured
All the cures have been either kept or replaced with the goonchem equivalents. Spaceacillin is still here as well.
> -Cryo mixes cannot be made
Yes they can, both cryox and clonex were kept, and you can mix the injectable goon chems as well.
> -The genetically damaged stay that way forever unless you use that limited supply of roundstart cryo
You can mix cryox/clonex.
> -The retarded are permanently retarded.
You can mix mannitol.
> -Heaters don't work at any of the listed values or above them
I don't know what's that supposed to mean. If it's about the chem heaters, I tested them locally and they work just fine. I'll test in-game soon.

The one thing that's missing is updating the wiki, but the rest is fine, and the changelog gives some pretty good hints about replacements anyway. Closing this as a non-issue.

**Closed by tkdrg** 2015-01-17 17:33 UTC

**Comment by Dorsisdwarf** [comment] 2015-01-17 17:54
Ah, so, the answers to all these were chems that aren't on the wiki coupled with the PR saying "Removes all non-goon chems" being a lie. I see.

**Comment by Dorsisdwarf** [comment] 2015-01-17 17:55
Specifically "Star Trek medicines have been brutally murdered and replaced with goon chemicals in all instances of use."

Except they haven't, because either this is a lie, or diseases still want ryetalin. Which is a 'Star Trek Medicine'

**Comment by Iamgoofball** [comment] 2015-01-17 22:53
i'm trying to find the reference to ryetalin in the code, but I can't reproduce this issue

also @tkdrg you can use Mutadone to fix genetic problems, not just cryo
