### ISSUE TITLE
Gas mask doesn't always show up on character when used with blood red hardsuit.

### ISSUE THREAD

**Issue by Lo6a4evskiy** [tgstation/-tg-station#13486] opened 2015-12-06 20:36 UTC
1. turn on travel mode helmet
2. put on gas mask (didn't test with other masks or hardsuits)
3. switch to combat mode (results in no mask on character)
4. turn off helmet (results in no mask on character)

You can also keep turning the helmet on and off and switch modes, mask doesn't show up unless you take it off and then put it on in circumstances other than described above. For instance, if you put it on when combat mode is on, it shows up just fine.

Screenshots of steps 3 and 4 respectively (it doesn't matter whether there is another hat equipped or not):
http://i.imgur.com/LWpLdm0.png
http://imgur.com/QUj7ykJ.png

**Comment by WJohn** [comment] 2015-12-06 21:04
I can understand the hair/mask hiding mechanics used in the first one (we could probably have it ONLY hide hair), but the second one shouldn't be hiding your mask at all??

**Comment by Lo6a4evskiy** [comment] 2015-12-06 21:05
There's actually a sprite with the mask for the first one as well. Just doesn't show up in this particular case.

**Comment by newfren** [comment] 2015-12-06 22:35
Pretty sure this is a dupe of an existing bug with the welding helmet that's floating around somewhere.

**Comment by PKPenguin321** [comment] 2015-12-07 01:31
looks like this is the electric boogaloo of https://github.com/tgstation/-tg-station/issues/12729 which was supposedly already fixed

**Comment by newfren** [comment] 2015-12-07 07:10
@tkdrg

**Comment by Bawhoppen** [comment] 2015-12-07 15:06
speaking of this did we ever make hoods not do this too?

**Comment by tkdrg** [comment] 2015-12-07 15:59
Well, I fixed it on the welding visor toggle, so yeah. Just need to add head_update() calls to anything that changes HIDE_ flags in the head.

**Comment by Lo6a4evskiy** [comment] 2015-12-10 09:16
By the way, welding mask is confirmed to be bugged too, just experienced it yesterday. Are you sure you fixed it, @tkdrg?

**Comment by tkdrg** [comment] 2015-12-10 17:29
I just tested it and it is indeed bugged again, which is weird. I was pretty sure I fixed it. I'll see if I'll look at this code again later on (I've been putting this off because it's awful and full of copy-paste).

**Closed** 2015-12-20 05:10 UTC
Labels: Bug, Consistency Issue
