### ISSUE TITLE
Chemical dispenser doesn't work when running game in Wine with IE8

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#1622] opened 2013-10-22 18:49 UTC
I am running Wine 1.6 in Xubuntu 13.10.

I don't know whether it's IE8 or Wine, but I imagine it's IE8. All that would be required to verify that it is IE8 is to test it by running BYOND on Windows XP, which is not compatible with any version of IE after IE8.

As is visible in the screenshot, none of the buttons on the chemistry dispenser are available.

http://i.imgur.com/Q39bUjP.png

**Comment by Deantwo** [comment] 2015-01-28 17:39
Is this still an issue?

**Comment by AlexanderUlanH** [comment] 2015-04-23 16:04
I can confirm that this still happens.
It's not just chem dispensers, it's everything that uses NanoUI, including APCs, Sleepers, and SMES.

**Comment by Aranclanos** [comment] 2015-05-24 12:51
I'm removing nanoUI.

**Comment by Iamgoofball** [comment] 2015-05-24 17:50
@Aranclanos sorry what

**Comment by Deantwo** [comment] 2015-05-24 18:12
> I'm removing nanoUI.

What? You have a better replacement?

**Comment by Aranclanos** [comment] 2015-05-24 18:20
thats the plan

**Comment by Deantwo** [comment] 2015-05-24 18:22
> thats the plan

Plan is to find a replacement?

Hopefully before you "remove" it, right?

**Comment by Aranclanos** [comment] 2015-05-24 18:25
to make it you big faggot

**Comment by Deantwo** [comment] 2015-05-24 18:39
> to make it you big faggot

Your the one that is posting very short messages. ._.

Can't know what your thinking/planning if you only say the first half of the sentence.

"thats the plan" didn't answer my question, so of course I am confused.

**Comment by Aranclanos** [comment] 2015-05-24 18:59
what do you mean by shor

**Comment by Deantwo** [comment] 2015-05-24 19:03
Anyway, so you wanna replace NanaUI. Sure make a new system that is better. But lets talk about it after you have a working prototype.

Remove != Replace

**Comment by Aranclanos** [comment] 2015-05-29 22:49
Okay, I tried something and ended up working perfectly and I was pretty happy,  it did everything that nanoUI does, but it didn't use javascript so it kinda sucks because to update it has to send the entire page.
I don't know if I have to work with this or start over, but I'm extremly burn out after 13 hours

**Comment by Razharas** [comment] 2015-12-03 11:40
We need to test it again once @neersighted finishes his nanoui thingies

**Comment by neersighted** [comment] 2015-12-17 16:36
This should work now. @Razharas close this?

**Comment by tkdrg** [comment] 2015-12-24 22:15
works 4 me

**Closed by tkdrg** 2015-12-24 22:15 UTC
Labels: Bug, UI
