### ISSUE TITLE
Electrode jitter animation allows for chainstunning (turrets

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7943] opened 2015-02-23 23:07 UTC
@phil235 

Due to the electrode jitter animation on hit, turrets with electrodes now chainstun indefinitely.

**Comment by phil235** [comment] 2015-02-24 10:21
can't reproduce with standard AI chamber and AI upload turrets.

**Comment by phil235** [comment] 2015-02-26 14:06
will probably be fixed by #7986

**Comment by phil235** [comment] 2015-04-06 17:57
Has someone noticed this bug happening lately?

**Comment by Jordie0608** [comment] 2015-04-07 05:15
Yeah this was fixed.

**Closed by Jordie0608** 2015-04-07 05:15 UTC
Labels: Cannot Reproduce
