### ISSUE TITLE
SMES deconstruction not logging

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10553] opened 2015-07-11 18:01 UTC
If someone deconstructs a SMES, it will only show that the SMES was deleted. FIngerprints are not transferred, and there is no logging of who deconstructed it.

**Comment by Boredone** [comment] 2015-07-11 19:52
Copy of #10413 but probobly still a problem.

**Comment by Dorsisdwarf** [comment] 2015-08-04 21:20
Closed for dupe of #10413

**Closed by Dorsisdwarf** 2015-08-04 21:20 UTC
