### ISSUE TITLE
Blob fails to spawn on Solars

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#6961] opened 2015-01-11 06:53 UTC
Had a blob antagonist attempt to burst while on the Fore Port Solar array.

He gibbed, but he did not become a blob. The tile he was standing on was a catwalk.

The round did not end there, and would likely have never ended had admins not intervened and respawned him as a blob on station.

**Comment by tkdrg** [comment] 2015-01-11 07:17
@paprika

**Comment by Anonus** [comment] 2015-01-11 17:38
Technically not a bug(not that I like it); catwalks are just lattices on space tiles, and thus blobs can't burst on them.
Aliens can't put stuff on them either.

**Comment by Ikarrus** [comment] 2015-01-11 17:40
Putting the round in a neverending state is pretty much a bug. 

The shuttle can't come during blob, and there's no blob to kill. The round would never end.

**Comment by tkdrg** [comment] 2015-01-11 18:19
Yeah, the blob doesn't need to be able to burst there. Maybe teleport it to one of the blob spawns for admin blobs or whatever. Just anything that doesn't break the gamemode.

**Comment by leibniztg** [comment] 2015-01-11 18:40
Bursting on solars was a valid strategy before it was arbitrarily decided that it shouldnt be.
The tradeoff was that you were near a lot of spacetiles which means spreading was hard and you didnt have rwalls protecting you so pacman+emitter platforms in space could get you.

**Comment by optimumtact** [comment] 2015-01-13 22:39
Blobs shouldn't be able to burst somewhere that's not a valid spot, so thats the root bug.

**Comment by RemieRichards** [comment] 2015-01-13 22:40
@optimumtact How do you suppose it's fixed? reset that blob candidate's burst timer to an arbitrary time until it decides to go to a valid turf? What if it sits in an invalid spot forever?

**Comment by optimumtact** [comment] 2015-01-13 22:42
I think reset + admin notice should do the trick, along with a warning to player

**Comment by Ikarrus** [comment] 2015-01-13 22:43
Give them another 30 seconds to find a valid spot or they'll just get spawned in a random blobspawn location

**Comment by tkdrg** [comment] 2015-01-13 23:17
The thing is that blob spawns are pretty well placed and desirable, so it would be a valid tactic for a desperate blob to pop in an invalid place (if it lacks maint access for example).

**Comment by Ikarrus** [comment] 2015-01-13 23:23
Kill them and make someone else blob?

I just don't think an admin notice alone is going to cut it. It should be automated in such a way that it wouldn't rely on a present admin to prevent abuses.

**Comment by paprka** [comment] 2015-01-14 17:14
This happens on any space tile then

**Comment by Miauw62** [comment] 2015-01-15 16:00
What area do solars have?

**Comment by paprka** [comment] 2015-01-15 22:19
they have catwalks that are glorified lattices, not turfs

**Comment by Dorsisdwarf** [comment] 2015-03-02 11:10
99% sure that this was fixed by one of the two seperate PRs put up to handle this, requesting closure @Cheridan

**Closed** 2015-03-02 12:26 UTC
Labels: Bug, Priority: High
