### ISSUE TITLE
VVing a welding tool (any kind) will disconnect you.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14782] opened 2016-01-22 12:23 UTC
What it says on the tin.

**Comment by phil235** [comment] 2016-01-22 13:32
Happens consistently on every round, on both Basill and Sybil. It only seems to happen when access VV through rightclick. VV'ing a toolbox and then clicking the weldingtool in its content opens the weldingtool's variable window just fine.

Also, I can't reproduce this locally with a 2-3 weeks old tg code.

**Comment by tkdrg** [comment] 2016-01-22 18:09
That same old byond bug again I'd wager.  We have like 4 reports of it. Someone complain on the byond forums please

**Comment by PKPenguin321** [comment] 2016-01-22 18:19
probably definitely related to https://github.com/tgstation/-tg-station/issues/14691 and also many of the other similar issues reported in the past, such as the one for VVing radio headsets

**Comment by Shadowlight213** [comment] 2016-01-22 20:39
Yeah. Dupe of that issue which is a dupe of another issue. Honk.

**Comment by tkdrg** [comment] 2016-01-23 14:38
dupe

**Closed by tkdrg** 2016-01-23 14:38 UTC
Labels: Administration, Bug

**Comment by optimumtact** [comment] 2016-06-07 04:40
of #10881
