### ISSUE TITLE
Connected cyborgs being shown to AIs aren't synched.

### ISSUE THREAD

**Issue by killerx09** [tgstation/-tg-station#14656] opened 2016-01-16 08:53 UTC
http://imgur.com/SIw6Ia3

http://imgur.com/TkPW5fM

http://puu.sh/mxC6T/543dd746d8.png

Tsar said that the borg isn't synched.

Goofball said that it was a bug.

Also, the borg that was affected wasn't a roundstart borg.

**Comment by WJohn** [comment] 2016-01-16 12:24
Dupe of #14646

**Closed by WJohn** 2016-01-16 12:24 UTC
