### ISSUE TITLE
Life chemical is not used up upon reacting.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8828] opened 2015-04-08 10:58 UTC
You're left with a beaker of "life" that does nothing. I don't think this is intended, it should probably make an appropriate number of creatures based on how much life chem was used in the reaction.

**Comment by Iamgoofball** [comment] 2015-04-08 16:29
it's supposed to make a single creature, any more then 1 would be way too overpowered for chemistry

**Comment by WJohn** [comment] 2015-04-08 16:51
That's fine and all, but the chem should at least vanish. The hell are you gonna do with liquid "life" then?

**Comment by Iamgoofball** [comment] 2015-04-08 16:53
the novelty of having /life/ in a beaker in front of you?

be a snake oil salesman, RP with it

**Comment by Lumipharon** [comment] 2015-04-09 02:16
This is an issue I reported, regarding every single react on mix goonchem, not just life.

**Comment by Iamgoofball** [comment] 2015-04-09 04:54
Yes, an issue you reported and then claimed a **non existing** crash bug was caused by the issue.

**Comment by Lumipharon** [comment] 2015-04-09 06:51
I told you directly on IRC and in previous PR(s?)

And as I said, after testing it on a test server, it ONLY crashed when I used the leftover liquid dark matter reagent itself in the chem smoke, NOT if you used the ingredients for it  - hence it indirectly caused the crash.

**Comment by Iamgoofball** [comment] 2015-04-09 13:25
OH MY GOD

IT WAS BECAUSE OF A SPECIFIC REACTION TURF AND REACTION OBJ CALL ON LDM

IT WAS LDM AND SORIUM SPECIFIC

I FUCKING SAID THIS

200 FUCKING TIMES

**Comment by Lumipharon** [comment] 2015-04-09 20:15
Goof.
Pap hotfixed it.

I realise it no longer happens, it was a critical bug and it got fixed with a few hours.

**Closed** 2015-04-10 05:32 UTC
