### ISSUE TITLE
Bag of Holding has generic backpack sprite inhand

### ISSUE THREAD

**Issue by cookingboy3** [tgstation/-tg-station#11381] opened 2015-08-25 09:25 UTC
I might be phrasing that wrong, but the Bag of Holding seems to be using the normal, grey backpack sprite for characters that are holding it. (it does have a proper sprite when on a character's back, however.)

found on sybil
revision: ba1a26830583f5273f6a9b123e43f889d7f6d40f

**Comment by Jalleo** [comment] 2015-08-25 09:55
occurs with all sprites for backpacks I think dunno about dufflebags or satchels.

**Comment by xxalpha** [comment] 2015-08-25 09:57
Have you ever seen a unique bag of holding inhand sprite?

**Comment by phil235** [comment] 2015-08-25 10:01
duplicate of #9631

**Closed by phil235** 2015-08-25 10:01 UTC
