### ISSUE TITLE
Nuke op shuttle is deconstructable

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#14771] opened 2016-01-21 06:51 UTC
What it says on the tin. It also effects all the other shuttle tiles, but it's mainly a concern for nuke ops because their ship was designed to safely hold the nuke.

Now every 2nd nuke op round some memester just welds a wall and spaced the nuke, which is seriously fucking gay for literally everyone involved.

**Comment by Shadowlight213** [comment] 2016-01-21 07:25
This is almost certainly a dupe.
I think in the last discussion in it it was deemed that the turrets were enough of a defense or something. Which is silly, considering there's a blindspot on te back. Remaining arguments was "Nuke ops shouldn't leave the nuke unattended" or something like that.

**Comment by WJohn** [comment] 2016-01-21 11:34
Dupe of #10520

**Closed by WJohn** 2016-01-21 11:34 UTC
