### ISSUE TITLE
Simple Mob Clowns Grow Hair On Death

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10943] opened 2015-07-31 00:34 UTC
When they die, they suddenly grow hair, which is really noticeable when it's a big beard or long hair.

Probably because of the transition from Simple Mob to a Human Mob.

**Comment by RemieRichards** [comment] 2015-07-31 00:37
not probably, entirely because of it.

**Comment by Niknakflak** [comment] 2015-07-31 02:13
This is a very interesting bug

**Comment by RemieRichards** [comment] 2015-07-31 02:21
"s not a bug. 
Simple animals dont have human hair sprites.
A human corpse does.

**Comment by Ikarrus** [comment] 2015-07-31 02:22
Technically it makes sense, but from players' point of view you have dead clowns growing hair.

**Comment by WJohn** [comment] 2015-07-31 03:24
Maybe just make it so these clowns/syndies are all bald and shaved when spawned?

**Comment by freerealestate** [comment] 2015-08-03 03:58
replace human simple mobs with snpcs

**Comment by WJohn** [comment] 2015-08-03 10:20
God no.

**Comment by freerealestate** [comment] 2015-08-03 10:29
Is their AI somehow worse than that of simple_animals? Like, genuine question. The only problem I have with them is the dumb shit they spout, but that could be changed based on what type of mob is it.

It'd make them stunnable, and have all the other characteristics you'd expect from a human mob that simple mobs lack (like hair).

**Comment by Firecage** [comment] 2015-08-03 18:11
Free, until Sawu MAYBE one day ports over SNPC's 2.0 from Dragonball, fuck no. Current SNPC's aren't good at all, but I don't feel like ranting about it in this issue. You can ask someone on Coderbus why they are bad.

**Comment by freerealestate** [comment] 2015-08-03 18:16
But they could be improved to fit the purpose though, and they really can't
be that much worse than simple mobs, which are pretty terrible generally.

**Comment by Firecage** [comment] 2015-08-03 18:18
Fine. If you want a horribly bugged mob to replace human simple animals. Go ahead.

**Comment by freerealestate** [comment] 2015-08-03 18:20
I dunno who's fixing this bug but I assume they'll just make the clown mobs
bald on death.

**Comment by Firecage** [comment] 2015-08-03 18:20
Unfortunately that would be the best option.

**Comment by Miauw62** [comment] 2015-08-03 19:05
i really think that would be the best option, yeah.

SNPCs are hilarously derpy and are great for the simple reason that they are fucking hilariously broken.

**Comment by Dorsisdwarf** [comment] 2015-08-27 13:36
Dupe of #4360

**Closed by Dorsisdwarf** 2015-08-27 13:36 UTC
Labels: Consistency Issue, Not a bug
