### ISSUE TITLE
box upload turrets bugged

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12733] opened 2015-10-29 20:25 UTC
The turrets are still shooting at people regardless if they are actually on or not.
I watched and tested it a couple times where the captain would turn off the turrets in the upload and they still shot and functioned.  This happened on box station as far as I know only, I have no idea about the other maps or if it's universal.

**Comment by WJohn** [comment] 2015-10-29 22:35
Yeah I noticed this a few days ago, not sure what's causing it. Maybe the area names no longer being improper? I dunno.

**Comment by tkdrg** [comment] 2015-10-30 01:51
Turrets are no longer area based so that shouldn't be the case.

**Comment by Jordie0608** [comment] 2015-10-30 03:38
Dupe of #12634

**Closed by Jordie0608** 2015-10-30 03:38 UTC
