### ISSUE TITLE
Instruments BPM and playback seem to be broken

### ISSUE THREAD

**Issue by HanzKetchup** [tgstation/-tg-station#9312] opened 2015-05-03 15:10 UTC
Both servers on pianos, guitars, and violins. No matter what tempo the song is set to be, it will be set to 222, and hitting the play button will make it look like it's working but no sound will come out. This has been going on for several weeks now and with the addition of guitars I think it's time to report it.

**Comment by stapler2025** [comment] 2015-05-03 16:32
BPM is stupid because it tries to compensate for lag.  (600 / tempo) where tempo = world.tick_lag w/e.

Playback is "broken" because you can disable instrument sounds now, and they start disabled by default for some shitty reason.  Go to your preferences tab and enable the sounds.

**Comment by Boggart** [comment] 2015-05-03 17:39
Duplicate of #9248, but yeah the bpm is rounded on importing.

**Comment by Supermichael777** [comment] 2015-05-03 17:49
Aparently intentonal

**Comment by Jordie0608** [comment] 2015-05-04 08:13
Duplicate

**Closed by Jordie0608** 2015-05-04 08:13 UTC
