### ISSUE TITLE
Recent maint remap broke powernets

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#10959] opened 2015-07-31 19:57 UTC
http://i.imgur.com/DIAx64B.png

@Dorsisdwarf

**Comment by Boredone** [comment] 2015-07-31 20:27
Incase it isn't noticed, assuming he didn't remove the disposal pipe in the screenshot for some reason, the disposal pipe is also missing there.

**Comment by xxalpha** [comment] 2015-07-31 22:45
@Steelpoint if you can squeeze this in your PR.

**Comment by daman997** [comment] 2015-07-31 23:05
this shit is so annoying

**Comment by Jordie0608** [comment] 2015-08-01 03:19
Duplicate of #10863

**Closed by Jordie0608** 2015-08-01 03:19 UTC
Labels: Bug, Map Issue, Priority: High
