### ISSUE TITLE
Rogue air meter in box maint

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12187] opened 2015-10-06 04:56 UTC
Looks like this was forgotten about in the repiping
![image](http://puu.sh/kAda7/7d152ef711.jpg)

**Comment by duncathan** [comment] 2015-10-06 05:01
This is a dupe of something

**Comment by WJohn** [comment] 2015-10-06 05:30
Dupe of #12120 
Will fix after the current map edit PRs are merged or closed, waitin' on steelpoint for that.

**Closed by WJohn** 2015-10-06 05:30 UTC
