### ISSUE TITLE
Oculine doesn't work

### ISSUE THREAD

**Issue by Cookiesndip** [tgstation/-tg-station#10084] opened 2015-06-21 21:12 UTC
I tried fixing a screwdrivered patient in medbay with oculine in both pill and patch form to no avail. I even tried squirting oculine in his eye, and, despite having 60 units in his system for several minutes, no change was observed.

**Comment by Iamgoofball** [comment] 2015-06-21 21:15
fucking eye code

@phil235 did you touch eye code at all doing the life rewrite? i'm not certain how it works anymore

**Comment by bgobandit** [comment] 2015-06-21 21:34
dupe https://github.com/tgstation/-tg-station/issues/9707

**Comment by Lumipharon** [comment] 2015-06-21 23:36
If you take enough eye damage, it gives you (or at least, used to) GENETIC blindness. Shit's retarded man.

**Comment by Boggart** [comment] 2015-06-21 23:38
If I remember correctly eye_stat isn't touched by occuline, only eye surgery. I don't know if that's intentional or accidental. (Eye_stat is the damage type caused by welding and I'd assume screwdrivers to the eye, etc.)

**Comment by Iamgoofball** [comment] 2015-06-21 23:47
thats retarded, it should heal all

**Comment by optimumtact** [comment] 2015-06-22 00:57
Yes goof it is retarded.

**Comment by WJohn** [comment] 2015-06-22 04:38
Closing since it's a dupe.

**Closed by WJohn** 2015-06-22 04:38 UTC

**Comment by optimumtact** [comment] 2015-06-22 05:37
of?

**Comment by optimumtact** [comment] 2015-06-22 05:37
nvm saw bandit's comment
