### ISSUE TITLE
Bluespace Electricity

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9903] opened 2015-06-11 15:07 UTC
I found the White Ship, used it to loot Derelict, built a SMES in the cockpit of the White Ship, wired the cables from the SMES to Arrivals in main station, flew the ship to Derelict and Deep space only to find that the SMES is still fully working with the station main grid. When in Deep Space/Derelict, I cut a cable from the SMES and it still worked as if it was linked to Station powernet. Several admins also came to check out but singularity interrupted any further science.

**Comment by RemieRichards** [comment] 2015-06-11 15:09
Shuttle transit clearly isn't disconnecting wires from their powernets (I'd hedge a bet the same is true for pipes and their pipelines)

**Comment by Razharas** [comment] 2015-06-11 15:47
Wires dont expect to be ever moved, they are expected to break into items in case something tried to pull them
So its expected that when they are teleported nothing happens, just need to add rebuilding to their Move()
Pipes are expected to be moved however so i hope they actully rebuild their network on the shuttle move alright

**Comment by Anonus** [comment] 2015-06-11 17:27
Pipes aren't expecting to move either.

**Comment by Razharas** [comment] 2015-06-12 00:41
Singulo pulling pipes doesnt destroy them(at least i remember it that way), just moves

**Comment by Lumipharon** [comment] 2015-06-12 00:58
moving ships creates a few wierd things that I've noticed.

1: Disposal pipes don't move with the ship, they just break.
2: Cameras on the ships break if they move BACK to a place the ship has been before.

**Comment by Dorsisdwarf** [comment] 2015-08-13 11:31
Now a dupe of master issue #11183.

**Closed by Dorsisdwarf** 2015-08-13 11:31 UTC
Labels: Bug
