### ISSUE TITLE
AI Holograms get affected by Zero-G

### ISSUE THREAD

**Issue by Summoners** [tgstation/-tg-station#9317] opened 2015-05-03 19:03 UTC
It's just a visual bug, the AI is still where the hologram should be but the hologram floats away. Absolutely amazing to use a hologram in escape and watch the hologram float down the main hallway.

Quite a minor visual bug, but still reporting it.

**Comment by palpatine213** [comment] 2015-05-05 15:51
Dupe of #6109

**Closed** 2015-05-06 10:20 UTC
Labels: Bug, Sprites
