### ISSUE TITLE
Janicart issues

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#11234] opened 2015-08-16 12:56 UTC
The janicart has some minor issues currently.

1. Even when riding it, you can slip on wet floors, banana's, etc.

2. When you are on the janicart, you can't change use the change reagent amount thing on, for example, buckets, watertanks, beakers, etc.

**Comment by phil235** [comment] 2015-08-16 13:22
1. is a duplicate of an older issue.

2. is linked to the object verb having a usr.canmove check which prevents using it while buckled.

**Comment by PKPenguin321** [comment] 2015-08-16 18:45
i think for number 1, couldn't you just wear galoshes
it wouldn't matter anyways since the slowdown gets negated by being on the cart

**Comment by Firecage** [comment] 2015-08-16 22:12
PK, it still shouldn't slip you, since you are riding with your feet of the ground, not walking.

**Comment by Cebasiz** [comment] 2015-08-16 22:44
complicated janicart water drifting model when

**Comment by phil235** [comment] 2015-10-11 18:20
1. has already been fixed in another PR.

and 2. will be fixed by 12323

**Closed** 2015-10-13 22:08 UTC
Labels: Balance, Bug
