### ISSUE TITLE
bio bags don't work 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14316] opened 2016-01-03 00:57 UTC
they don't pick up things en masse

@bgobandit this is your's I think

**Comment by PKPenguin321** [comment] 2016-01-03 00:59
probably a dupe of https://github.com/tgstation/-tg-station/issues/13116

**Comment by Bawhoppen** [comment] 2016-01-03 01:02
a dupe of a dupe? whoa

**Comment by PKPenguin321** [comment] 2016-01-03 01:02
yeah this issue keeps getting reported but never fixed

**Comment by Bawhoppen** [comment] 2016-01-03 01:03
fucking bgo

**Closed** 2016-01-03 01:29 UTC
