### ISSUE TITLE
Nar-sie is making normal floor tiles instead of cult floor tiles.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#11557] opened 2015-09-03 01:49 UTC
Old god is losing it in his old age and forgot what kind of tile to lay down.

**Comment by WJohn** [comment] 2015-09-03 01:52
Misclicks, whoops!

**Comment by xxalpha** [comment] 2015-09-03 04:08
Dupe? This is a known bug.

**Comment by duncathan** [comment] 2015-09-03 06:24
Yeah I'm almost certain this is a dupe

**Comment by CosmicScientist** [comment] 2015-09-03 12:26
Because no-one else went to prove it's a dupe (it takes five seconds with the search box): #10180

**Comment by Dorsisdwarf** [comment] 2015-09-04 05:54
Closed, dupe of #10180

**Closed** 2015-09-04 05:55 UTC
Labels: Bug
