### ISSUE TITLE
Deck of cards issues

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#2189] opened 2013-12-30 15:54 UTC
- Hands of cards all have the same cards shown in their sprites regardless of what cards are actually in them (don't know if this can be fixed)
- Holding individual cards in each hand (as opposed to as a hand of cards) shows what cards they are on examine (don't know if this can be fixed)
- Prone people can draw from hands of cards (the cards just fall underneath them so it's useless)
- You can't display cards on a table by placing them on the same tile as they stack directly on top of each other. This means in blackjack for example you need to take up two table spaces to display your cards face up. Or I guess you can hand your blackjack hand to the dealer. It means the other players can't see what you have unless they pick the hand up themselves however. Someone in the original pull request mentioned giving the placed cards the pixel offset of the cursor when placed. This would mean you could click different areas of the same tile to place the cards where they'll be readable. This is more of a feature request than a bug report, but it is regarding something that affects the functionality of the object.

**Comment by phil235** [comment] 2015-04-25 21:16
The last point of this issue has been fixed by Remie's pixel click parameter.

**Comment by RemieRichards** [comment] 2015-04-25 21:17
Oh that is true actually!

**Comment by xxalpha** [comment] 2015-05-17 23:13
This is pretty much fixed unless there's expectations of someone fixing the first point.

**Comment by phil235** [comment] 2015-07-17 16:09
IPoint 3 and 4 are fixed. The first two points aren't bug so I'm changing the tag.

**Comment by Dorsisdwarf** [comment] 2015-11-04 14:02
Closed for old not a bug that nobody will ever ever implement

**Closed by Dorsisdwarf** 2015-11-04 14:02 UTC
Labels: Not a bug, Usability
