### ISSUE TITLE
AI holograms based on crew members don't change direction.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#7249] opened 2015-01-21 10:10 UTC
If you choose to have a hologram based on a crew member when you move it around, it's facing direction doesn't change. It always faces south.

None of the other hologram types do this, they change direction as they should.

**Comment by RemieRichards** [comment] 2015-01-21 10:12
This is a known issue but I'm not sure if it's been reported. I looked into it once, and couldn't find a reason why it's broken, it's been broken for *quite* some time.

**Comment by Miauw62** [comment] 2015-01-21 14:36
AFAIK, this is not a dupe.

**Comment by GunHog** [comment] 2015-01-21 15:36
What about the use of getFlatIcon()? Would that not cause a loss of dir?

**Comment by RemieRichards** [comment] 2015-01-21 15:42
@GunHog getFlatIcon() was used when this still worked, getFlatIcon() now includes a direction argument (South) which YotaXP added when he improved it, but that's not the cause, I did lots of tests on changing that, not to mention some of these holograms start off facing E/W/N which are not South obviously.

**Comment by phil235** [comment] 2015-10-11 16:50
Tested it and it seemed to work fine now. Closing.

**Closed by phil235** 2015-10-11 16:50 UTC
Labels: Bug, Sprites
