### ISSUE TITLE
Derelict windows

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12593] opened 2015-10-22 18:09 UTC
This might be a dupe and its quite an old bug that many people know about, but on the derelict there are some windows where you're able to walk through. 
Typically not ones that face space but are inside the structure itself.

**Comment by Shadowlight213** [comment] 2015-10-22 18:13
This is definitely a dupe. The bug is caused by the derelict using the old window system or something.

**Comment by Bawhoppen** [comment] 2015-10-22 18:21
I honestly don't know why it hasn't been fixed then considering there are windows that work correctly.

**Comment by Jordie0608** [comment] 2015-10-22 18:21
Dupe of #12391

**Closed by Jordie0608** 2015-10-22 18:21 UTC
