### ISSUE TITLE
Prying up floor tiles makes them airless.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14642] opened 2016-01-16 00:52 UTC
What it says on the tin. Kind of high priority!

**Comment by YotaXP** [comment] 2016-01-16 00:56
Duppers #14633

**Comment by duncathan** [comment] 2016-01-16 16:35
Can't reproduce on master; this was an issue with listmos that was fixed before it was merged

**Closed by duncathan** 2016-01-16 16:35 UTC
Labels: Atmos, Bug, Priority: High
