### ISSUE TITLE
Replica Pod is Broken (Hydroponics)

### ISSUE THREAD

**Issue by kalevader** [tgstation/-tg-station#8721] opened 2015-04-03 16:19 UTC
Problem Description: 

When attempting to revive a player via using a replica pod, it is impossible to harvest the pod. The plant grows fully, the green marker activates, stating it is ready to harvest. However no interaction allows for harvesting the pod. I have attempted this multiple times and it cannot be harvested with player blood injected and without. (Without being in an attempt to gain further seeds)

What did you expect to happen:

I expected to be able to harvest the plant. An administrator was online at the time (I don't recall the administrators name) and he admin-magicked the dead player I was trying to revive back to life after it was evident it was broken.

What happened instead: 

No interaction message was received from clicking the plant to harvest. It was not harvested. The player was not revived, no seeds were returned. Eventually the plant died.

Why is this bad/What are the consequences: 

It breaks a strong feature of the job role, Botanist.

Steps to reproduce the problem: 
1. Plant some replica pod seeds in a Hydroponics tray.
2. Maintain the plant until full growth is reached.
3. Attempt to harvest.

Server: Sybil

Revision: 
Server revision compiled on: 2015-04-02
06f09b707f3c997d5ade135540a937bc941ece40 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Protect Assistant From Antagonist: 0

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): 

I have tested this during multiple rounds, at multiple different periods. It appears gamemode independent.

**Comment by Incoming5643** [comment] 2015-04-03 16:33
I've seen it work fairly recently.

Are you sure you injected blood into the seed pack? Injecting it to the plant once its growing doesn't count.

Are you sure the person was dead and available at the time? If he took control of another mob or wasn't dead it doesn't work.

Are you sure the blood sample was clean? If it's mixed with anything else, including someone elses blood, it doesn't work.

**Comment by kalevader** [comment] 2015-04-03 16:39
My steps were as follows:

1. Chef volunteered to be replicated as his body was damaged.
2. I drew blood from his dead body
3. I injected it into seed pack
4. I planted seed pack into hydro tray
5. Maintained and waited for full growth.

Also, as far as I am aware it is possible to receive two seeds if no blood is injected at full growth according to the wiki, neither situations allow for harvest.

I have tested it as of 10 minutes ago.

**Comment by Lumipharon** [comment] 2015-04-03 21:27
I was there at the time. Both plants were fully mature but couldn't be harvested, shit was gay.

**Comment by Jordie0608** [comment] 2015-04-04 04:28
Dupe of #8243, closing that because this has actual information

**Comment by hanshansenhansson** [comment] 2015-04-04 10:46
Can confirm, happened to me yesterday. As traitor, stole the blood from an executed traitor and tried to pod him. Plant did grow, green lights blinked, could not harvest.

Usually if the guy who is to be podded is not cloneable for some reason, you would at least get a seed pack when harvesting, but this time I had to watch the plant die.

**Closed** 2015-04-27 15:02 UTC
Labels: Bug, Priority: High
