### ISSUE TITLE
Cig vending machines don't have any cigars/robust gold packs

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#8525] opened 2015-03-24 22:11 UTC
It's unacceptable.

**Comment by Xhuis** [comment] 2015-03-24 22:15
did you put a coin in them?
also if my cigar cases pr ever gets merged this won't be an issue

**Comment by Lumbermancer** [comment] 2015-03-24 22:27
Yes of course I put the coin in.

**Comment by Xhuis** [comment] 2015-03-24 22:38
guess it's just a bug then

**Comment by stapler2025** [comment] 2015-03-25 00:02
https://github.com/tgstation/-tg-station/pull/8436

**Comment by phil235** [comment] 2015-03-25 00:43
duplicate of #8469

**Closed by phil235** 2015-03-25 00:43 UTC
