### ISSUE TITLE
Jump to area verb is missing areas

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12684] opened 2015-10-27 07:07 UTC
e.g. Cargo Bay, Cargo Office, Prison Wing

**Comment by xxalpha** [comment] 2015-10-27 10:36
Update your local before you report bugs.

**Comment by MrStonedOne** [comment] 2015-10-27 13:22
this is a byond bug. downgrade to 1305 or below or wait until 1311

**Comment by xxalpha** [comment] 2015-10-27 13:35
It's a bug that was fixed by #12479

**Comment by MrStonedOne** [comment] 2015-10-27 21:03
Nope.

It's a bug in byond caused by 1305, fixed in 1309, but breaks something else that will get fixed in 1311.

**Comment by freerealestate** [comment] 2015-10-28 04:34
>Update your local before you report bugs.

did i bang your wife, officer?
i keep catching you following me around the repo, looking for excuses to cite me
i apologise, if i'd known she was yours i'd have taken the back route

**Comment by neersighted** [comment] 2015-12-01 15:57
@MrStonedOne is this one fixed?

**Comment by tkdrg** [comment] 2015-12-16 15:20
fixed in 509

**Closed by tkdrg** 2015-12-16 15:20 UTC
Labels: Bug, BYOND 509, BYOND Issue, Needs Reproducing/Testing
