### ISSUE TITLE
Mopping finish message is broken

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9297] opened 2015-05-02 23:33 UTC
![span](https://cloud.githubusercontent.com/assets/5659269/7443110/276cb5a0-f102-11e4-9670-a3cddbd26f5d.png)

Done on Sybil at the time of creation.

**Comment by phil235** [comment] 2015-05-02 23:51
duplicate of #9201

**Closed by phil235** 2015-05-02 23:51 UTC
