### ISSUE TITLE
Spraying burning items and structures with water doesnt put out the fire.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14106] opened 2015-12-27 23:42 UTC

**Comment by Jalleo** [comment] 2015-12-27 23:44
There is a thing called burn stacks look up the code for it to see how it works and what your exact issue is

**Comment by Zilenan91** [comment] 2015-12-28 00:29
Works with fire extinguishers but not actual water itself. Water out of sprayers aren't supposed to put fires out. Close this please.

**Comment by WJohn** [comment] 2015-12-28 00:33
I find this to be more a consistency issue, even if its not a bug. Worth a discussion I guess.

**Comment by KazeEspada** [comment] 2015-12-28 01:40
I mean the fire extinguisher didn't put them out.

**Comment by newfren** [comment] 2015-12-28 02:13
You know how when fire fighters spray water at a fire and it doesn't instantly go out because there's too much fire?

Same principle.

**Comment by KazeEspada** [comment] 2015-12-28 02:23
There was no fire in the entire room except for a few burning tables and I unleased an entire extinguisher of water at it.

**Comment by optimumtact** [comment] 2015-12-29 21:14
They probably had a stupidly high firestack thanks to a bug or a stupid chemical or something

**Closed** 2016-01-02 16:53 UTC
Labels: Balance, Consistency Issue, Not a bug
