### ISSUE TITLE
Solars aren't spawning on Dreamstation

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#17254] opened 2016-04-29 20:46 UTC
1. Load dream station

2. Look below chapel at solars

3. Plating is gone, just floating wiring.

**Comment by PKPenguin321** [comment] 2016-04-29 20:50
Pretty sure this is a dupe

**Comment by ChangelingRain** [comment] 2016-04-29 21:00
This is happening to all the southwest solars so uh
also dupe of #17145

**Closed by ChangelingRain** 2016-04-29 21:00 UTC
