### ISSUE TITLE
The tile on the bomb test range to keep bombs from flying into space gets destroyed by bombs

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10189] opened 2015-06-26 17:16 UTC
So if you fling a second bomb onto the test range, it'll fly off into space and probably ruin something you didn't want ruined.

**Comment by Incoming5643** [comment] 2015-06-26 17:55
Fun game: set a proxy sensor on a max cap bomb and throw it on a diagonal into space and see how quickly you get contacted by admins.

**Comment by WJohn** [comment] 2015-06-26 19:03
This could probably be "fixed" with simply having a very thick layer of R walls on the test site, since explosions are now blocked by walls. This'd give it some re-usability.

**Comment by Dorsisdwarf** [comment] 2015-06-27 00:00
Didnt unsim turfs get removed?

**Comment by WJohn** [comment] 2015-06-27 00:16
Yes, and now this and a few other things that relied on unsimulated turfs are acting up weirdly.

**Comment by MrStonedOne** [comment] 2015-06-27 03:08
either make those tiles have super high explosion resistance (its a var) or make them be the /turf/undestructable type

**Comment by Dorsisdwarf** [comment] 2015-07-01 08:43
Anonus, if you're gonna change the title, at least acknowledge that the problem isnt an unsim turf getting destroyed, it's a sim turf not being boomproof

**Comment by Shadowlight213** [comment] 2015-07-18 01:33
Bump
High priority. Test site is basically useless after 1 bomb now

**Comment by Dorsisdwarf** [comment] 2015-08-05 08:28
fixed in #10723

**Closed by Dorsisdwarf** 2015-08-05 08:28 UTC
Labels: Map Issue, Not a bug
