### ISSUE TITLE
Disconnecting for a few seconds shouldn't end the round in rev/other-game-modes-that-use-this-metric

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#17452] opened 2016-05-07 17:05 UTC
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

See title.

The server's network connection having a 3 second hiccup shouldn't spell the end of the round.

@Incoming5643

**Comment by PKPenguin321** [comment] 2016-05-07 20:25
Dupe of one of my issues

**Comment by ChangelingRain** [comment] 2016-05-07 21:03
Duplicate of #15159

**Closed by ChangelingRain** 2016-05-07 21:03 UTC
