### ISSUE TITLE
Overlay rendering issue

### ISSUE THREAD

**Issue by Stevepelcz** [tgstation/-tg-station#3225] opened 2014-03-29 03:34 UTC
Not sure what the technical terminology would be, but upon trying to play today I encounter the issue pictured.

Basically byond isn't rendering transparency or gradients on overlays. Also stretch to fit appears much 'fuzzier' than usual. Upon asking chat about it, some people said that was how the game always looked for them.

**Comment by MrPerson** [comment] 2015-04-11 11:32
Without the screenshot in OP's picture I don't even know what the problem is at this point

**Comment by Miauw62** [comment] 2015-04-11 20:06
fairly sure this is a software mode issue.

**Comment by Aranclanos** [comment] 2015-04-13 12:13
this issue will have a year old, just close it.

**Closed** 2015-04-13 12:47 UTC
Labels: Bug, BYOND Issue, Sprites, Unresolvable
