### ISSUE TITLE
Temperature gun

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#11017] opened 2015-08-04 15:47 UTC
Double e-swords do not deflect the shots from temperature guns, not sure if this is a mistake or just over looked, but a temperature gun shoots out /bolts/ of temperature, not balls of gas that change the temperature.

Was a traitor and got killed by a sec officer with a temperature gun by shooting cold shots, while I was wielding a double energy sword

>Was also told it maybe a bug so I brought it here, if it isn't then don't slap me ;-;

**Comment by SconesC** [comment] 2015-08-04 18:11
>he got killed by a temp gun

**Comment by PKPenguin321** [comment] 2015-08-04 18:16
how did you get killed by a temp gun

**Comment by phil235** [comment] 2015-08-04 18:28
That's because you can only deflect projectiles that are child of either projectile/energy or projectile/beam (https://github.com/tgstation/-tg-station/blob/a825eb02e85de7ef4fc5c1807c1f84c2ec6ab99e/code/modules/mob/living/carbon/human/human_defense.dm#L45).
 Temperature gun projectile is obj/item/projectile/temp

**Comment by Firecage** [comment] 2015-08-04 18:43
....How the fuck did you get killed by a temperature gun.

**Comment by Marflowerose** [comment] 2015-08-04 19:04
I think we need a new gittag for this momentous occasion, or at least a spam of all the colorful ones. Are you sure you weren't nude in space while someone happened to be shooting a temperature gun at your general direction and died to the exposure rather than temperature gun?

**Comment by Stickymayhem** [comment] 2015-08-04 19:16
>Trying to reflect the laws of thermodynamics
>Wanting to nerf the literal weakest ranged weapon in the game.

Oh my god Sirnat any shreds of doubt I had about treating you like shit have completely evaporated

**Comment by Ausops** [comment] 2015-08-04 19:16
>OOC: Marflow: I've seen several Restart votes go through but never even heard of death caused by temperature gun

**Comment by sirnat** [comment] 2015-08-04 21:25
Im so confused, should I take that as a compliment sticky? xD

**Comment by sirnat** [comment] 2015-08-04 21:27
I didnt die from the gun its self, I died from being shot with it/slowed down and outright fucked by a baton. But I still had the e-sword deployed and held.     But the gun is the reason I was fucked/killed

**Comment by Lumipharon** [comment] 2015-08-04 21:56
World first.
Temp gun confirmed new meta.

**Comment by Summoners** [comment] 2015-08-04 22:33
Tempgun is blocked by a dual esword, I tested it. I have no idea how you even died to it, it hardly even slows you. I had to have two temp guns and have two rechargers and I emptied at-least  7 full clips to even down the guy.

Also it's almost impossible to hit anyone with a dual esword with the temp gun, it's blockrate is extreme.

**Comment by sirnat** [comment] 2015-08-04 22:39
I had the dual e-sword deployed, it didnt block any of the cold shots the guy sent toward me

**Comment by Summoners** [comment] 2015-08-04 23:00
@sirnat I just tested it on both servers, about 90% of the shots were blocked. It never deflected, only blocked.

**Comment by sirnat** [comment] 2015-08-04 23:06
Hm.. Wierd, all of his shots hit, okay well I guess this can be closed then? Sorry if it was a waste of time

**Comment by Marflowerose** [comment] 2015-08-04 23:34
Was it actually a disabler? I'm not sure if they penetrate the blocking, that could be it, they do stamina damage which slows you and eventually puts you on the ground.

**Comment by TheVekter** [comment] 2015-08-10 04:00
HE -DIED TO A TEMP GUN-

**Comment by PKPenguin321** [comment] 2015-08-27 04:31
reminder that this guy died to a temp gun

**Comment by Iamgoofball** [comment] 2015-08-27 04:45
# HOW DO YOU DIE TO THE MOST USELESS GUN IN THE GAME

**Comment by TheVekter** [comment] 2015-08-27 04:46
HE  DIED  TO  A  TEMP  GUN

**Comment by Dorsisdwarf** [comment] 2015-08-27 08:10
Closed by request, get good, etcetera

**Closed by Dorsisdwarf** 2015-08-27 08:10 UTC
Labels: Balance, Bug, Edge case, FUCK

**Comment by PKPenguin321** [comment] 2016-01-22 23:50
never forget

**Comment by duncathan** [comment] 2016-03-01 13:08
;_;7

**Comment by Iamgoofball** [comment] 2016-03-12 20:12
press ;_;7 to pay respects

**Comment by PKPenguin321** [comment] 2016-03-12 20:19
;_;7

**Comment by PKPenguin321** [comment] 2016-08-11 03:25
about six days ago was the one year anniversary of theonly time somebody died to a temp gun never forget o7

**Comment by Iamgoofball** [comment] 2016-08-11 04:02
F

**Comment by francinum** [comment] 2016-08-11 06:36
Never 4get

**Comment by Iamgoofball** [comment] 2016-08-11 07:34
8/11

**Comment by Marflowerose** [comment] 2016-08-11 09:31
;_;7

**Comment by yackemflam** [comment] 2016-08-11 11:03
;_;7

**Comment by sirnat** [comment] 2016-08-12 03:06
F-Fuck you guys xD

**Comment by optimumtact** [comment] 2016-11-10 07:12
literally died to a temp gun

**Comment by PKPenguin321** [comment] 2016-11-10 08:29
Really makes you think

**Comment by Militaires** [comment] 2017-01-23 12:11
new year new temp gun

**Comment by Marflowerose** [comment] 2017-04-15 03:29
Member to pray respects to temp gun death on easter ;_;7

**Comment by PKPenguin321** [comment] 2017-04-15 03:35
Will temp gun ever be not useless

**Comment by duncathan** [comment] 2017-04-15 06:06
at this point it's best that we never let it be useful

**Comment by kevinz000** [comment] 2017-09-03 16:10
temp gun is my carry weapon as security now

**Comment by Stickymayhem** [comment] 2017-09-03 19:40
Same

**Comment by sirnat** [comment] 2017-09-04 17:21
The headmin to remove the tempgun gets my vote.

**Comment by Shadowlight213** [comment] 2017-09-13 14:30
Tfw you add temp gun to sec a joke and its actually useful.
Did not see that coming tbh.

**Comment by Marflowerose** [comment] 2017-12-23 01:29
Christmas is the time to spend with loved ones and to remember the sacrifice baby sirnat made for us, never forgetti that he died to a temp gun for our sins.

**Comment by Armhulen** [comment] 2017-12-23 01:40
:)

**Comment by sirnat** [comment] 2017-12-23 06:29
Im so happy you all still remember my downfall. :(

**Comment by optimumtact** [comment] 2018-01-07 12:02
guys this guy died in 2015 to a temp gun

**Comment by ike709** [comment] 2018-01-07 13:16
new year new temp gun

**Comment by Bawhoppen** [comment] 2018-01-08 11:40
![happynewtempgun](https://user-images.githubusercontent.com/6510293/34669268-705ae1d0-f436-11e7-88cd-cc650e1ab9bd.png)

**Comment by sirnat** [comment] 2018-01-08 14:35
That is my new forum profile picture.

**Comment by kevinz000** [comment] 2018-03-29 04:20
lmao

**Comment by duncathan** [comment] 2018-03-29 12:03
good times

**Comment by The-Driker** [comment] 2018-12-12 16:09
Imsxz was also recently killed with a temp gun. I feel like we should consider this a gift going into 2019.

**Comment by optimumtact** [comment] 2019-01-19 22:40
yo he died in 2015 to a temp gun

**Comment by Anonmare** [comment] 2019-01-19 22:40
HE 
DIED
TO
A
TEMPGUN
:rofl:

**Comment by nicbn** [comment] 2019-04-11 03:50
Hm
 Looks like temp gun needs a nerf

**Comment by PKPenguin321** [comment] 2019-04-11 17:12
❄️ 🔫

**Comment by Bawhoppen** [comment] 2019-04-11 23:00
We need to do a quick port of https://github.com/AnimusWhite/NTstation13/pull/14 for good measure.

**Comment by sirnat** [comment] 2019-07-31 07:27
We're almost there boys for the 4 year anniversary!

**Comment by Bawhoppen** [comment] 2020-01-01 04:07
As a decade of chaos, fear, and division, yet also progress, strength, and devotion, finally draws to a close... I think we can take a step back and look at one common thing which united us all in a common bond: the temperature gun. 
High hopes for the new decade everyone! :tada:

**Comment by sirnat** [comment] 2020-01-01 04:08
Ahh I love ol TG I hope you all had a good 2019.

**Comment by Anonmare** [comment] 2020-01-01 14:27
Yo is this the dude who ded to a temp gun on stream?

**Comment by The-Driker** [comment] 2020-01-01 14:38
I welcome the new decade of the temp gun.

**Comment by loserXD** [comment] 2020-01-01 18:35
he died

**Comment by notfrying1pans** [comment] 2021-01-03 13:18
hey its 2021 time for a yearly reminder that you died to a temp gun

**Comment by duncathan** [comment] 2021-03-26 11:43
he really did die to a temp gun huh

**Comment by sirnat** [comment] 2021-06-28 03:26
It be 2021, and I still have nightmares about dying to a temp gun in ss13

**Comment by optimumtact** [comment] 2021-06-28 04:32
o7

**Comment by LemonInTheDark** [comment] 2021-06-28 04:36
Subscribed

**Comment by Kylerace** [comment] 2021-06-28 05:07
astonishing

**Comment by PKPenguin321** [comment] 2021-06-28 06:04
unbelievable... all the gun does is lower your temperature by like 1 degree per shot bro... you died to that fr❓❗

**Comment by optimumtact** [comment] 2021-06-28 06:45
it slows you down

**Comment by Iamgoofball** [comment] 2021-06-28 12:31
died to a temp gun in 2015, RIP

**Comment by Anonmare** [comment] 2021-06-28 22:38
I have only returned purely to ask: Did you really die to a temp gun?

**Comment by Iamgoofball** [comment] 2021-06-29 14:51
they did, ya

**Comment by sirnat** [comment] 2021-06-30 00:51
I died bc the temp gun slowed me down massively when i had a double e sword out and it was supposed to block 100 energy projectiles. 

I was a retard back when i played then.

**Comment by Bawhoppen** [comment] 2021-07-02 01:53
https://github.com/tgstation/tgstation/pull/59949

**Comment by Fikou** [comment] 2021-07-02 07:25
he died to a temp gun

**Comment by MrDoomBringer** [comment] 2021-07-02 09:04
this guy's health variable somehow got set to 0 after someone used the temp gun on the same server as him, what an odd bug - wonder what the interactions at play here are

**Comment by Shadowflame909** [comment] 2021-07-03 17:23
Dont use the temp gun in space bro. Nukies will fear

**Comment by Rhials** [comment] 2021-08-23 15:57
Unironically died to a temp gun

**Comment by notfrying1pans** [comment] 2021-12-31 20:48
It's 2022 tomorrow, remember that this person died to a temp gun

**Comment by Mothblocks** [comment] 2022-02-08 23:30
greetings from 2022! this guy died to a temp gun

**Comment by Iamgoofball** [comment] 2022-02-08 23:44
i come back to this issue every year to think of the before times when someone died to a temp gun in ss13

**Comment by nicbn** [comment] 2022-02-09 01:26
Once again blessed by the e-mail notification for the issue about a guy dying to a temp gun seven years ago

**Comment by Lumipharon** [comment] 2022-02-09 02:47
![index](https://user-images.githubusercontent.com/7869430/153112400-3149adc2-6504-4d0b-9fd1-1c75d1cd1608.jpg)

**Comment by PKPenguin321** [comment] 2022-02-09 03:16
take me back. take me back

**Comment by notfrying1pans** [comment] 2022-02-09 17:22
Lol

**Comment by duncathan** [comment] 2022-02-09 18:54
oh my god it's been 7 years

**Comment by TheBonded** [comment] 2022-02-11 21:10
amazing

**Comment by anclandor** [comment] 2022-02-12 03:54
With thermal pistols I foresee many people falling to a tempgun in 2022.  EVEN IF THEY HAVE DESWORDS.  Massive bug abuse.

**Comment by Stickymayhem** [comment] 2022-02-13 13:02
This is just a list of the boomers now isn't it

**Comment by Bawhoppen** [comment] 2022-02-13 21:07
@Stickymayhem 
> This is just a list of the boomers now isn't it

Yes
I 'member it like it was yesterday

**Comment by sirnat** [comment] 2022-02-15 20:30
I remember this day, like it was yesterday.. The day I raged when dying to a temp gun.. With a desword.. Now I hardly even touch ss13.. I love our reunions every year.

**Comment by Spc-Dragonfruits** [comment] 2022-02-20 16:47
This is part of SS13 history

**Comment by duncathan** [comment] 2022-02-20 23:44
@sirnat thanks again for bringing us together like this.

**Comment by Mothblocks** [comment] 2023-04-28 15:28
he died to a temp gun

**Comment by sirnat** [comment] 2023-04-28 16:29
I'm so happy this comes back around every few years

**Comment by sirnat** [comment] 2023-04-28 16:31
You lot were some fun ppl to game with. 2015 was the year I graduated high school. Hope all your lives have been going good.

**Comment by anclandor** [comment] 2023-04-29 22:14
We really need to get around to nerfing the temp gun, I mean its been eight years since this guy was killed by one and STILL no change!

**Comment by Moonlit2000** [comment] 2023-05-04 18:38
This guy was killed by a tempgun twelve years after the game was made. If we don't nerf it, we could get a second tempgun death in just four years!

**Comment by sirnat** [comment] 2023-05-04 19:37
I haven't played ss13 in awhile but i remember being such an annoying fucker my notes list was long even though, I almost made it to the staff team on a few occasions I'm glad to have had the memory of this with you lot. @Iamgoofball and @Stickymayhem you two were some of who I saw as decent acquaintances even tho I annoyed tf outta sticky. Hope you guys are doing well if you want to get in touch with me I can get you guys a few ways to connect

**Comment by PKPenguin321** [comment] 2023-06-14 06:47
@sirnat skill issue

**Comment by duncathan** [comment] 2023-06-23 07:03
thanks again for intermittent joy i receive seeing this issue appear in my github notifications <3

**Comment by rageguy505** [comment] 2023-12-27 03:51
you can block tempgun shots now :(

**Comment by notfrying1pans** [comment] 2024-02-05 18:25
heres to another new year

**Comment by sirnat** [comment] 2024-02-06 16:17
Here's to the year 2024 the year of blocking temp gun beams

**Comment by anclandor** [comment] 2024-02-15 01:10
SO happy this horrible bug has been fixed.

**Comment by optimumtact** [comment] 2024-02-15 20:10
it's only funny if you comment on the anniversary please tone it down.
