### ISSUE TITLE
The autolathe cannot dispense glass

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13893] opened 2015-12-21 23:13 UTC
It dissapears

**Comment by swankcookie** [comment] 2015-12-21 23:53
was it a map-spawned one, or did you build it?  which map?

**Comment by Zilenan91** [comment] 2015-12-21 23:55
map-spawned, ass station

**Comment by WJohn** [comment] 2015-12-21 23:58
Strange, I've definitely got the autolathe on metastation to dispense glass just yesterday.

**Comment by xxalpha** [comment] 2015-12-22 01:01
Can't reproduce.

**Comment by Zilenan91** [comment] 2015-12-22 01:09
The glass dissapeared when I tried to print glass off of it

**Comment by xxalpha** [comment] 2015-12-22 01:10
Nope, it works fine.

**Comment by Zilenan91** [comment] 2015-12-22 01:11
strange

**Comment by tkdrg** [comment] 2015-12-23 21:40
closing as can't reproduce unless we can get more info on this

**Closed by tkdrg** 2015-12-23 21:40 UTC
Labels: Bug, Needs Reproducing/Testing
