### ISSUE TITLE
Xenobio headslugs not working

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#11332] opened 2015-08-23 01:54 UTC
Headslugs spawned via xenobiology do not work. They can lay eggs in dead bodies fine, and die shortly after as they should, but what hatches is instead a regular monkey, not a monkeyling.

**Comment by PKPenguin321** [comment] 2015-08-23 03:27
that monkey could still be made into a human via genetics though right

**Comment by WJohn** [comment] 2015-08-23 03:37
Dupe of #9365

**Closed by WJohn** 2015-08-23 03:37 UTC
