### ISSUE TITLE
Entering the gateway should immobilize you for a moment, to prevent you from instantly going through it again.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13545] opened 2015-12-10 08:13 UTC
What it says on the tin, it's very easy to accidentally jump back into the mission when you didn't mean to because you moved one tile too many.

**Comment by Supermichael777** [comment] 2015-12-10 13:50
The clown: HONK *SHOVE*

**Comment by xxalpha** [comment] 2015-12-10 15:55
This is a duplicate issue.

**Comment by CosmicScientist** [comment] 2015-12-10 16:55
Of which one @xxalpha?

**Comment by tkdrg** [comment] 2015-12-10 17:34
Dupe of #2717

**Comment by Dorsisdwarf** [comment] 2015-12-11 08:10
#CRUSHED#

**Closed** 2015-12-11 08:11 UTC
Labels: Feature Request, Usability
