### ISSUE TITLE
AI voicechange meta

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/-tg-station#7551] opened 2015-02-04 18:35 UTC
When a ling uses imitate voice or a traitor uses a voicechanger, the AI's follow buttons lead straight to the mob regardless of whether the visual name matches the message.  This leads to silly behavior which makes the ruse trivially easy for AI's to discover, such as:
If the AI clicks the follow button for a message with any name, it will lead to the actual mob who said the message.  If, for example, the Janitor impersonated the Captain, the follow button would take the AI to the janitor, not the Captain.
If the AI has followed the Captain, but not the Janitor, follow links to the Captian will show up purple rather than blue as they have been clicked on, but follow links from the Janitor impersonating the Captain will show up as blue.
Plus there's probably the issue of being able to see the actual text of the follow link which'll give it away anyway.
This is bad because AIs make voice changers and imitate-voice nearly useless.
The best way to fix this would probably be to have some proc that tries to find a mob in the camera network given a name, and to make follow links use that.

**Comment by Razharas** [comment] 2015-02-06 23:59
I think its duplicate
Also old issue
Also none knows how to solve it nicely

**Comment by Cheridan** [comment] 2015-02-09 14:49
dupe of #1128

**Closed by Cheridan** 2015-02-09 14:49 UTC
