### ISSUE TITLE
rev icons dissapearing (maybe cult too)

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3569] opened 2014-04-28 21:36 UTC
if you're a rev and disconnect, once you reconnect, you won't have the red/blue R icons next to you or your teammates.
This happens when an admin returns to his body, for example, pressing twice F5.

**Comment by Dorsisdwarf** [comment] 2015-08-27 11:16
Cannot reproduce, closing due to age

**Closed by Dorsisdwarf** 2015-08-27 11:16 UTC
Labels: Bug, Needs Reproducing
