### ISSUE TITLE
Restrained SNPCs cannot be dragged

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7356] opened 2015-01-25 22:14 UTC
Handcuffed greytide move regardless of being held by someone else.

**Comment by WJohn** [comment] 2015-01-25 22:21
SNPCs are incredibly shit. Who'da thought?

**Comment by Stickymayhem** [comment] 2015-01-25 22:43
I hope they become neat ;_;

**Comment by optimumtact** [comment] 2015-01-26 02:56
@sawu-tg pls

**Comment by Miauw62** [comment] 2015-01-26 16:04
sawu quit.

**Comment by WJohn** [comment] 2015-01-26 18:27
Of course he did.

**Comment by palpatine213** [comment] 2015-01-30 00:25
They still can't be dragged even if dead.

**Comment by Cheridan** [comment] 2015-05-26 18:42
Basically a dupe of #8324

**Comment by freerealestate** [comment] 2015-08-07 07:53
You also get a runtime when an SNPC spawns as a head of staff, such as when using the Populate World verb

**Comment by optimumtact** [comment] 2015-08-07 08:19
it's dead code basically

**Comment by freerealestate** [comment] 2015-08-07 08:19
Why?

**Comment by optimumtact** [comment] 2015-08-07 08:20
Nobody else is stepping up to maintain it, I don't see anyone who looks like they will in the near future either.

Happy to be proven wrong

**Comment by Shadowlight213** [comment] 2015-08-07 15:59
I have a hunch about what's wrong with SNPC movement, but until I understand movement code better, I can't test my hunch.

**Closed** 2015-08-29 18:13 UTC
Labels: Bug
