### ISSUE TITLE
Traitor objective / law 0 from traitor AI not given to roundstart cyborg

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#14241] opened 2016-01-01 11:07 UTC
**Server:** Sybil

**Revision:** Didn't grab the exact number; it's whatever revision was active around 2015-12-31 20:30 UTC+01:00.

**Problem Description:** I was the roundstart cyborg. Initial law display listed Asimov, with no special messages or traitor announcements. Beep over to Robotics to get a replacement cell. Roboticist pops me open, and right around this point I notice a 'Hacked' icon in the top left of the screen. Assuming the Roboticist just emagged me, I check the chat log for the usual emag messages, but there are none. 

I click Show Laws, which lists standard Asimov again, but also says something about the AI not knowing about my law 0, and to avoid suspicion. It also says obeying is optional, and that the laws are synched to the AI. There is no zeroth law listed, and my notes don't show any objectives.

At this point, the Roboticist notices the busted interface and decons me. I adminhelp asking what the hell, STP looks into it and mentions that both the AI and the newly created cyborg had a law 0. He couldn't check my laws anymore since I was deconned.

**What did you expect to happen:** A zeroth law, objectives, or any indication whatsoever that I was apparantly a traitor and/or slaved to a traitorous AI.

**What happened instead:** Standard Asimov, no special messages at all; only the 'Show Laws' verb giving a weird line about a non-existent law 0.

**Why is this bad/What are the consequences:** Same as the older incarnations of this issue. Should be clear enough from the story.

**Steps to reproduce the problem:** I'm guessing it's not a 100% thing, or it might have been encountered sooner, so this is pretty bare-bones.

1. Get roundstart cyborg
2. Get a traitor AI

**Possibly related stuff:** The Show-Laws message was implying that I was a lone traitorous cyborg, and that the AI was kosher. STP mentioned that the AI definately had a zeroth law, so this seems to be contradictory.

**Comment by YakumoChen** [comment] 2016-01-01 11:11
from what I've seen it usually pops up after a minute, but I've had admins erroneously tell me I have to hack the borg first for the objective to appear, which is outright wrong (and dangerous)

Borgs still have to follow the AI's orders, however, so if AI gets law 0 and tells its borgs, they have to follow with it.

**Comment by Iamgoofball** [comment] 2016-01-01 11:11
May or may not be an objectives issue, might be a laws issue, might be a @KorPhaeron malf ai issue

**Comment by Braincake** [comment] 2016-01-01 11:18
>**YakumoChen** commented 5 minutes ago
>from what I've seen it usually pops up after a minute

It took a few minutes for me to reach Robotics because reasons, so I don't think time was the issue.

>Borgs still have to follow the AI's orders, however, so if AI gets law 0 and tells its borgs, they have to follow with it.

Normally, yeah. However, the Show-Laws message explicitly said that I should ignore the AI when it comes to accomplishing my (non-existent) law 0, which was rather odd.

**Comment by Jalleo** [comment] 2016-01-01 11:22
I know what the issue is its because antag is being handed out incorrectly due to how cyborg and AI roles are handed out. Its a confliction of antag and job code.

**Comment by Supermichael777** [comment] 2016-01-01 13:49
yummy dupe you have here

**Comment by KorPhaeron** [comment] 2016-01-03 05:45
@Aranclanos 

You just merged the fix for this, but I forgot to autoclose it

**Closed** 2016-01-03 06:01 UTC
