### ISSUE TITLE
Insulated gloves lose their insulation when dyed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8203] opened 2015-03-07 17:10 UTC
Probably not intended!

**Comment by Mandurrrh** [comment] 2015-03-07 17:35
Ill test this out next round. It may very well be they were the trick insulateds and someone didn't exam. coughcoughscaredycough.

**Comment by phil235** [comment] 2015-03-07 17:38
can't reproduce.

**Comment by Miauw62** [comment] 2015-03-07 17:57
this is probably a dupe.

**Comment by phil235** [comment] 2015-03-07 19:12
duplicate of #7321

**Closed by phil235** 2015-03-07 19:12 UTC
