### ISSUE TITLE
Spiderlings occasionally congregate into huge piles and bug out

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#11704] opened 2015-09-10 21:23 UTC
Proof here, they never grew up and did nothing. This is the case for both player spiders and lings.
http://i.imgur.com/01ltVYz.png?1

Same bug as #11620 but with added proof

**Comment by Nitrousoxide** [comment] 2015-09-10 21:31
>bug out
bu dum tsh

**Comment by Zilenan91** [comment] 2015-09-10 21:37
@Nitrousoxide Ayyy intentional

**Comment by WJohn** [comment] 2015-09-10 23:57
Dupe of #11620

**Closed by WJohn** 2015-09-10 23:57 UTC
