### ISSUE TITLE
Can't vend virus bottles with the + character in the name.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#8025] opened 2015-02-27 02:56 UTC
Put a virus bottle named "Eternal Youth+1" inside the smart virus storage to find that it is now trapped forever within the fridge.

I've been using +1 to indicate that it has one other symptom, but I believe it's doing parsing to look for "EternalYouth1" which doesn't exist.

The same results happen with any bottle which has a name with +1 or + 1 in it.

**Comment by Miauw62** [comment] 2015-03-01 19:32
I think this is a dupe.

**Comment by phil235** [comment] 2015-03-08 23:45
duplicate of #4708

**Closed by phil235** 2015-03-08 23:45 UTC
Labels: Bug
