### ISSUE TITLE
all camera networks broken AGAIN

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#15006] opened 2016-01-28 13:28 UTC
Can't view any camera on cam consoles. fucks with AI etc. etc.

**Comment by neersighted** [comment] 2016-01-28 13:31
Dupe of #14985

**Comment by CPTANT** [comment] 2016-01-28 13:52
that one says AI cant use camera's

ALL camera's are broken

**Comment by neersighted** [comment] 2016-01-28 13:53
Its an issue with all cameras. Please read the other issue that was closed as dupe in favor of that one.
Regardless, it is the same problem. And a PR is up.

**Comment by Dorsisdwarf** [comment] 2016-01-28 14:13
Closed due to a near-dupe of #14985. A fix is inbound already.

**Closed by Dorsisdwarf** 2016-01-28 14:13 UTC
