### ISSUE TITLE
NOSHIELD Flag Doesn't Do Anything

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8929] opened 2015-04-12 22:38 UTC
It would appear that this flag doesn't actually do anything; it exists in setup and is on a number of sword and two-handed weapons, but it doesn't  actually do anything; from its description, it sounds as though weapons with this modifier are meant to pierce shields no matter what, but this definitely isn't the case; shields block weapons with this flag.

**Comment by Thunder12345** [comment] 2015-04-12 23:01
Is it used anywhere else in the code?

**Comment by Fox-McCloud** [comment] 2015-04-13 00:24
Nope; unless someone defined it by its bitflag instead of its DEFINE---in which case, good luck finding it.

**Comment by Cheridan** [comment] 2015-04-13 13:54
duplicate of #2753

**Closed by Cheridan** 2015-04-13 13:54 UTC
