### ISSUE TITLE
As an artificer a flashbang made me Permadeaf

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#6853] opened 2015-01-06 21:01 UTC
As above. Got flashbanged and poof unable to hear

**Comment by WJohn** [comment] 2015-01-06 21:29
Duplicate of #6442 and a ton of other issues. Deafness is pretty much universally broken for everything that isn't a human.

**Comment by tkdrg** [comment] 2015-01-06 21:30
Dupe

**Closed by tkdrg** 2015-01-06 21:30 UTC
