### ISSUE TITLE
VVing capguns crashes the game.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/-tg-station#17326] opened 2016-05-02 04:05 UTC
fuck

**Comment by hornygranny** [comment] 2016-05-02 06:21
dupe of https://github.com/tgstation/-tg-station/issues/10881
the object seems to change randomly between revisions but is reproducible on each revision

**Comment by Incoming5643** [comment] 2016-05-02 06:58
yep, a few revisions back it was rubber ducks, I was devastated.

**Closed** 2016-05-16 04:57 UTC
Labels: Bug
