### ISSUE TITLE
Changeling Augmented Vision doesn't give night vision

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10427] opened 2015-07-06 14:43 UTC
Unconfirmed player report.

HELP: Kel the Oblivious/(X) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Changeling augmented vision is bugged. It gives thermal, but not nightvision. 

Apparently the ability description suggests you should be getting night vision in addition to thermals. Either it's broken and it doesn't, or the description needs to be reworded.

**Comment by Miauw62** [comment] 2015-07-06 14:48
duplicate issue i think

**Comment by WJohn** [comment] 2015-07-06 15:29
Yeah dupe of #10297

**Closed by WJohn** 2015-07-06 15:29 UTC
