### ISSUE TITLE
Hybrid taser goes invisible when adding seclite

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#7661] opened 2015-02-11 18:29 UTC
![](http://i.imgur.com/KkX1qYR.png)

Whoops!

Repro:
* Add seclite to hybrid taser

Expected:
* Light and gun!

Reality: Sprite disappears and leaves only the seclite sprite.

**Comment by paprka** [comment] 2015-02-11 20:29
Very likely fixed in https://github.com/tgstation/-tg-station/pull/7651

**Comment by Sometinyprick** [comment] 2015-02-12 00:27
Some more information if it's at all helpful.
Just to add I attempted to recreate this but I couldn't, firing your taser once will fix the sprite however if it's changed.
In that case the icon_State was changed to advtaser325 which doesn't exist so it had no sprite.

**Comment by phil235** [comment] 2015-02-13 18:39
Can't reproduce, so it looks like it is fixed.

**Closed by phil235** 2015-02-13 18:39 UTC
Labels: Bug, Sprites
