### ISSUE TITLE
Admins get notified that "emitter lost power" when they shouldn't

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#14135] opened 2015-12-29 02:56 UTC
The point is that the emitter doesn't lose power so it ends up spamming the admins with ~3 lines of false alarms.

**Comment by Jordie0608** [comment] 2015-12-29 03:03
IIRC this is actually due to emitters checking they have power when the powernet is recalculating.

**Comment by Iamgoofball** [comment] 2015-12-29 05:40
goofball literally can't EMP it due to the emitter being on the blacklist, so it has to be that power check meme.

**Comment by Shadowlight213** [comment] 2015-12-29 09:11
This is a dupe of a really old issue I think

**Comment by WJohn** [comment] 2015-12-29 11:18
Yeah, dupe of #4777

Good catch.

**Closed by WJohn** 2015-12-29 11:18 UTC
Labels: Administration, Logging
