### ISSUE TITLE
Bug: Camera alarms only go off when the camera is repaired/restored

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#16361] opened 2016-03-25 17:17 UTC
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Some cameras start out roundstart broken, but do not generate camera alarms. The AI/cyborg gets a camera alarm from that location after the camera is fixed, which is quickly cleared. The same happens when a camera is EMP'd.

An alarm when something is fixed isn't very useful.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by bgobandit** [comment] 2016-04-30 19:52
Not a bug, this was an intentional change to prevent the AI from validshouting once a camera was cut

**Comment by coiax** [comment] 2016-04-30 21:26
Nice necroshouting.

My new solution to such an idea is just put the camera alarm on a random delay of at least one minute, so the AI will eventually realise, and be able to provide a list of broken cameras on demand, but stops the validshouting.

**Comment by PKPenguin321** [comment] 2016-04-30 22:24
or just leave it alone instead of buffing the AI

**Comment by PKPenguin321** [comment] 2016-04-30 22:24
also close this issue

**Comment by Shadowlight213** [comment] 2016-05-09 00:31
Not a bug. It was set as intentional.
It lets you actually silently cut cams.

**Comment by PKPenguin321** [comment] 2016-05-09 00:48
yeah seriously somebody close this

**Closed** 2016-05-09 10:18 UTC
Labels: Bug
