### ISSUE TITLE
Can't add in cables to machine frame components.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10631] opened 2015-07-15 12:10 UTC
When you try to put in a cable coil in the component phase (adding matter bins and micro manipulators), the cable coil is dropped. This, by extension, means you can't build things like cloning scanners or turbines. More importantly, you can completely ruin cloning just by deconstructing the scanner and watch people be unable to put it back together.

**Comment by phil235** [comment] 2015-07-15 13:17
I tested it and the cable coil is properly inserted in the machine and it can be constructed just fine. What IS being dropped is the rest of the cable coil that isn't being used. All you have to do is pick up the coil and add it on the machine again. You're basically adding cables one at a time. It's still a bug but not as big.

**Comment by Marflowerose** [comment] 2015-07-15 16:59
Seems like dupe of https://github.com/tgstation/-tg-station/issues/10375

**Comment by phil235** [comment] 2015-07-15 17:11
yep

**Closed by phil235** 2015-07-15 17:11 UTC
Labels: Bug
