### ISSUE TITLE
mismatched z level transitions

### ISSUE THREAD

**Issue by norill** [tgstation/-tg-station#8727] opened 2015-04-03 20:32 UTC
edge transitions between z levels do not correspond to each other. i.e. if going north from z1 leads to z3 does not mean going south from z3 will lead you back to z1. its confusing and frustrating. one misstep in spess and you end up fuck knows where, even if you throw something in the opposite direction

**Comment by Supermichael777** [comment] 2015-04-03 22:22
this is intentional.

**Comment by WJohn** [comment] 2015-04-04 00:02
Dupe of #8661 #6338 and #5614

**Comment by optimumtact** [comment] 2015-04-04 04:15
can we close some of these dupes then please WJohn

**Closed** 2015-04-04 04:22 UTC

**Comment by Miauw62** [comment] 2015-04-04 09:23
This is not intentional as far as I'm concerned
Op 4-apr.-2015 06:22 schreef "Jordie" <notifications@github.com>:

**Comment by Jordie0608** [comment] 2015-04-04 09:43
It's a triple-dupe, #5614 is the original.

**Comment by norill** [comment] 2015-04-04 22:52
so is it intentional or not? i could probably fix it it its not intentional

**Comment by norill** [comment] 2015-04-04 22:56
the whole spesscube thing won't work no matter what, because logic. it has to be torus, not cube

**Comment by optimumtact** [comment] 2015-04-05 02:41
It's just a side affect, if you have some useful system that's better / more consistent or understandable then by all means go for it
