### ISSUE TITLE
Ayyylien teleporter teleports cause people to switch places

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10147] opened 2015-06-25 01:07 UTC
And it makes playing ayyylien fucking awful when you lose a guy three times because he's switching with your agent.

**Comment by Jordie0608** [comment] 2015-06-25 03:53
Likely related to #4214

**Comment by Jordie0608** [comment] 2015-06-25 03:54
Dupe of #9138 actually

**Closed by Jordie0608** 2015-06-25 03:54 UTC
Labels: Bug
