### ISSUE TITLE
Setting the shaker's transfer rate to 25 deletes the shaker

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7779] opened 2015-02-17 02:03 UTC

**Comment by phil235** [comment] 2015-02-17 18:20
can't reproduce. Can we have more info on how it happened? (you're talking about the bartender's shaker, right?)

**Comment by Dorsisdwarf** [comment] 2015-09-04 12:35
No information forthcoming, bug is months old and unable to reproduce, closing.

**Closed by Dorsisdwarf** 2015-09-04 12:35 UTC
Labels: Bug, Cannot Reproduce

**Comment by Chocobro** [comment] 2016-09-29 12:33
i know this is wicked ancient but the entire information was i spawned in as a bartender at round start, changed my shaker to 25 and it disappeared into the shadow realm
