### ISSUE TITLE
Cultist comms don't get readded when cloned

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#15205] opened 2016-02-05 01:59 UTC
They retain their cultist status, but they don't get the comms verb back. Probably another one for the post-datum antags pile.

**Comment by KorPhaeron** [comment] 2016-02-05 03:56
Should be a spell instead of a verb anyway. They'd get an action button and it would transfer

**Comment by Shadowlight213** [comment] 2016-02-07 19:07
Dupe of #8726

**Closed** 2016-02-07 19:25 UTC
Labels: Bug
