### ISSUE TITLE
Vending Machines Have Wierd Stuff instead of the Normal Stuff

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#6973] opened 2015-01-11 19:26 UTC
Server: Sybil, Around Noon Mountain Time.

Revision: #6942

Problem Description: Vending machines have a bunch of strange stuff instead of food/drink.

What did you expect to happen: I wanted to get some food or soda.

What happened instead: I could get stuff like dice, soap, tequila, maid uniforms, you get the idea!

Why is this bad/What are the consequences: We can't get normal food or drink or coffee!

Steps to reproduce the problem: Look at a food, drink, or coffee vending machine during a round.

Extra Note: Only effects the food related vending machines, clothes/sec/cig machines seemed fine. Did not check chef's or bartender's at this time.

**Comment by RemieRichards** [comment] 2015-01-11 19:27
Think this is a dupe of the robot arms becoming different items in mech fabricators.
it sounds like Byond messing up refs.

**Closed** 2015-01-12 00:40 UTC
Labels: Bug, Higgs-Bugson
