### ISSUE TITLE
APC wire pulses should be working with a real timer, not spawn()

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#1130] opened 2013-08-12 10:37 UTC
Airlocks use a "real" timer in the game.

**Comment by Jalleo** [comment] 2015-01-08 12:09
@tkdrg could you quickly check if this one should be closed it appears to be something nobody knows what the problem is

**Comment by tkdrg** [comment] 2015-01-08 17:44
It's not a problem (thus the "Not a Bug" tag). It's more of a feature request, if anything. Basically I think he's asking for a specific APC ticker instead of ad-hoc spawn()s all over the place.

**Comment by astralenigma** [comment] 2015-05-28 20:54
In my opinion the problem here is that he's asking for a feature thinking something else is using this feature.
Senior coders should see if it can and should be achieved. if the answer is no to either then this should be closed.

**Comment by Aranclanos** [comment] 2015-05-29 01:07
I made this issue with a proxie person, the wires shouldn't use  spawn() 👌

**Closed** 2016-01-23 00:36 UTC
Labels: Maintainability - Hinders improvements, Not a bug, Usability
