### ISSUE TITLE
You can't pour from one reagent container to another if they're both on your person

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#10365] opened 2015-07-04 03:43 UTC
If you're trying to pour from a beaker (probably any container) to another beaker in your other hand/pocket/bag it just won't work, you need to place the beaker to pour into on the floor/table

**Comment by Ikarrus** [comment] 2015-07-04 03:45
Duplicate of #10346

**Closed** 2015-07-04 03:46 UTC
