### ISSUE TITLE
Deconstructing Telecomms machines doesn't work

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#8793] opened 2015-04-06 20:35 UTC
Problem Description: The last step of telecomm machine deconstruction (crowbaring out the parts) doesn't work: it does say it completed the step, but the parts don't come out, and the stage doesn't progress.

What did you expect to happen: The machine to actually deconstruct.

What happened instead: It didn't deconstruct.

Why is this bad/What are the consequences: Makes it a whole bit harder to sabotage telecomms for a larger length of time.

Steps to reproduce the problem: Follow the deconstruction steps for the telecomm machines.

Server: Sybil.

Revision: What revision was the server running? Revision compiled on: 2015-04-06,
9c4e744fc9fc6dd3be19a65fd2cac25681486518

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I was a cyborg. Haven't explicitly tried it as a normal boring carbon yet.

**Comment by francinum** [comment] 2015-04-06 20:57
Cannot reproduce.

**Comment by phil235** [comment] 2015-04-06 21:19
duplicate of #8715

**Closed by phil235** 2015-04-06 21:19 UTC
