### ISSUE TITLE
Sounds randomly start cutting off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9470] opened 2015-05-13 01:00 UTC
Partway through a round and at times all the way through rounds, all sounds will cut off within a second of being played, sometimes near instantly. This seems to be able to happen for either the entire round or only a certain duration, but I have absolutely no clue what's causing this.

**Comment by Miauw62** [comment] 2015-05-13 07:49
This might be a dupe
Op 13-mei-2015 03:00 schreef "WJohn" <notifications@github.com>:

**Comment by Marflowerose** [comment] 2015-05-13 09:00
Also applies to instruments. I was playing Violin, Guitar and piano at the same time (as one does) and only portions of each instrument were played and sometimes all of them just quieted down.

**Comment by Cheridan** [comment] 2015-05-13 13:45
Dupe of #9042

**Closed by Cheridan** 2015-05-13 13:45 UTC
Labels: Bug, Sound
