### ISSUE TITLE
mining hardsuits don't have lights

### ISSUE THREAD

**Issue by pudl** [tgstation/-tg-station#8560] opened 2015-03-26 22:04 UTC
with the mining hardsuit change, their head flashlight doesn't turn on at all. worse is that paprika removed the ability to put lanterns in the suit storage, so you don't have any good way to get light.

**Comment by GunHog** [comment] 2015-03-26 23:38
Duplicate of https://github.com/tgstation/-tg-station/issues/8541. This is my fault, not his. I failed to check for this when took over Steelpoint's helmet update. A fix is already posted, stay tuned.

**Closed** 2015-03-26 23:58 UTC
