### ISSUE TITLE
Buckshot is underwhelming

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9265] opened 2015-05-01 18:33 UTC
More of a feature request than an actual issue report

Buckshot damage is pretty underwhelming and considering it only comes from Combat Shotguns, the lathe for the bartender, or most importantly, Syndicate Shotguns, this really would just be a QoL buff. 

Currently at point blank (Disregarding the weird and sort of shitty point blank mechanic) buckshot requires 2 shots to put somebody into crit, with 5 pellets do 15 damage each. *This is using the point blank* mechanic where you have to click on someone adjacent and it hits them with all 5. *Clicking behind someone does not hit them with all 5*, instead hitting them with 3 while the other 2 magically curve around them. Point blank aside this makes combat shotguns total trash, wherein you can't double-tap people fast enough, and if it's a gunfight you will likely not be in range.

I personally recommend buffing buckshot's individual pellet damage to like, 25 or something. People should be getting vaporized when they get hit by enough pellets which means they're pretty damn close given the nature of spread.

#BuffShotguns2015

**Comment by hornygranny** [comment] 2015-05-01 20:31
:+1:

**Comment by WJohn** [comment] 2015-05-01 21:05
Dupe of #9118

**Comment by Lumipharon** [comment] 2015-05-02 02:06
Just make them not spread so much. I mean seriously, fire buckshot in real life, it doesn't spread that much.

**Closed** 2015-05-02 07:40 UTC
Labels: Balance, Not a bug
