### ISSUE TITLE
tacticool turtleneck

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12337] opened 2015-10-12 05:03 UTC
For some reason you can't change the level of the suit sensors on this thing. It says it doesn't have sensors.

**Comment by Bawhoppen** [comment] 2015-10-12 07:00
Thats because its a turtleneck and not a jumpsuit

**Comment by Dorsisdwarf** [comment] 2015-10-12 07:34
The tacticool turtleneck is literally a toy sweater produced to poke fun at the syndicate. Why would it have sensors.

**Comment by KorPhaeron** [comment] 2015-10-12 08:40
It has no sensors because otherwise nuke ops would show up on the monitor.

Not a bug @Dorsisdwarf

**Comment by Firecage** [comment] 2015-10-12 08:44
....Kor misreads the situation again...

**Comment by Bawhoppen** [comment] 2015-10-12 08:46
Tacticool is the toy version of the Tactical turtleneck, Neither should have sensors.

**Comment by Dorsisdwarf** [comment] 2015-10-12 09:47
If nobody puts forwards a good reason why the tacticool turtleneck should have sensors, I'll close this soon (because holy shit we have a flood of actual bugs to handle right now)

**Comment by Jalleo** [comment] 2015-10-12 20:16
@dorsisdwarf i call it a intedended feature.

**Comment by Dorsisdwarf** [comment] 2015-10-12 21:19
Closed

**Closed by Dorsisdwarf** 2015-10-12 21:19 UTC
Labels: Feature Request, Not a bug, Unresolved

**Comment by Zilenan91** [comment] 2015-10-14 03:37
sorry this is late but examining the tacticool turtleneck says it has its sensors enabled

**Comment by Jalleo** [comment] 2015-10-14 08:47
Welp ^^^
