### ISSUE TITLE
AI bot control harm prevention system overload/disable

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#13433] opened 2015-12-04 01:50 UTC
You know how AIs are able to temporarily make bots like beepsky and medibots behave as emagged by switching off their harm prevention systems?
Well they still can, but now once you do it the bot responds with interface not responding when you try to do anything to it like undoing what you just did.
So, if an AI temporarily makes a bot have emagged behvaior they can't fix the bot and instead need someone to destroy the bot and rebuild it to have it fixed.
Why new Nanoui change everything :(

**Comment by tkdrg** [comment] 2015-12-04 02:11
this has literally nothing to do with nanoui, bots don't even use nano
this is a duplicate of #13363 and caused by anturk's simple animal bots

**Closed** 2015-12-04 02:26 UTC
