### ISSUE TITLE
Shadowlings can hatch after having already hatched previously

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12883] opened 2015-11-06 20:48 UTC
Happened during a round today, quite weird.

**Comment by KorPhaeron** [comment] 2015-11-07 00:08
Admin let him rehatch, not a bug

**Comment by Zilenan91** [comment] 2015-11-07 03:07
Why'd he need to rehatch?

**Comment by KorPhaeron** [comment] 2015-11-07 03:11
Nightvision broke or something, ask Oldman

**Comment by Niknakflak** [comment] 2015-11-07 06:11
Close this issue then

**Closed** 2015-11-07 06:13 UTC
Labels: Bug
