### ISSUE TITLE
Cyborgs have two entries on the orbit list

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/-tg-station#13231] opened 2015-11-26 02:37 UTC
All cyborgs have two entries on the orbit list.  The first one is their actual name, but there's also one just called "cyborg (number)" later on in the list as well.  If there's 3 cyborgs in the game at the moment the extra entries will go "cyborg 1, cyborg 2, cyborg 3"

Your orbit animation also has a zero radius when you're orbiting the extra entries

**Comment by WJohn** [comment] 2015-11-26 04:48
Dupe of #8858

**Closed by WJohn** 2015-11-26 04:48 UTC
