### ISSUE TITLE
Bug when items drop on fire

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#13159] opened 2015-11-22 16:55 UTC
Title sounds weird, but, I'll explain better here.
When you set a person on fire and their items drop, the hitbox of the items get huge. For example, a person drops an ID and above the ID there is a pen. You can't click the id neither the body because the pen is occuping the whole tile basically.

**Comment by RemieRichards** [comment] 2015-11-22 17:04
you know how when an item is inside a storage container you can click around it to pick it up, rather than on the sprite? That's this, except controlled.
It updates itself when items remove themselves PROPERLY, but clearly the fire system doesn't do it properly.

**Comment by tkdrg** [comment] 2015-11-22 19:00
Duplicate of something somewhere

**Comment by lzimann** [comment] 2015-11-23 22:32
I *think* it has been fixed. At least I couldn't reproduce it anymore.

**Comment by Dorsisdwarf** [comment] 2015-12-09 13:18
Dupe

**Closed by Dorsisdwarf** 2015-12-09 13:18 UTC
Labels: Bug
