### ISSUE TITLE
Can't change intent as a non person.

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#11028] opened 2015-08-05 02:20 UTC
This is specifically in mechs.
As a posibrain, and a believe also mmi's and AI's, you don't have access to intents, which means you can't for example, mech punch or clamp things.

There's no logical reason not to allow this, so I assume it's an oversight.

**Comment by phil235** [comment] 2015-08-05 10:45
duplicate of #10430

**Closed by phil235** 2015-08-05 10:45 UTC
