### ISSUE TITLE
Biogenerators start with no beakers.

### ISSUE THREAD

**Issue by CreationPro** [tgstation/-tg-station#3638] opened 2014-05-04 20:47 UTC
Issue occured on: Sybil, last seen today.
The issue occurs on roundstart. The biogenerators in both assistants' garden and permabrig start with no beakers, which are kind of daunting to get.

Why this is bad: the bug is minor, yes, but the permabrigged prisoners have nowhere to get a beaker, so that might halt their plants' growth.

**Comment by Cheridan** [comment] 2015-03-11 14:29
This was technically intended by the guy who added them. I'm closing this as it's not a bug, you can just use a bucket.

**Closed by Cheridan** 2015-03-11 14:29 UTC
Labels: Feature Request, Map Issue, Not a bug
