### ISSUE TITLE
Mobs can pass through RIPLEY mech

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#7529] opened 2015-02-03 21:51 UTC
Seems any mob can pass through a RIPLEY mech. Only tested with a borg and a human. Tested with both a pilot in and out of the mech. View is still blocked by the mech though.

**Comment by Kraseo** [comment] 2015-02-08 00:31
tried with all 4 variants of the ripley, couldn't reproduce

**Comment by GrayRachnid** [comment] 2015-02-14 21:01
Idk if this is still an issue(we still have it) but you can pass through and shoot through all mechs(atleast most from what i've seen) and it's very annoying when you try to hide behind a mech and get buttfucked because they can shoot lasers through it.

**Comment by phil235** [comment] 2015-04-14 16:02
@peoplearestrange What kind of mech did this happen with? One specific mech? One specific type of mech? all mechs?

**Comment by peoplearestrange** [comment] 2015-04-17 01:59
I saw it happen in a ripley. But weirdly I haven't seen it since the time of post. It was happening quite a bit that day and day after though IIRC.

**Comment by phil235** [comment] 2015-04-19 13:55
I guess this got fixed by a PR at some point... Reopen if this happens again.

**Closed by phil235** 2015-04-19 13:55 UTC
Labels: Bug, Cannot Reproduce
