### ISSUE TITLE
Standing under a shower behaves oddly regarding covered clothes

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#14622] opened 2016-01-14 11:11 UTC
Just had this recently - I was wearing a hardsuit over a bloody jumpsuit, stood under the running shower and then took off the hardsuit - jumpsuit did not get clean. I walked out from under the shower and then back under it and the jumpsuit got clean instantly.

**Comment by xxalpha** [comment] 2016-01-14 11:32
That's because it uses Cross or Crossed, should be an easy fix calling the one of these procs that does the cleaning when turning it on.

**Comment by WJohn** [comment] 2016-01-14 11:57
This bug's been around forever.

**Comment by Dorsisdwarf** [comment] 2016-01-14 14:19
Dupe of #9713

**Closed by Dorsisdwarf** 2016-01-14 14:19 UTC
Labels: Bug, Consistency Issue
