### ISSUE TITLE
AI Hologram becomes a Shadowling

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9101] opened 2015-04-21 03:16 UTC
...If the selected person is in fact, a shadowling, hatched or not.

**Comment by Iamgoofball** [comment] 2015-04-21 05:06
Ahahahahhahahahahahha

Feature/10 DNF

**Comment by pudl** [comment] 2015-04-21 13:39
if anyone fixes this, i'll flip shit

**Comment by Xhuis** [comment] 2015-04-21 20:57
So you're telling me that the hologram is a hatched shadowling, regardless of the hatched status of the shadowling? There's no way that should be occurring, so I'm calling it a feature.

**Comment by SconesC** [comment] 2015-04-21 21:38
@Xhuis Yep, no idea what could cause it but it happened ONCE. Unable to reproduce. 

Hilarious feature, right?

**Comment by Xhuis** [comment] 2015-04-21 22:00
Totally. I guess we should close this now because it isn't a bug.

**Comment by SconesC** [comment] 2015-04-21 23:06
Yep.

**Comment by Miauw62** [comment] 2015-04-22 13:52
what no this can be used to metagame.

**Comment by Dorsisdwarf** [comment] 2015-04-23 07:45
add Edge Case because it doesnt happen every time reportedly.

**Comment by phil235** [comment] 2015-10-11 17:06
can't reproduce, whether I'm creating the crew hologram icon before or after hatching, I still get the picture from crew records and not a shadowling (although I only tested with admincreated shadowling).

**Comment by Dorsisdwarf** [comment] 2015-12-03 13:09
Will be closed if nobody finds evidence of this happening in like a month. Sometimes BYOND just shits itself.

**Closed** 2015-12-29 22:55 UTC
Labels: Bug, Cannot Reproduce, Edge case, FUCK, In Game Exploit, Needs Reproducing/Testing, Shadowling
