### ISSUE TITLE
Xray lasers OP

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#9923] opened 2015-06-12 22:44 UTC
Right now, X-ray lasers are a bullshit level of overpowered. 
They can shoot through walls, and (unless I am mistaken), go forever. Meaning if you shoot them they go forever through Z levels and go through the station again. 
Combined with a X-ray implant, you're basiclly unstoppable unless someone else has the same thing.

On a side note, apparently it makes aliens very badly irradiated, because other day I shot an alien queen and it started shaking on the ground. :o.

**Comment by GunHog** [comment] 2015-06-12 22:58
The only part of this I agree with changing is the insane range they have. 14 spaces maximum (twice the distance one can normally see). The other things I find okay, given that it is an endgame product from Science, costs quite a bit of uranium, even at full upgrades, and generally takes a concentrated effort to get quickly. And yes, irradiation is quite a fun product of x-ray guns. I did not think aliens were affected, though.

**Comment by Dorsisdwarf** [comment] 2015-06-12 23:00
Pretty sure this is a dupe

**Comment by GunHog** [comment] 2015-06-12 23:04
Duplicate of #6928

**Comment by xxalpha** [comment] 2015-06-12 23:11
feedback forum

**Comment by WJohn** [comment] 2015-06-12 23:18
Yeah I'd be okay with a range limit, honestly. Their insane distance makes them basically a be-all-end-all against blobs, allowing you to one shot their core often from the other side of the station where the most they can do is swap cores (if they ever have enough resources sitting around to do that).

**Comment by Lumipharon** [comment] 2015-06-13 00:23
they're really fucking awful.

They used to not go through wall tiles.

After that change, you can just get a few then spam them in random directions all fucking round, and kill people with absolutely zero counter play.

**Comment by PKPenguin321** [comment] 2015-06-13 01:10
boo hoo
read the feedback in the other issue, lots of reasons to leave them mostly as is
if you absolutely *have* to change them (but really why should you), limit their range to one or two screens

also,
\>feedback forum

**Comment by Razharas** [comment] 2015-06-13 01:12
You are mistaken, projectiles dont go forever

**Comment by bgobandit** [comment] 2015-06-13 04:19
This is not the best time to talk about how OP they are due to infinite mining

**Comment by SconesC** [comment] 2015-06-13 05:07
No these really are actually pretty terrible, we had a traitor sci with about 5 in space outside escapes, he just shot into the shuttle until we launched with no stops

I thought they didn't even do that much damage but damn nigga those hurt

**Comment by Jordie0608** [comment] 2015-06-13 05:19
When they were first reworked they didn't shoot through walls; perhaps we should go back to that as I'm honestly not sure when and why that was changed.

**Comment by Stickymayhem** [comment] 2015-06-13 09:23
Yeah they are meant to be monstrously strong, this is just an end result of the extremely bad mining bug.

I don't honestly think they need rebalancing. Maxxing out R&D, getting shittons of minerals and going through the firing pin malarkey should be rewarding. 

They are only currently overpowered because you won't run out of them thanks to the mineral bullshit. In actuality they drain pretty quickly, show where they're coming from and rely on access to chargers which narrows down where it's coming from drastically.

**Comment by WJohn** [comment] 2015-06-13 10:26
To my knowledge they do 15 immediate burn and then enough rad damage to do 15 toxins (however that's converted, 1:1?)

**Comment by KorPhaeron** [comment] 2015-06-13 19:52
http://www.singulo.io/player.php?v=/tg/src/1433809799414.webm&t=test_10_.webm&loop=1

I was playing around with making a new xray gun if anyone is interested in using this as an xray replacement. Would still be powerful but not "shoot the entire station at once" powerful.

**Comment by Niknakflak** [comment] 2015-06-13 20:09
"I dies, pls nerf"

**Comment by Niknakflak** [comment] 2015-06-13 20:10
That looks worse kor, x-rays dont explode either.  People hate explosions for their bullshit knockdown, dont put it in a gun people can get outside of a wizard/badmin round.

**Comment by GunHog** [comment] 2015-06-13 20:53
XRAY EXPLOSIVE GUN? Holy fish!

**Comment by hanshansenhansson** [comment] 2015-06-15 08:28
You say "endgame product". In most blob rounds you see them after 20 - 25minutes. That is not endgame and way too early.

**Comment by SconesC** [comment] 2015-06-15 08:43
progression issue

**Comment by Miauw62** [comment] 2015-06-15 09:26
the issue is that blob is shit
if the blob is found early, its dead.
if its found a little later, it wrecks the entire station
if RD is competent and makes xray lasers, the blob loses.

**Comment by xxalpha** [comment] 2015-06-15 10:52
I don't know, xray beams going through walls is kind of OP, maybe gate it behind higher tech levels.

**Comment by palpatine213** [comment] 2015-06-15 18:47
Wait, so if the xray gun doesn't go through walls, what's the point of it other than as a hard counter to blob? I guess taking out a tide of assistants in rev? Nerfing the range is a good idea though.

**Closed** 2015-06-17 19:13 UTC
Labels: Balance
