### ISSUE TITLE
damp rag smothering is heinously broken

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10867] opened 2015-07-26 16:08 UTC
Do we not already have an issue report for this? How has it not been fixed?

Instant chemical application through masks and face-concealed gear including hardsuit helmets

**Comment by Marflowerose** [comment] 2015-07-26 17:15
https://github.com/tgstation/-tg-station/issues/10323
https://github.com/tgstation/-tg-station/issues/10784

**Comment by phil235** [comment] 2015-07-26 18:59
Duplicate of 10784

**Closed by phil235** 2015-07-26 18:59 UTC
