### ISSUE TITLE
Lighting is all kinds of bugged

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8264] opened 2015-03-10 00:08 UTC
![](http://i.imgur.com/Kj79Ay0.png)

Not sure what's causing this.

**Comment by kevinz000** [comment] 2015-03-10 01:42
muh carpetbombs is

**Comment by Cheridan** [comment] 2015-03-10 04:14
Probably related to/duplicate of #8063

**Comment by phil235** [comment] 2015-03-10 19:29
yep, duplicate, I saw that round and those tile were exposed to space and repaired.

**Closed** 2015-03-10 19:29 UTC
Labels: Bug
