### ISSUE TITLE
Full darkness not being dark properly

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#11127] opened 2015-08-10 00:19 UTC
![@MrPerson](http://puu.sh/jvEuq/163706f26c.jpg)
@MrPerson 
As you can see, a bunch of tiles aren't at full darkness despite all nearby tiles being completely dark.

**Comment by RemieRichards** [comment] 2015-08-10 00:22
Uh... the image is completely black?

**Comment by WJohn** [comment] 2015-08-10 00:32
Probably a dupe of #10899, but we'll have to see the pic to be sure.

**Comment by Anonus** [comment] 2015-08-10 00:41
It's not a dupe of #10899 though it might be related.

**Comment by MrStonedOne** [comment] 2015-08-10 02:06
![687474703a2f2f7075752e73682f6a764575712f313633373036663236632e6a7067](https://cloud.githubusercontent.com/assets/7069733/9158325/a3e3705a-3ec9-11e5-912f-ccaf41b1ad4b.jpg)
I fucked around with the levels, so that you can see it. but if you have a laptop you can do the same by tilting it.

**Comment by MrStonedOne** [comment] 2015-08-10 02:18
before:
![space station 13 2015-08-09 191601](https://cloud.githubusercontent.com/assets/7069733/9158397/1a8c7e08-3ecb-11e5-8140-0b720a4c201d.png)
after:
![space station 13 2015-08-09 191240](https://cloud.githubusercontent.com/assets/7069733/9158382/eb7e2a3a-3eca-11e5-8d35-676a0f5cddee.png)
Here is a better image of the effect, with more details, and a before/after. It seems to be completely random what tiles it happens to.

**Comment by MrStonedOne** [comment] 2016-01-24 19:34
This was fixed in #13333

**Closed** 2016-01-24 19:37 UTC
Labels: Bug
