### ISSUE TITLE
Malfunction AI air alarm abillity bugged

### ISSUE THREAD

**Issue by borntohonk** [tgstation/-tg-station#14353] opened 2016-01-03 20:02 UTC
I purchased the flood module for 50 points as a traitormalf.

I didn't get an enviromental mode setting to "flood" so i had to manually change the pressure checks.

please fix to enable my F.I.R.E. meme

**Comment by neersighted** [comment] 2016-01-03 20:38
I've never seen this before -- the original air alarm template did not include this... I'll see if I can track it down and add it.

**Comment by neersighted** [comment] 2016-01-04 03:44
I hate to ask you this... But did you use the module? It emags every alarm, and seems to work fine here.

![Wut](http://i.imgur.com/muyC14u.png)
![Lol](http://i.imgur.com/gitmoJ9.png)

**Comment by tkdrg** [comment] 2016-01-04 03:45
Closing as can't reproduce

**Closed by tkdrg** 2016-01-04 03:45 UTC
Labels: Bug
