### ISSUE TITLE
Can walk over cyborg rechargers as human.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#8052] opened 2015-02-28 00:05 UTC
Cyborg rechargers start closed and you can walk over them if they are not opened and closed again.

Steps to reproduce:
-Round start
-Walk over closed cyborg recharger
-Open and close recharger, can't walk over it anymore

**Comment by Dorsisdwarf** [comment] 2015-03-01 17:43
Cannot reproduce, can consistently walk over borg chargers after closing and opening them.

You're supposed to be able to walk over them when open anyway.

**Comment by xxalpha** [comment] 2015-03-01 19:23
Not when they're closed. They're dense when closed.

**Closed** 2015-03-02 14:37 UTC
Labels: Bug

**Comment by Dorsisdwarf** [comment] 2015-03-03 10:42
I can confirm that I've been able to walk over the one in the ministation shuttle, even after opening and closing.
