### ISSUE TITLE
Deathsquad are not flashbang-protected

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8041] opened 2015-02-27 18:25 UTC
...Seriously?

I think it's their helmets not having the flag, and/or the fact that they don't spawn with bowmans on

**Comment by paprka** [comment] 2015-02-27 23:06
Don't they have thermals or something

**Comment by Lumipharon** [comment] 2015-02-28 01:29
For some retarded fucking reason, thermals have negative flash protection, but NVG's don't. NOt sure if that's relevent to this specific case, but eh.

**Comment by paprka** [comment] 2015-02-28 04:14
Negative flash protection is basically shit

It's meant to balance thermals, which only overpowered death squads get, the detective doesn't get them anymore.

Best option is a removal of this and keeping it in as an option for balancing later on, but right now there is pretty much no reason for negative flash protection on anything that has it.

**Comment by phil235** [comment] 2015-02-28 10:51
or make deathsquad thermals a child of traitor thermals and then remove the negative flash protection.

**Comment by Miauw62** [comment] 2015-03-02 09:49
Traitors can order (disguised) thermals, paprika.

**Comment by Jalleo** [comment] 2015-03-02 12:31
dupe of #6669

**Closed** 2015-03-02 12:33 UTC
