### ISSUE TITLE
No sprite for C4 on cloning pods

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7397] opened 2015-01-28 03:04 UTC
Given that this is a thing that traitors can reasonably be expected to do often, it's weird that this of all things has no sprite. (The C4 still works, obviously; there's just no visual indication it's there.)

**Comment by Thunder12345** [comment] 2015-01-30 16:06
Couldn't reproduce this, was the pod in any specific state when it happened?

**Comment by phil235** [comment] 2015-01-30 17:45
can't reproduce either, even when messing with the clone pod's state. My guess is that the c4 was planted on the floor instead of the machine itself, I tested it and the planted c4 was indeed hidden byt the pod (

**Comment by phil235** [comment] 2015-04-19 13:58
Closing this.

**Closed by phil235** 2015-04-19 13:58 UTC
Labels: Bug, Cannot Reproduce, Sprites
