### ISSUE TITLE
You can punch bots without any downside

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#13449] opened 2015-12-04 21:49 UTC
You can destroy beepsky(it will take a while, but still) with punches without it trying to arrest you(like if you attack with something else). I did it as a hulk and took a while, but beepsky didn't care and accepted his fate.

**Comment by WJohn** [comment] 2015-12-04 21:57
Dupe of #13377 and there's already a fix PR up, just needs merging.

**Closed by WJohn** 2015-12-04 21:57 UTC
