### ISSUE TITLE
BioBag doesn't pickup slime cores without presence of monkey cube

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/-tg-station#13116] opened 2015-11-19 17:14 UTC
When clicking on a core with biobag in hand, no notification comes up and nothing is put in the bag.

When clicking on a monkey cube with biobag in hand while said monkey cube is on slime cores, notification comes up stating the monkey cube doesn't go in the bag but the slime cores are transferred into the bag.

**Comment by bgobandit** [comment] 2015-11-19 17:50
technically a dupe of https://github.com/tgstation/-tg-station/issues/12712 but way more detailed, close that one imo

still trying to figure out wtf is happening here

**Comment by tkdrg** [comment] 2015-11-19 19:40
Maybe the slime cores override attackby?

**Comment by Menshin** [comment] 2015-11-19 21:33
@tkdrg Right on the spot : neither _slime_extract_, nor _syringes_ or _blood_ call super on _attackby()_.

Maybe it would be worth considering using _/obj/item/weapon/storage/attack()_ instead ?

**Closed** 2016-02-13 20:25 UTC
Labels: Bug
