### ISSUE TITLE
Nanofrost does not close scrubbers

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#10473] opened 2015-07-08 16:21 UTC
Nanofrost is only closing up vents, not scrubbers.

**Comment by Miauw62** [comment] 2015-07-08 17:50
duplicate bug.

**Comment by phil235** [comment] 2015-07-08 19:02
Which issue is this a duplicate of?

**Comment by Miauw62** [comment] 2015-07-09 10:01
The issue of metal foam not working, dont know the issue number.

Although nanofrost not closing scrubbers isnt a duplicate.

**Closed** 2015-07-18 02:45 UTC
Labels: Bug
