### ISSUE TITLE
Admin AI interaction

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#14490] opened 2016-01-07 19:28 UTC
Admin's can still activate canisters/jetpacks, even with admin AI interaction off. Seems like it was missed when it got changed.

**Comment by Shadowlight213** [comment] 2016-01-07 23:48
That wasn't me actually. @neersighted added that to nanoui stuff.
I focused on stuff the AI could interact with, so it wasn't added to the toggle.

**Comment by neersighted** [comment] 2016-01-08 13:48
Yeah, this is not a bug. Admins can interact with any tgui. Do you want it moved behind the toggle for safety purposes? tgui interaction is a normal ghost feature (admins can just read and write), where as Admin AI interaction is the admin pretending to be an AI.

**Comment by lzimann** [comment] 2016-01-09 21:13
I think it would be great to have everything under admin AI interaction, better than clicking in accident something.

**Comment by tkdrg** [comment] 2016-01-24 18:26
fixed by neer apparently

**Closed by tkdrg** 2016-01-24 18:26 UTC
Labels: Administration, Bug
