### ISSUE TITLE
Syndicate bombs are awfully weak now

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#10410] opened 2015-07-05 13:59 UTC
Did not see anything in the changelog about them being changed, but they seem to do way less destruction now.

This is the aftermath of a bomb placed at tcomms, outside the r-wall with the APC.
![image](https://cloud.githubusercontent.com/assets/11201491/8511977/6d828052-232e-11e5-9ac6-9851108fc191.png)
Quite a lack of destruction there. Even the APC itself is still fully operational. In fact, only one machine was destroyed at all.

**Comment by phil235** [comment] 2015-07-05 14:03
Duplicate of #10118

**Closed by phil235** 2015-07-05 14:03 UTC
