### ISSUE TITLE
Paprika a shit

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7364] opened 2015-01-26 02:41 UTC
Paprika is a shit. Resolve posthaste.
This is my last service to TGstation :smile:

**Comment by optimumtact** [comment] 2015-01-26 02:54
Closed Wontfix

This is an intended feature, not a bug

**Closed** 2015-01-26 02:55 UTC
Labels: Cannot Reproduce, Consistency Issue, Feature Request, Fix, Maintainability - Hinders improvements, Priority: High, Unresolvable, Usability

**Comment by paprka** [comment] 2015-01-26 03:08
ow the edge case

**Comment by Nienhaus** [comment] 2015-01-26 03:18
You forgot a tag @Cheridan

**Comment by Miauw62** [comment] 2015-01-26 16:06
ayy lmao

**Comment by Iamgoofball** [comment] 2015-01-26 17:20
ayy lmao

**Comment by S0ldi3rKr4s0** [comment] 2015-01-26 17:31
ayy lmao

**Comment by Cheridan** [comment] 2015-01-26 17:31
ayy lmao

**Comment by RemieRichards** [comment] 2015-01-26 17:32
ayy lmao

**Comment by Kraseo** [comment] 2015-01-26 17:39
![ss 2015-01-26 at 05 27 31](https://cloud.githubusercontent.com/assets/3855300/5904691/a7153700-a58a-11e4-9361-b94aefb916d2.png)

**Comment by RemieRichards** [comment] 2015-01-26 17:41
>Attempt #37441 mom laya

**Comment by quaggaman555555** [comment] 2015-01-27 15:32
@Kraseo Can I get you to send me that python shell in some way? I'm curious as to what you did, but it might be a bit late though. How long did it take to get to ayy lmao? Oh, and look at attempt #37431, aol oyly, who poured oil on AOL?

**Comment by ike709** [comment] 2015-01-27 22:02
ayy lmao

**Comment by Dorsisdwarf** [comment] 2015-01-28 13:12
Oaml Y.Y.A

**Comment by quaggaman555555** [comment] 2015-01-28 17:00
Can I get you to send me that python shell in some way? I'm curious as to what you did, but it might be a bit late though. How long did it take to get to ayy lmao? Oh, and look at Attempt #37431, aol oyly, who poured oil on AOL?

**Comment by TheVekter** [comment] 2015-01-28 23:23
oaml yya
