### ISSUE TITLE
clowns can dupe handcuffs/cable restraints

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7910] opened 2015-02-22 19:01 UTC
Clowns apparently are unable to use handcuffs now for the same reason clowns can't use guns, and they end up cuffing themselves. However, the cuffing of the original person still goes through, resulting in:

Uh... how do those things work?!
Pocket is trying to put cable restraints on Emerson Ackerley!
You handcuff Emerson Ackerley.

Result: Both of us handcuffed, with two pairs of cable restraints. duuuuuupe

**Comment by Incoming5643** [comment] 2015-02-22 19:26
this bug report is a duplicate of #7910 :o)

**Comment by Jalleo** [comment] 2015-02-22 23:36
Well i never thought the clown as a trainee magician

**Comment by paprka** [comment] 2015-02-23 00:19
Feature ^

**Comment by mikecari** [comment] 2015-02-23 02:17
Wow clowns really can't do anything right can they?
...Why do I keep promoting clowns to security again?

**Closed** 2015-02-24 17:56 UTC
Labels: Bug
