### ISSUE TITLE
Making not Changelings through the power of science

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12628] opened 2015-10-24 06:21 UTC
Steps to reproduce:
1. Get an aggressive headslug through the life reaction of chemistry or through plasma in a gold slime core.  It must be aggresive.
2. Feed it a human corpse
3. Wait for corpse to pop
4. Out pops a changeling monkey with the ability to turn into a human and buy more abilities.
5. Maybe this bug is already known about except it doesn't register them as a changeling in the admin panel or even as an antag.  They are simply a human with changeling abilities according to every panel and antag checker in the game. 
6. Get really confused as the admin panel says they aren't a changeling but their screen says they are but they aren't an antag which is normally not even possible to be a changeling and not be an antag 
7. Ahaaaaaaaaaaaaaaaaaaaaaaaaaaaa

Featuring an image from the test
![image](http://i.imgur.com/uGb8tS5.png)

**Comment by kevinz000** [comment] 2015-10-24 06:23
Feature

**Comment by PKPenguin321** [comment] 2015-10-24 06:24
this is known, for the 10,000th time, and is (literally, not jokingly) a feature
iirc the only way to make them sentient is by using a sentience potion on the headslug

**Comment by Incoming5643** [comment] 2015-10-24 06:25
This is not a bug, fully intentional, and even has special code to make sure it works right.

If you bring a changeling into the world he will be your best friend. Sentience potion can melt the heart of a monster. Blessed be the station aligned changeling.

**Comment by Niknakflak** [comment] 2015-10-24 06:28
No sentience potions were used during the making of this not ling.  I wasn't sure if it was intended or not.   But the admin panel says they aren't changelings and it's not updating something correctly.

**Comment by PKPenguin321** [comment] 2015-10-24 06:31
waiiit so if the headslug murders you then you get to control the ling???
no wonder it didnt work when we did it on the braindead guy

**Comment by Incoming5643** [comment] 2015-10-24 06:33
To be clear here the bug is actually that if a npc headslug revives in a person that person gets control of the new ling, yeah?

All the stuff about improply updating admin panels literally not a bug because the ling is not intrinsically an antag (because ling abilities is its own seperate datum [WELCOME TO ANOTHER FACET OF HELL IN MY DATUM ANTAG JOURNEY])

**Comment by Niknakflak** [comment] 2015-10-24 06:39
Well the thing about the panels is incoming.  Changelings normally can't ever be changelings without being an antag so the panel is simply equipped to display non-antag changelings and therefore is misleading

**Comment by PKPenguin321** [comment] 2015-10-24 06:40
this needs to stay in the game tbh this is amazing
emergent gameplay at its absolute finest
(the adminpanel glitchyness should be fixed though)

**Comment by Incoming5643** [comment] 2015-10-24 06:45
ok so this is really hard to believe but

https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/modules/mob/living/simple_animal/hostile/headcrab.dm#L78

You getting control of the changeling if the headslug was mindless? Looks like an intended feature.

**Comment by Dorsisdwarf** [comment] 2015-10-24 07:00
CRUSHING UNDER THE BOOT OF CODERBUS BEFORE SOMEONE TRIES TO "FIX"

**Closed by Dorsisdwarf** 2015-10-24 07:00 UTC
