### ISSUE TITLE
You can put a grab in the trash.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#15161] opened 2016-02-03 04:57 UTC
Blame @KorPhaeron

**Comment by xxalpha** [comment] 2016-02-03 05:27
:put_litter_in_its_place:

**Comment by Incoming5643** [comment] 2016-02-03 06:29
It's funny because Kor is all about putting grabs in the trash

**Comment by tkdrg** [comment] 2016-02-08 22:54
@KorPhaeron 
phil said this is caused by https://github.com/tgstation/-tg-station/commit/621c59ad3da908ba28dc547e321aff2f1808d95e#diff-4b6c20ec7d37222630e7524d9577e230L312

**Comment by nukeop** [comment] 2016-04-09 19:25
I just saw this again the other day. Hilarious.

**Comment by nukeop** [comment] 2016-04-09 19:25
I just saw this again the other day. Hilarious.

**Comment by nullbear** [comment] 2016-04-16 09:28
fixed with https://github.com/tgstation/-tg-station/pull/16901

**Closed** 2016-05-13 22:18 UTC
Labels: Bug
