### ISSUE TITLE
Issue with deconstructing bombed APC's

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#9145] opened 2015-04-24 13:01 UTC
It is possible, for whatever reason, to use screwdriver on a panel of the APC with broken screen, which results in exposing wires. It has no point, as you cannot manipulate wires using wirecutters/multitool when the screen is broken.
The issue with that is, if you do expose wires, then break the screen and proceed with deconstruction, you will be unable to finish the wirecutters step of cutting cable and terminal out. You cannot close the panel either, as you had to destroy it to get to this step, and screwdriving results in fastening/unfastening the electronics. This effectively makes APC impossible to deconstruct if you expose wires.

**Comment by chimersable** [comment] 2015-04-27 04:05
Smash it.
 I ran into this once myself, after trying everything I got annoyed and began taking swings at it with a toolbox, which to my surpise worked.

**Comment by phil235** [comment] 2016-05-11 22:22
Can't reproduce, probably fixed by me in the attackby refactor

**Closed by phil235** 2016-05-11 22:22 UTC
Labels: Bug
