### ISSUE TITLE
Instant death as ghosts become shades

### ISSUE THREAD

**Issue by DocProfSmith** [tgstation/-tg-station#12445] opened 2015-10-16 20:24 UTC
Basically Laz0r died instantly upon becoming a shade for no discernible reason

**Comment by francinum** [comment] 2015-10-16 21:28
Any additional information? Time? Server? Were they the original inhibitor of the body or were they brought in as a ghost? This is all very important information.

**Comment by DocProfSmith** [comment] 2015-10-17 00:51
Ahh sorry, this is the first time I've done one of these. The server was sybil and they were brought in as a ghost. I unfortunately can't say much more about the time other than it happened not long before I filed this report.

**Comment by Dorsisdwarf** [comment] 2015-10-17 07:21
Dupe of #12320

**Closed by Dorsisdwarf** 2015-10-17 07:21 UTC
Labels: Bug
