### ISSUE TITLE
Shuttles flies rectangular.

### ISSUE THREAD

**Issue by bear1ake** [tgstation/-tg-station#9788] opened 2015-06-04 17:49 UTC
details in picture
![nukeshuttle](https://cloud.githubusercontent.com/assets/9455174/7990630/3c930322-0b2d-11e5-97b6-1863ea1ac522.png)

**Comment by Miauw62** [comment] 2015-06-04 17:55
i rate this issue report ayy/lmao

**Comment by RemieRichards** [comment] 2015-06-04 17:56
@Miauw62 Ayylmao is for Abductors lmao.

**Comment by CorruptComputer** [comment] 2015-06-04 18:02
this is probably because unsimulated turfs were removed.

**Comment by kyrahabattoir** [comment] 2015-06-04 18:19
Oh yeah on a sidenote, the centcom shuttle (not escape) turns the plating tiles where it's corner pieces are sitting at centcomm  into /turf/simulated/floor (honktiles?) after doing a return trip from the station.

**Comment by MrStonedOne** [comment] 2015-06-04 19:07
We know, I warned @Aranclanos about this after the shuttle turf thing.

I can fix it, but i won't, @Aranclanos decided to stick his nose in places he didn't understand, and removed checks without knowing what they did, did no testing on it, and got the maintainers to quick merged his untested piece of shit pr.

So @Aranclanos gets to be the one to fix it.

And since @Aranclanos has decided not to (its been 2 days), you should probability stop updating from the tgstation code branch since its in an unstable state and the maintainers have no plans to do anything about it.

**Comment by Iamgoofball** [comment] 2015-06-04 19:39
well @MrStonedOne I feel that you as @MrStonedOne should try and fix it since @MrStonedOne has the knowledge of how to fix it.

@MrStonedOne should be a good citizen and contribute his knowledge he has from being @MrStonedOne to the process of fixing the turf problems, which since @MrStonedOne knows what he's doing, @MrStonedOne should be able to easily and quickly fix the problem.

**Comment by RemieRichards** [comment] 2015-06-04 19:41
@Iamgoofball @Iamgoofball @Iamgoofball @Iamgoofball stop @Iamgoofball @Iamgoofball @Iamgoofball pls @Iamgoofball @Iamgoofball

**Comment by CorruptComputer** [comment] 2015-06-04 19:41
Make a var: shuttle
Have it default to: 0
Update shuttle turfs to: 1
Have it only move turfs that are: 1

**Comment by Iamgoofball** [comment] 2015-06-04 19:41
@RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards @RemieRichards dismemberment when?

**Comment by Aranclanos** [comment] 2015-06-04 19:50
what the fuck did you just say about me you little bitch? i'll have you know I graduated top of my class in the googlecode guard, and I've been involved in numerous code reworks on space station 13, and I have over 300 confirmed bugfixes. I am trained in autocommented code and I'm the top lag remover in the entire /tg/ branch commiters list. You are nothing to me but just another mantainer. I will wipe you the fuck out with precision the likes of which never been seen before on this github, mark my fucking words. You think you can get away with saying that shit to me over the internet? Think again, fucker. As we speak I am contacting my tortoise git local network across my computer and your github is being traced right now so you better prepare for the storm, fagget. The storm that wipes out the pathetic little thing that you call your branch, You're fucking code reverted, kid. I can be anywhere, anytime, and I can tell you that you're a faggot in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in faggotry, but I have access to the entire arsenal of the faggotry corps and I will use it to its full extent to call you a double faggot, you little donger. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the pric, you goddamn fool. I will shit dongers all over you and you will drown on them. You're mother, kiddo.
8==D

**Comment by Iamgoofball** [comment] 2015-06-04 19:52
8===D

**Comment by Iamgoofball** [comment] 2015-06-04 19:52
@Aranclanos ¯\_(ツ)_/¯

**Comment by Miauw62** [comment] 2015-06-04 19:56
fix your shit aran

**Comment by Firecage** [comment] 2015-06-05 11:48
God damnit @Aranclanos. Why did you remove this check and not test it @Aranclanos. Basically everyone at this point in Coderbus already knew what removing the check would do @Aranclanos, and we had several discussions about it @Aranclanos. @MrStonedOne was even planning to fix it so this issue doesn't pop up and already knew how @Aranclanos, but then you did this @Aranclanos

**Comment by Stickymayhem** [comment] 2015-06-05 12:58
This meme is two days old now.

**Comment by SconesC** [comment] 2015-06-05 19:23
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by Jalleo** [comment] 2015-06-06 22:03
Who said the nuke op shuttle dosent get stuck on ice?

**Comment by Incoming5643** [comment] 2015-06-07 21:39
Before the round even starts the rectangle that moves here has its area mass overwritten to the shuttle's area, how I have no idea, but if you could stop this and then put an area check it would probably fix things

**Closed** 2015-06-09 05:49 UTC
Labels: Bug, FUCK, Priority: CRITICAL
