### ISSUE TITLE
Powersinks are useless

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#9677] opened 2015-05-28 13:14 UTC
The powersink drain is less than the power generation in engineering if the singulo is set up properly, so they can't actually depower anything.

**Comment by xxalpha** [comment] 2015-05-28 13:46
Could be because of new MC, since the power output of the singulo engine hasn't changed and neither has the power sink drain.

**Comment by Jalleo** [comment] 2015-05-28 14:55
@MrStonedOne would you be able to get collate basic stats on what could be causing this?

**Comment by pudl** [comment] 2015-05-28 15:26
i noticed this many a years ago but i thought i was just shit at using powersinks. its a shame because a station with no power is the best kind of station

**Comment by xxalpha** [comment] 2015-05-28 18:24
>years ago

Must be completely unrelated.

**Comment by pudl** [comment] 2015-05-28 22:06
i wasnt saying many a years ago seriously, i meant like a few weeks but i was being a meme

**Comment by Lumipharon** [comment] 2015-05-29 00:38
I can confirm that powersinks seem to be fucked.

Went in as nuke ops, planted a sink on a wire (not a knot) waiting 5 minutes, nothing happened.
Moved the sink onto a knot, waiting 5 minutes, nothing happened.

It was screwdrivered in, and on, just the station wasn't losing any power, dunno why.

**Comment by Dorsisdwarf** [comment] 2015-05-29 09:30
Coding a fix for this

**Comment by MrStonedOne** [comment] 2015-05-29 10:34
its the 4th smes, it means they can overload a powersink because sinks only drain at 600kw

**Comment by xxalpha** [comment] 2015-05-29 20:40
Oh yeah, that happened.

**Comment by duncathan** [comment] 2016-01-24 20:22
FEED
BACK
FORUM

**Closed by duncathan** 2016-01-24 20:22 UTC
Labels: Not a bug

**Comment by Lumipharon** [comment] 2016-01-24 20:51
@duncathan 
how is this a FEEDBACK FORUM.
An item has 1 sole intended function. It is currently not working.

This is what experts call a BUG.

**Comment by xxalpha** [comment] 2016-01-24 20:55
More like an oversight.

**Comment by PKPenguin321** [comment] 2016-01-24 20:56
yeah, this should be kept open

**Comment by Lumipharon** [comment] 2016-01-24 20:57
>A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.
