### ISSUE TITLE
Cargo Tech jumpsuit is missing sprites

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/-tg-station#7236] opened 2015-01-21 00:26 UTC
The cargo tech's jumpsuit body sprites aren't showing, instead using the default 'SUIT' sprite

**Comment by dannno** [comment] 2015-01-21 01:10
Already reported

**Comment by WJohn** [comment] 2015-01-21 04:50
Dupe of #7205

**Closed** 2015-01-21 12:04 UTC
