### ISSUE TITLE
All-In-One-Grinder oversight

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8505] opened 2015-03-23 09:42 UTC
Grinder doesn't get the space/volume expansion from using bluespace beaker in it. It still assumes the container is Large Beaker for purposes of filling it up and grinding and won't allow to grind/fill to 300 units which the bluespace beaker holds.

**Comment by Jordie0608** [comment] 2015-03-23 11:17
I can't reproduce this nor do I see why it would happen.

https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/Chemistry-Machinery.dm#L1179
```		if (!beaker || (beaker && beaker.reagents.total_volume >= beaker.reagents.maximum_volume))```

**Comment by Marflowerose** [comment] 2015-03-23 12:04
Maybe it's an issue with plant bag, I was using one and it said "filled to brim" and only produced less than 90 units of stuff from dank.

**Comment by RandomMarine** [comment] 2015-03-23 18:40
The grinder has a cap of 10 items at once.

**Comment by phil235** [comment] 2015-04-04 17:49
I guess this was just a misunderstanding. Closing it.

**Closed by phil235** 2015-04-04 17:49 UTC
