### ISSUE TITLE
Revheads shouldn't instalose if they disconnect

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15159] opened 2016-02-03 03:47 UTC
>inb4 feedback forum

here is why:
1. only 3 heads of staff, so the game scales it down to there only being 1 revhead
2. said revhead's internet decides to shit itself 40 seconds into the round
3. the round instantly ends
4. the revhead reconnects and is met with anger/a ban

**Comment by WJohn** [comment] 2016-02-03 04:05
I say that antags who lose upon leaving the z level or hiding in a locker should be given some grace timer when disconnecting, maybe 3 mins or something.

**Comment by PKPenguin321** [comment] 2016-02-03 04:09
Especially so admins can have a chance to react and maybe put a new player in the body.

**Comment by Dorsisdwarf** [comment] 2016-02-03 08:48
thats hilarious

**Comment by tkdrg** [comment] 2016-02-03 09:27
Just make it message admins and then wait like 30 seconds, sorta like mulligan does

**Comment by Dorsisdwarf** [comment] 2016-02-03 17:41
Wait at least a minute because le byond ad memes

**Comment by PKPenguin321** [comment] 2016-02-03 22:32
this could probably do with a priority tag as i've seen more than one round get instacucked by this

**Comment by ChangelingRain** [comment] 2016-05-07 21:03
Duplicate of #13039

**Closed by ChangelingRain** 2016-05-07 21:03 UTC
Labels: Feature Request, Not a bug, Usability
