### ISSUE TITLE
Multiple people's locations being set to x y z 0 0 0

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8231] opened 2015-03-08 17:35 UTC
http://i.imgur.com/Xd9oAeR.png

This can happen to multiple people at the same time in the round.

Happened just now 08/03/2015 13:35

**Comment by Incoming5643** [comment] 2015-03-08 17:37
nullspace is a scary place

**Comment by phil235** [comment] 2015-03-08 21:49
How did that happen?

**Comment by WJohn** [comment] 2015-03-08 21:59
No idea, several people simultaneously got moved to 0 0 0. This is apparently a pretty common thing. They're reporting getting a black screen from this.

**Comment by Miauw62** [comment] 2015-03-09 15:53
Yeah their loc is probably null, if they were just at 000 they could still
move and such. This is a BIG FUCKING ISSUE
Op 8-mrt.-2015 18:35 schreef "WJohn" <notifications@github.com>:

**Comment by peoplearestrange** [comment] 2015-03-10 12:32
I've seen this a few times. It MAINLY happens during "Bluespace relocation" random events or any other kind of random teleportation (Unset handtele and artifacts too I think).

But 90% of the time ive seen it happen due to "Bluespace Relocation"

**Comment by Miauw62** [comment] 2015-03-10 18:28
im fairly sure we still have an open bug report with bluespace relocation
putting people in nullspace.
i distincly remember accidentally putting rr in nullspace by spamming
bluespace events.

**Comment by WJohn** [comment] 2015-06-15 07:51
This is still happening by the way. Just occurred today as someone walked into AI upload, they managed to get in on two bluegrid tiles so it's neither the floor nor the area that caused it.

**Comment by MrStonedOne** [comment] 2015-12-23 07:45
Please edit this issue or close it

XYZ being 0 doesn't matter, this is actually normal. Being inside a locker causes, being inside ANYTHING causes it, and it's 100% normal and intended.

loc is the var that matters.

Please edit this issue with the loc info for the mobs, of if you don't have it, close this issue.

**Comment by KorPhaeron** [comment] 2015-12-31 23:46
@WJohn 

Pretty sure we fixed most causes of this (gateway+singulo, spawn failure) and the issue is too vague/old otherwise

**Closed** 2016-01-01 00:48 UTC
Labels: Bug, Priority: CRITICAL
