### ISSUE TITLE
Breathing from oxygen tank inside box

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#12764] opened 2015-10-30 20:32 UTC
Steps to produce:

Take oxygen tank in hands
Put mask on face
Put tank back in your box
Put box in your backpack
You're still using internals.

**Comment by blobbernaut** [comment] 2015-10-30 22:04
I believe it is intended behavior that you're able to access stuff inside a container in your backpack, but NOT a container inside of that container, based on one of the comment lines I saw on a file when I was looking through the code.

**Comment by blobbernaut** [comment] 2015-10-30 22:04
You can open up a medkit in your backpack by click-dragging onto your character and releasing

**Comment by francinum** [comment] 2015-10-30 22:26
The tank part is unintended, being able to fully use a container inside a container, One layer deep, IS intended.

**Comment by xxalpha** [comment] 2015-10-30 23:21
Pretty sure you're not supposed to breathe from a tank that is not in your pockets, belt, hands or suit storage.

**Comment by sirnat** [comment] 2015-10-31 00:16
I tried it with a second way:

Take oxygen tank from box

Turn on internals

Store tank inside backpack

Internals don't work. 


Basically it works when in a box inside your backpack, but not inside your pack its self.

**Comment by tkdrg** [comment] 2015-11-13 20:34
I can't reproduce this by following either one of your instructions.

**Comment by phil235** [comment] 2016-02-14 13:32
Can't reproduce. Closing.

**Closed by phil235** 2016-02-14 13:32 UTC
Labels: Bug, In Game Exploit
