### ISSUE TITLE
Space suit dispenser break with power

### ISSUE THREAD

**Issue by Shodansbreak** [tgstation/-tg-station#15814] opened 2016-02-28 07:10 UTC
Space suit dispensers used to break with power, requiring you to crowbar them open to get the space suit inside. Someone changed the dispensers, so you cannot access their content without the power being on, even though you can see the item and it is accessible.
Possibly caused by the Nano-UI change?

**Comment by PKPenguin321** [comment] 2016-02-28 07:59
dupe of https://github.com/tgstation/-tg-station/issues/15164

**Closed** 2016-02-28 10:06 UTC
