### ISSUE TITLE
Player spiders should be able to see in the dark

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12056] opened 2015-09-28 03:27 UTC
People in OOC were talking a lot about a round of no antags but player spiders, but their lack of night vision would cripple them due to them being unable to really hide, forcing them into the hallways.

If this would be better suited to the feedback forum, let me know.

Also something that may or may not be a bug, wrapping living things as a nurse spider doesn't kill them or do any damage at all, even though it says you suck fluids out of the victim. This means you can keep wrapping things like monkeys or even people over and over again to keep getting a stupid amount of eggs.

**Comment by Dorsisdwarf** [comment] 2015-09-28 07:37
Dupe of #5740

**Closed by Dorsisdwarf** 2015-09-28 07:37 UTC
Labels: Balance, Feature Request
