### ISSUE TITLE
Items held by drones who die in pipes disappear

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#9274] opened 2015-05-02 03:23 UTC
Might apply to other mobs that die in pipes too. You'd expect the items to drop in the pipe, able to be retrieved upon deconstruction, but they don't.

I can see this being an issue if a drone takes an important item, is killed for it while trying to ventcrawl away, and successfully vent crawls before the death registers.

**Comment by Jalleo** [comment] 2015-05-02 07:22
@remierichards

**Comment by phil235** [comment] 2015-05-02 11:25
This is pretty much a duplicate of #9206

**Closed by phil235** 2015-05-02 11:25 UTC
