### ISSUE TITLE
Xenomorph strikes can knock cyborgs unconcious

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#11195] opened 2015-08-14 01:31 UTC
What it says on the tin. Gets the human KO hud overlay after one or two hits, can be happily pounded until dead.

**Comment by Anonus** [comment] 2015-08-14 01:48
Should only be normal stun, not knockout.

**Comment by Cebasiz** [comment] 2015-08-14 02:07
oh, i thought this was intentional, but made no sense, not that it was unintentional and made no sense. woops.

**Comment by Dorsisdwarf** [comment] 2015-08-14 22:20
Aliens disarming cyborgs have a special "push-back" stun which lasts for like 20 seconds it's redonculous

**Comment by WJohn** [comment] 2015-08-15 13:14
Yeah it's entirely too easy to stunlock cyborgs. Frankly I think it should give a VERY short stun that can at best allow you to stunlock them, but be unable to stun+kill them by yourself. If the stun duration were made so short that you couldn't even get a single swipe in (or very rarely able to) and require at least two aliens, then I think borgs would be worthwhile against xenos again.

**Comment by Cebasiz** [comment] 2015-08-15 16:22
you can kind of beat them if you are a VTEC illegal module secborg with lots of room to run

or you are a sneaky breeki guy with a plasma canister and an rcd

otherwise you're fucked though, note that hunterleap stuns you the same way as the knockback attack

**Comment by Dorsisdwarf** [comment] 2015-09-04 12:26
Related: #9061 ?

**Comment by tkdrg** [comment] 2016-01-24 20:06
yeah this is a dupe of #9061

**Closed by tkdrg** 2016-01-24 20:06 UTC
Labels: Bug, In Game Exploit
