### ISSUE TITLE
Attempting to hack a suit storage unit prompts an "Improper Argument" error window and crashes.

### ISSUE THREAD

**Issue by Rockinrhino** [tgstation/-tg-station#9413] opened 2015-05-09 00:56 UTC
Doesn't seem to matter if suit storage is open or closed at the time.  As soon as you screwdriver the Storage Unit, the error window pops up.

Version I had when I got the error: 507.1284.
Downgraded to Franc's version.... no issue.

**Comment by francinum** [comment] 2015-05-09 00:58
Cannot Reproduce

**Comment by Rockinrhino** [comment] 2015-05-09 01:02
Attempting to figure out if it's a byond version issue.

**Comment by Rockinrhino** [comment] 2015-05-09 01:09
Version I had when I got the error: 507.1284.
Downgraded to Franc's version.... no issue.

**Comment by phil235** [comment] 2015-08-08 10:06
Can't reproduce with the latest BYOND version that we use. Since it appears that it was an issue with 807.1284, all that's needed to prevent the bug is to update your Byond version. Closing this.

**Closed by phil235** 2015-08-08 10:06 UTC
Labels: Bug, Cannot Reproduce
