### ISSUE TITLE
Virology smart fridge cannot vend you your custom-made virus bottles back.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9484] opened 2015-05-13 22:17 UTC
What it says on the tin. It won't even try to vend it back to you. This occurred with a sneeze + stim culture bottle.

**Comment by Alek2ander** [comment] 2015-05-13 22:24
I'm sure this was already reported several times. Caused by the + in the name which conflicts with one of BYOND's special control characters.

**Comment by PKPenguin321** [comment] 2015-05-13 23:33
Yeah, this is likely a duplicate. Workaround is to just avoid using any characters that aren't letters. (No punctuation/numbers etc, replace 1 with I and 2 with II etc.)

**Comment by phil235** [comment] 2015-05-14 00:20
Duplicate of #4708

**Closed by phil235** 2015-05-14 00:20 UTC
