### ISSUE TITLE
Flymen eating is janky

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#16726] opened 2016-04-07 23:12 UTC
As a member of the flyman race, eating is difficult. You don't gain nutrition because every time you take a bite, you vomit, which would be fine and actually cool if the vomit gave you nutrition, but it doesn't, so the only way to avoid starving forever is to inject nutriment into your body with medbay.

In addition, vomiting after taking a bite of food causes you to be frozen in place, unable to move or do interact with anything, as well as causing you to drop whatever items you hold.

**Comment by PKPenguin321** [comment] 2016-04-07 23:51
actually vomit has no nutriment due to a bug with vomiting
so this bug report is inaccurate and technically a dupe (at the least the first part is)

**Comment by coiax** [comment] 2016-04-08 22:02
Normally throwing up does make a person stunned and drop what their holding.

So you can either

1. make flymen immune to being stunned and itemdropping by vomiting (have a benefit to being a flyman, convenience vomiting)
2. just make the vomiting reaction to nutriment eating just not stunning

**Comment by Jalleo** [comment] 2016-04-19 23:48
I can actually confirm that the issue is actually with the throwing up itself. If you have no nutrient you cant vomit it up and eating itself is causing the vomit before your nutrient is transferred over to you to go into the vomit. Specific message is saying that you have nothing in the stomach to throw up.

**Comment by phil235** [comment] 2016-04-20 11:30
Just revert https://github.com/tgstation/-tg-station/pull/15698

**Comment by coiax** [comment] 2016-04-23 22:19
Dupe of #16693

**Closed** 2016-04-23 22:35 UTC
Labels: Bug
