### ISSUE TITLE
The Shard Reckoning

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10453] opened 2015-07-07 20:41 UTC
Disposals just caused this
has deleted all (3991) instances of /obj/item/weapon/shard.
Occured while #10452 was happening but I dont know if they are related

**Comment by tkdrg** [comment] 2015-12-23 21:26
Probably fixed by #10872, given that it hasn't happened since then. We also do not have enough information to reproduce this in any meaningful way, so I'm closing me. Feel free to ping me or another maintainer if you disagree.

**Closed by tkdrg** 2015-12-23 21:26 UTC
Labels: Bug, Cannot Reproduce
