### ISSUE TITLE
Oxygen damage is completely broken.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12418] opened 2015-10-15 20:49 UTC
How to reproduce:

- Get your internals
- Set the distribution pressure to something low as fuck, like 6
- You get the O2 alert and start gasping, but your health does not decline and you do not pass out.

Apparently this also works in siphoned rooms (but you still take pressure damage probably

**Comment by phil235** [comment] 2015-10-15 21:04
Apparently, as long as oxygen amounts in the tile or in your tank are not literally 0 you don't take oxy damage.

**Comment by freerealestate** [comment] 2015-10-15 21:10
I think this bug has been around for months now. Didn't report it because wasn't sure if it just meant low oxygen (but still breathable) or not, with the new screen alerts.

**Comment by bgobandit** [comment] 2015-10-15 21:12
@phil235 literally 0 works too, at least distribution amount

**Comment by phil235** [comment] 2015-10-15 22:08
origin: https://github.com/tgstation/-tg-station/blob/61d23d8c1112fdc45bce2e8422122ca136aa248b/code/modules/mob/living/carbon/human/species.dm#L1206 
Even if the mob doesn't require co2 to breath it still gets the oxyloss heal from it.

**Comment by WJohn** [comment] 2015-10-15 22:50
Dupe of #10420 but this is more accurate, so I'll close the old one.

**Closed** 2015-10-20 22:06 UTC
Labels: Bug, In Game Exploit, Priority: High
