### ISSUE TITLE
You can get past plastic flaps with a box

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#12129] opened 2015-10-03 22:05 UTC
What it says on the tin. Boxes, like lockers can go through plastic flaps. Unlike lockers, the person hiding inside can move while inside it to get through.

**Comment by RemieRichards** [comment] 2015-10-03 22:10
Arguably a feature.

**Comment by Miauw62** [comment] 2015-10-03 22:30
If it's a feature, it's unbalanced and should be fixed.
Op 4-okt.-2015 00:10 schreef "Remie Richards" <notifications@github.com>:

**Comment by Supermichael777** [comment] 2015-10-03 22:56
you can get under flaps with a friend anyhow. they arn't that big a hindrance to anyone but a solo antag.

**Comment by Lumipharon** [comment] 2015-10-03 23:21
Yes but there is a big difference between being able to do something with 2 people, an being able to do something on your own.

Also this means you can get into almost every department from maint, with just a common box.

**Comment by RemieRichards** [comment] 2015-10-04 00:03
>Also this means you can get into almost every department from maint, with just a common box.

Just spent a round on sybil doing this, you really can't.
I got into: 
* Engineering (Ok, that's pretty bad, but I was an Assistant with insuls and tools so I could have anyway)
* Botany
* Chef
* Bar
* Atmos Office
* Cargo Office
* Head Meeting Room

None of these places, Except Engineering, are even remotely important.
Not to mention, as I said, as assistant if you want into those places you already can get in.

**Comment by Lumipharon** [comment] 2015-10-04 00:43
Hacking airlocks require you to actually take the time to figure out wires before hand.

Box requires nothing but the box.

It's not some huge balance concern, but it's clearly not intended behavior, plastic flaps exist purely to move objects one way without letting people through.

Atleast stuff like abusing a mulebot requires specific access/tools to do.

**Comment by Incoming5643** [comment] 2015-10-04 05:44
This is a feature. Nearly all department flaps have windoors behind them, and those are harder to break down than the windows that are likely to be right next door to the flaps.

When I mentioned if anyone had figured out the "secret box technique" yet, this is what I was alluding to.

**Comment by tuypo1** [comment] 2015-10-04 06:24
it just plain makes no sense that you cant go through as a human anyway but we live with it this is just inconsistency

**Comment by Incoming5643** [comment] 2015-10-04 06:25
I'll fix this if people really think it's hyper unbalancing, but I just thought it was a funny lampshading on plastic flaps amazing ability to detect and exclude mobs.

**Comment by RemieRichards** [comment] 2015-10-04 14:50
No, keep it, it's fine, like you said, I did encounter a windoor at EVERY plastic flap except for cargo's office conveyor on Box, and as I said above, those departments aren't important anyway.

**Comment by Miauw62** [comment] 2015-10-04 15:25
this should really be fixed. plastic flaps have always been ment to be impassible to humans and they should really be.

**Comment by RemieRichards** [comment] 2015-10-04 15:27
@Miauw62 are you just ignoring every point to the contrary? you can't do -anything- bad or special with this beyond some minor hilarity. it's FINE.

**Comment by Miauw62** [comment] 2015-10-04 16:02
mapper: "oh hey let me just put these plastic flaps here to let mules in but keep the area secure, humans cant pass through"

and then the area is looted every round with boxes.

**Comment by RemieRichards** [comment] 2015-10-04 16:04
That's a stupid mapper.

**Comment by Miauw62** [comment] 2015-10-04 16:34
lets just let everybody walk through plastic flaps, then.

**Comment by RemieRichards** [comment] 2015-10-04 16:34
Reductio ad absurdum is not a good way to argue.

**Comment by Miauw62** [comment] 2015-10-04 17:45
all im asking for is some consistency

**Comment by Iamgoofball** [comment] 2015-10-04 18:00
why do we even have plastic flaps ffs they're dumb and can't be deconstructed/moved unlike every other item in the game and die only to bombs

**Comment by Anonus** [comment] 2015-10-04 18:02
It's a bigger problem for dreamstation because I wanted to disperse with the windoor+window shit other maps do, so someone with a box has way too easy of a time getting in and doing shit.

**Comment by Zilenan91** [comment] 2015-10-04 19:19
You can also get into R&D with these which is kind of a big deal if you have science access or want to print some weapons out for yourself then skedaddling.

**Comment by RemieRichards** [comment] 2015-10-04 19:22
>getting into RD with science access is a big deal

what.

**Comment by Bawhoppen** [comment] 2015-10-05 03:08
It makes sense if you're under a box crouching down you'd be small enough to crawl under some flaps.
You can't go through airtight plastic flaps with a box I believe. Make the high securiy locations have those, and then leave the feature it.

**Comment by Anonus** [comment] 2015-10-05 04:05
You can go through airtight flaps too, so nope.

**Comment by Miauw62** [comment] 2015-10-05 15:37
its the difference between disassembling an rwall and breaking a windoor or a normal rwindow, remie.

**Comment by RemieRichards** [comment] 2015-10-05 15:38
@Miauw62 >RD >Science Access >Big Deal

**Comment by Incoming5643** [comment] 2015-10-05 15:43
I'm not 100% sure on this, but I think a windoor actually takes more hits than a rwindow

**Comment by Miauw62** [comment] 2015-10-05 15:45
just an example of this being pretty bullshitty: you put rwalls on an area to make it secure yet a simple /CARDBOARD BOX/ can completely negate this.

it doesn't make sense.

**Comment by Incoming5643** [comment] 2015-10-05 15:47
A full tile Rwindow has 100 health
A standard windoor has 150 health
Thus: Replace all r windows with windoors

**Comment by Aranclanos** [comment] 2015-10-05 15:58
remove boxes REMOVE BOXES REMOVEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Incoming5643** [comment] 2015-10-05 16:39
IT'S TOO LATE IT'S CODIFIED IN TG CULTURE NOW

**Comment by Incoming5643** [comment] 2015-10-05 16:44
Also this is more a problem with plastic flaps than boxes.

I invite everyone to look at how dumb plastic flap code is
https://github.com/tgstation/-tg-station/blob/15e50de0feb35850e348919d8f20cb63777fafc7/code/game/machinery/computer/shuttle.dm#L77

**Comment by Iamgoofball** [comment] 2015-10-05 23:49
Yeah, I'm going to argue that plastic flaps are FUCKING ATROCIOUS and that boxes aren't the problem here

instead of defending old shitcode let's fix it

**Comment by Dorsisdwarf** [comment] 2015-10-07 13:41
This is one of the most commented issues ever and it's a confirmed feature

/tg/station13

**Comment by Miauw62** [comment] 2015-10-07 14:38
i really hate the sentiment where people think something is fine if the person who made it says its fine

by that logic we should still have autorifles in their original form and arans recent memery is also perfectly fine.

**Comment by Incoming5643** [comment] 2015-10-07 16:39
I said I'd fix it if people really didn't think it was fine.

but boy the fix wouldn't be pretty given what flaps look like right now.

**Comment by Iamgoofball** [comment] 2015-10-08 02:25
Remove flaps

**Comment by Anonus** [comment] 2015-10-08 02:43
Please fix it because I'd rather my map didn't get dunked on by an antag sneaking around in a box, as fun as that would be to watch.

**Comment by Dorsisdwarf** [comment] 2015-10-08 13:48
Most commented issues ever about boxes: 1

**Closed** 2015-10-28 16:39 UTC
Labels: Balance, Not a bug
