### ISSUE TITLE
New chems not working as they are intended to, Cult got nerfed by proxy for no reason from this chance

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/-tg-station#7178] opened 2015-01-19 00:44 UTC
Right now there's a lack of balance for the new chemistry system. The emergency medipens are used less for trying to keep people alive but instead are used instead for the knockdown side effect to steal guns from security or nuke ops or just stunning the wizard and getting BWOINKed over it.

Also patches are doing 1:1 heals so it would take upwards of 6 patches to heal someone who was set on fire with light fire damage. Someone who got a large amount of fire damage requires over 15! patches. It shouldn't take over a hundred patches from chemistry just to deal with a mass causality event.

Stealth cult also got nerfed with the medbot change meaning that you always have to convert medbay to keep up with the research requirements.

Just bringing it up because it seems right now coderbus is unaware of the problems.

**Comment by tkdrg** [comment] 2015-01-19 02:42
Emergency medipens are bugged, they will be fixed soon.
Patches take time to work, they don't instaheal like bruise packs, they're more like sleepers in that you have to wait. Each patch should heal double its unit amount.
Medbots were nerfed yes, maybe we can look into other ways of letting cult heal.
@Iamgoofball

**Comment by StuAhpla** [comment] 2015-01-19 02:47
Do the patches heal bodywide like chems or just locational like packs?

**Comment by Iamgoofball** [comment] 2015-01-19 03:39
bodywise

**Comment by Tenebrosity** [comment] 2015-01-19 08:21
I think you need to actually try the patches out for yourself while playing medical doctor on the server because they're very weak

**Comment by StuAhpla** [comment] 2015-01-19 08:27
How fast does it heal though?

**Comment by Lumipharon** [comment] 2015-01-20 00:05
cultists can use the blood drain rune to heal, but that's obviously a far from ideal solution.

**Comment by StuAhpla** [comment] 2015-01-20 00:25
Well I assume coderbus is aware of the saline bug as well, if not then some random chemicals were improperly replaced with saline which I assume was a fallback dummy chemical for if someone added a bottle with an improper chemical in the code

**Comment by Iamgoofball** [comment] 2015-01-20 00:44
@StuAhpla never assume we are aware of a bug

ever

always make an issue report

what exactly is the bug

**Comment by StuAhpla** [comment] 2015-01-20 00:46
I haven't experenced it myself but other medical players say that a lot of the chemical bottles's contents were replaced with saline instead of the listed chemical, including the current upgraded sleeper were apparently saline is repeated several times according to one person

**Comment by Miauw62** [comment] 2015-01-20 17:00
nonexistant chems are supposed to throw a fucking error, not just silently fail and do some dumb bullshit that is completely fucking invisible and doesnt produce any debugging output. that's php-level bullshit.

**Comment by tkdrg** [comment] 2015-01-20 17:45
There's a warning printed to world.log
Saline is an existing chem that has an actual intended effect. It's just that it provides very low-level healing.

**Comment by Miauw62** [comment] 2015-01-23 16:28
@Iamgoofball pls do something

**Comment by Iamgoofball** [comment] 2015-01-24 02:11
@Miauw62 i'm looking and most of this is higgs bugson such as epipens knocking you out, i can't reproduce it locally

**Comment by Iamgoofball** [comment] 2015-01-31 00:54
epipens have been fixed for ages
there's a PR up to increase the on tick effects of styptic and silver sulf, and since those transfer into the mob after patch applications this should make you only need like 1-2 patches
saline-glucose appears to be working as intended

**Closed** 2015-02-06 00:16 UTC
Labels: Balance
